# Import libraries and dataset into environment

In [1]:
import dill
import os
import sys
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
import math as mt
import shap
from sklearn.metrics import confusion_matrix, roc_curve, auc
from MLstatkit import Bootstrapping
import json
import gc
from joblib import Parallel, delayed, externals
import multiprocessing
num_cores = multiprocessing.cpu_count() - 1
import defined_functions
from defined_functions import sum_metric, met_collate_func
defined_functions.pd = pd

In [2]:
path = os.getcwd()
sys.path.append(path)

save_file = os.path.join(path, "session.pkl")

with open(save_file, "rb") as f:
    state = dill.load(f)

split_list_valid_smote = state["split_list_valid_smote"]
split_list_valid_smote_final = state["split_list_valid_smote_final"]
split_list_fil_valid_smote_final = state["split_list_fil_valid_smote_final"]
split_list_sim_onset_valid_smote_final = state["split_list_sim_onset_valid_smote_final"]
split_list_vldiag_valid_smote_final = state["split_list_vldiag_valid_smote_final"]
split_list_diag1_valid_smote_final = state["split_list_diag1_valid_smote_final"]
split_list_diag2_valid_smote_final = state["split_list_diag2_valid_smote_final"]

# Define functions

In [3]:
# Define function to train Lasso regression model
def run_single_lasso_split(i, split):
    train_df = split['train'].copy()
    valid_df = split['valid'].copy()
    test_df = split['test'].copy()

    train_df['outcome'] = train_df['outcome'].cat.reorder_categories(["Non severe", "Severe"], ordered = False)
    valid_df['outcome'] = valid_df['outcome'].cat.reorder_categories(["Non severe", "Severe"], ordered = False)
    test_df['outcome'] = test_df['outcome'].cat.reorder_categories(["Non severe", "Severe"], ordered = False)

    train_x = train_df.drop(columns = ['outcome'])
    valid_x = valid_df.drop(columns = ['outcome'])
    test_x = test_df.drop(columns = ['outcome'])

    features = list(train_x.columns)
    cat_cols = ['age', 'gender', 'vaccination', 'comorbidity']
    for col in cat_cols:
        train_x[col] = train_x[col].astype('category')
        valid_x[col] = valid_x[col].astype('category')
        test_x[col] = test_x[col].astype('category')

    train_x = pd.get_dummies(train_x, columns = cat_cols, drop_first = False)
    valid_x = pd.get_dummies(valid_x, columns = cat_cols, drop_first = False)
    test_x = pd.get_dummies(test_x, columns = cat_cols, drop_first = False)

    feature_names = train_x.columns.tolist()

    # Force valid/test to have same columns and same order as train
    valid_x = valid_x.reindex(columns = feature_names, fill_value = 0)
    test_x = test_x.reindex(columns = feature_names, fill_value = 0)
    
    mapping = {"Non severe": 0, "Severe": 1}
    
    train_y = train_df['outcome'].map(mapping).astype(int)
    valid_y = valid_df['outcome'].map(mapping).astype(int)
    test_y = test_df['outcome'].map(mapping).astype(int)
    lasso = LogisticRegression(
        penalty = 'l1',  # Perform L1-regularization/Lasso regression
        solver = 'liblinear',
        l1_ratio = 1.0,
        C = 0.1,   # Inverse of regularization strength
        class_weight = {0: 1, 1: 1.25},    # Define wights associated with classes
        max_iter = 1000,
        random_state = 123
    )

    lasso_model = lasso.fit(train_x, train_y)

    # Make predictions on Testing set
    lasso_pred_prob = lasso_model.predict_proba(test_x)[:, 1]

    # Calculate Area Under the ROC curve
    fpr, tpr_curve, _ = roc_curve(test_y, lasso_pred_prob, pos_label = 1)
    auc_val_lasso = auc(fpr, tpr_curve)

    # Store standard structure dictionary
    roc_container = {
        'actual': test_y,
        'probabilities': lasso_pred_prob
    }
    
    # Calculate Area Under the Precision-Recall Curve (AUPRC / PR-AUC)
    auprc_val, prc_ci_lower, prc_ci_upper = Bootstrapping(test_y, lasso_pred_prob, 'pr_auc')

    # Convert predicted probabilities to the labels
    lasso_pred = lasso_model.predict(test_x).astype(int)
    lasso_pred_res = np.where(lasso_pred == 0, "Non severe", "Severe")
    
    # Compute Confusion Matrix (Test)
    tn, fp, fn, tp = confusion_matrix(test_y, lasso_pred, labels = [0, 1]).ravel()
    
    # Format a formal R-styled evaluation matrix lookup dataframe 
    cfm_lasso = pd.DataFrame(
        [[tn, fp], [fn, tp]], 
        index = ["Non severe", "Severe"], 
        columns = ["Non severe", "Severe"]
    )
    cfm_lasso.index.name = 'Prediction'
    cfm_lasso.columns.name = 'Observed'
    
    # Calculate performance metrics
    accuracy_lasso = (tp + tn) / (tn + fp + fn + tp) if (tn + fp + fn + tp) > 0 else 0
    sensitivity_lasso = tp / (tp + fn) if (tp + fn) > 0 else 0
    specificity_lasso = tn / (tn + fp) if (tn + fp) > 0 else 0
    npv_lasso = tn / (tn + fn) if (tn + fn) > 0 else 0
    precision_lasso = tp / (tp + fp) if (tp + fp) > 0 else 0
        
    # Make predictions on Training Set to gather accuracy
    lasso_pred_train_prob = lasso_model.predict_proba(train_x)[:, 1]
    lasso_pred_train = lasso_model.predict(train_x).astype(int)
    tn_tr, fp_tr, fn_tr, tp_tr = confusion_matrix(train_y, lasso_pred_train, labels = [0, 1]).ravel()
    accuracy_lasso_train = (tp_tr + tn_tr) / (tn_tr + fp_tr + fn_tr + tp_tr)
    
    masker = shap.maskers.Independent(train_x)
    explainer = shap.LinearExplainer(model = lasso_model, masker = masker)
    shap_values = explainer(train_x).values

    return {
        "model": lasso_model,
        "confusion_matrix": cfm_lasso,
        "accuracy_training": accuracy_lasso_train,
        "accuracy_testing": accuracy_lasso,
        "sensitivity": sensitivity_lasso,
        "specificity": specificity_lasso,
        "precision": precision_lasso,
        "npv": npv_lasso,
        "roc": roc_container,
        "AUC_value": auc_val_lasso,
        "PRC_val": auprc_val,
        "PRC_lower_ci": prc_ci_lower,
        "PRC_upper_ci": prc_ci_upper,
        "SHAP_values": shap_values,
        "prediction": lasso_pred_res,
        "pred_prob": lasso_pred_prob
    }

# Define function to train Lasso regression for 100 times in parallel
def model_func_lasso_tune(data_list):
    
    # Count system resource availability profiles
    num_cores = multiprocessing.cpu_count() - 1
    
    if __name__ == '__main__':
        try:
            result_list = Parallel(n_jobs = num_cores)(
                delayed(run_single_lasso_split)(i, data_list[i]) 
                for i in range(100)
                )
        finally:
            externals.loky.get_reusable_executor().shutdown(wait = True)
            gc.collect()

    return result_list

# Fitting dataset into the model

## Fitting data list without VL information

In [4]:
lasso_fil_list = model_func_lasso_tune(split_list_fil_valid_smote_final)
lasso_fil_met_summary = sum_metric(lasso_fil_list)
lasso_fil_metrics_summary = lasso_fil_met_summary["metric_summary"]
lasso_fil_summary = met_collate_func(lasso_fil_metrics_summary).assign(
    models = "Lasso regression (No VL info & SMOTE)"
)
lasso_fil_summary

/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:  16%|█▌        | 157/1000 [00:00<00:00, 1563.75it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:  30%|██▉       | 297/1000 [00:00<00:00, 1495.21it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:  32%|███▏      | 316/1000 [00:00<00:00, 1574.30it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:  30%|██▉       | 298/1000 [00:00<00:00, 1162.09it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:  12%|█▏        | 118/1000 [00:00<00:00, 1175.78it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:  47%|████▋     | 474/1000 [00:00<00:00, 1366.75it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1409.70it/s]
Bootstrapping pr_auc:  72%|███████▏  | 717/1000 [00:00<00:00, 1294.31it/s]Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1482.41it/s]
Bootstrapping pr_auc:  42%|████▏     | 419/1000 [00:00<00:00, 1468.89it/s]Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1417.37it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1434.58it/s]
Bootstrapping pr_auc:  91%|█████████ | 911/1000 [00:00<00:00, 1283.24it/s]Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1305.00it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1277.14it/s]
/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1322.37it/s]
Bootstrapping pr_auc:  58%|█████▊    | 584/1000 [00:00<00:00, 1536.92it/s]Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1372.84it/s]
Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Bootstrapping pr_auc:  94%|█████████▍| 939/1000 [00:00<00:00, 1441.60it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1481.94it/s]
Bootstrapping pr_auc:  75%|███████▍  | 746/1000 [00:00<00:00, 1238.98it/s]Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1541.54it/s]
Bootstrapping pr_auc:  81%|████████  | 810/1000 [00:00<00:00, 1336.24it/s]Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1556.01it/s]
Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:  15%|█▌        | 154/1000 [00:00<00:00, 1538.67it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:  15%|█▌        | 150/1000 [00:00<00:00, 1499.45it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1295.00it/s]
/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1276.80it/s]
Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Bootstrapping pr_auc:  90%|█████████ | 902/1000 [00:00<00:00, 1200.75it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1510.88it/s]
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1353.66it/s]
Bootstrapping pr_auc:  16%|█▌        | 160/1000 [00:00<00:00, 1599.22it/s]Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Bootstrapping pr_auc:  16%|█▌        | 158/1000 [00:00<00:00, 1571.90it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(

bound,Metrics,estimate,lower,upper,models
0,AUPRC_value,36.2211,16.5175,59.5285,Lasso regression (No VL info & SMOTE)
1,AUROC_value,92.1385,83.2469,97.5273,Lasso regression (No VL info & SMOTE)
2,Accuracy,86.8308,80.1888,92.4471,Lasso regression (No VL info & SMOTE)
3,Accuracy_train,87.9117,83.2931,91.9821,Lasso regression (No VL info & SMOTE)
4,NPV,99.4476,98.6274,100.0000,Lasso regression (No VL info & SMOTE)
5,Precision,17.3534,11.1708,25.4234,Lasso regression (No VL info & SMOTE)
6,Sensitivity,84.3000,60.0000,100.0000,Lasso regression (No VL info & SMOTE)
7,Specificity,86.9097,79.7352,93.1620,Lasso regression (No VL info & SMOTE)

## Fitting data list with simulated VL at symptom onset

In [5]:
lasso_vlsymp_sim_list = model_func_lasso_tune(split_list_sim_onset_valid_smote_final)
lasso_vlsymp_sim_met_summary = sum_metric(lasso_vlsymp_sim_list)
lasso_vlsymp_sim_metrics_summary = lasso_vlsymp_sim_met_summary["metric_summary"]
lasso_vlsymp_sim_summary = met_collate_func(lasso_vlsymp_sim_metrics_summary).assign(
    models = "Lasso regression (VL symp simulated & SMOTE)"
)
lasso_vlsymp_sim_summary

/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:   7%|▋         | 71/1000 [00:00<00:01, 706.64it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:  16%|█▌        | 159/1000 [00:00<00:00, 1589.13it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:  31%|███▏      | 314/1000 [00:00<00:00, 1441.40it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1535.19it/s]
Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1594.54it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1452.88it/s]
Bootstrapping pr_auc:  81%|████████  | 810/1000 [00:00<00:00, 1456.89it/s]Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1459.46it/s]
Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1377.67it/s]
Bootstrapping pr_auc:  91%|█████████ | 911/1000 [00:00<00:00, 1526.31it/s]Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1307.00it/s]
Bootstrapping pr_auc:  68%|██████▊   | 684/1000 [00:00<00:00, 1411.38it/s]Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1278.65it/s]
Bootstrapping pr_auc:  96%|█████████▌| 956/1000 [00:00<00:00, 1451.50it/s]Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1517.01it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1437.12it/s]
Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1353.79it/s]
Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1225.52it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1314.86it/s]
Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1412.49it/s]
Bootstrapping pr_auc:  84%|████████▍ | 845/1000 [00:00<00:00, 1477.46it/s]Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1353.57it/s]
Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1415.08it/s]
/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:  15%|█▍        | 149/1000 [00:00<00:00, 1486.54it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:  16%|█▌        | 158/1000 [00:00<00:00, 1569.56it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:  15%|█▌        | 153/1000 [00:00<00:00, 1519.36it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:  32%|███▏      | 324/1000 [00:00<00:00, 1589.35it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:  13%|█▎        | 126/1000 [00:00<00:00, 1253.48it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1456.21it/s]

bound,Metrics,estimate,lower,upper,models
0,AUPRC_value,35.0961,16.4274,61.0831,Lasso regression (VL symp simulated & SMOTE)
1,AUROC_value,91.9813,83.4186,97.7321,Lasso regression (VL symp simulated & SMOTE)
2,Accuracy,86.6586,78.6782,92.4471,Lasso regression (VL symp simulated & SMOTE)
3,Accuracy_train,87.9154,83.3749,92.0093,Lasso regression (VL symp simulated & SMOTE)
4,NPV,99.4360,98.6274,100.0000,Lasso regression (VL symp simulated & SMOTE)
5,Precision,17.1672,11.0167,25.4234,Lasso regression (VL symp simulated & SMOTE)
6,Sensitivity,84.0000,60.0000,100.0000,Lasso regression (VL symp simulated & SMOTE)
7,Specificity,86.7414,78.3411,93.1620,Lasso regression (VL symp simulated & SMOTE)

## Fitting data list with VL at diagnosis

In [6]:
lasso_vldiag_list = model_func_lasso_tune(split_list_vldiag_valid_smote_final)
lasso_vldiag_met_summary = sum_metric(lasso_vldiag_list)
lasso_vldiag_metrics_summary = lasso_vldiag_met_summary["metric_summary"]
lasso_vldiag_summary = met_collate_func(lasso_vldiag_metrics_summary).assign(
    models = "Lasso regression (VL diag & SMOTE)"
)
lasso_vldiag_summary

/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:  16%|█▌        | 157/1000 [00:00<00:00, 1561.20it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:  16%|█▌        | 160/1000 [00:00<00:00, 1596.81it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:   9%|▉         | 93/1000 [00:00<00:00, 925.09it/s]s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:  16%|█▌        | 159/1000 [00:00<00:00, 1581.66it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1582.32it/s]
Bootstrapping pr_auc:  96%|█████████▌| 959/1000 [00:00<00:00, 1579.57it/s]Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1555.52it/s]
Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1446.83it/s]
Bootstrapping pr_auc:  70%|███████   | 702/1000 [00:00<00:00, 1422.60it/s]Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1387.76it/s]
Bootstrapping pr_auc:  86%|████████▌ | 862/1000 [00:00<00:00, 1420.94it/s]Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1464.05it/s]
Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1310.65it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1424.81it/s]
Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1525.74it/s]
Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1327.17it/s]
/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1462.01it/s]
Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1386.18it/s]
Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1338.21it/s]
Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1452.49it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1269.40it/s]
/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Bootstrapping pr_auc:  16%|█▌        | 155/1000 [00:00<00:00, 1541.72it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1237.15it/s]
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Bootstrapping pr_auc:  15%|█▌        | 151/1000 [00:00<00:00, 1507.30it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:  15%|█▌        | 151/1000 [00:00<00:00, 1501.98it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:  30%|███       | 302/1000 [00:00<00:00, 1501.75it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:  46%|████▌     | 456/1000 [00:00<00:00, 1419.42it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:  10%|▉         | 95/1000 [00:00<00:00, 949.91it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1349.26it/s]

bound,Metrics,estimate,lower,upper,models
0,AUPRC_value,40.4548,17.9522,64.7000,Lasso regression (VL diag & SMOTE)
1,AUROC_value,92.9492,83.3583,97.8520,Lasso regression (VL diag & SMOTE)
2,Accuracy,87.1420,79.4562,92.6057,Lasso regression (VL diag & SMOTE)
3,Accuracy_train,88.8307,85.0169,92.4714,Lasso regression (VL diag & SMOTE)
4,NPV,99.4584,98.6532,100.0000,Lasso regression (VL diag & SMOTE)
5,Precision,17.8153,11.5994,27.3667,Lasso regression (VL diag & SMOTE)
6,Sensitivity,84.6000,60.0000,100.0000,Lasso regression (VL diag & SMOTE)
7,Specificity,87.2212,78.9642,92.8505,Lasso regression (VL diag & SMOTE)

## Fitting data list with VL at diagnosis & VL at 1-day after diagnosis

In [7]:
lasso_add1_list = model_func_lasso_tune(split_list_diag1_valid_smote_final)
lasso_add1_met_summary = sum_metric(lasso_add1_list)
lasso_add1_metrics_summary = lasso_add1_met_summary["metric_summary"]
lasso_add1_summary = met_collate_func(lasso_add1_metrics_summary).assign(
    models = "Lasso regression (VL diag + 1 & SMOTE)"
)
lasso_add1_summary

/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:  15%|█▌        | 152/1000 [00:00<00:00, 1509.79it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:  13%|█▎        | 133/1000 [00:00<00:00, 1325.57it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:  32%|███▏      | 318/1000 [00:00<00:00, 1586.13it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:  32%|███▏      | 324/1000 [00:00<00:00, 1558.59it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1541.06it/s]
Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1390.88it/s]
Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1421.72it/s]
Bootstrapping pr_auc:  84%|████████▍ | 839/1000 [00:00<00:00, 1299.84it/s]Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1465.59it/s]
Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1483.45it/s]
Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1398.09it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1345.17it/s]
Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1368.09it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1358.55it/s]
Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1266.20it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1342.89it/s]
Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1332.09it/s]
Bootstrapping pr_auc:  84%|████████▍ | 843/1000 [00:00<00:00, 1384.11it/s]Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:  93%|█████████▎| 926/1000 [00:00<00:00, 1140.29it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]1371.29it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1354.17it/s]
Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1321.73it/s]
Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1195.10it/s]
Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:  16%|█▌        | 156/1000 [00:00<00:00, 1555.24it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:  16%|█▌        | 160/1000 [00:00<00:00, 1598.01it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:  16%|█▌        | 156/1000 [00:00<00:00, 1552.41it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:  31%|███▏      | 314/1000 [00:00<00:00, 1562.50it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:  15%|█▌        | 154/1000 [00:00<00:00, 1534.35it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:  31%|███▏      | 313/1000 [00:00<00:00, 1565.40it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:  64%|██████▍   | 643/1000 [00:00<00:00, 1599.06it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1567.31it/s]

bound,Metrics,estimate,lower,upper,models
0,AUPRC_value,39.4551,16.8041,65.9939,Lasso regression (VL diag + 1 & SMOTE)
1,AUROC_value,93.2361,84.5413,98.1877,Lasso regression (VL diag + 1 & SMOTE)
2,Accuracy,87.4743,80.0453,92.4471,Lasso regression (VL diag + 1 & SMOTE)
3,Accuracy_train,89.3583,85.6179,92.9660,Lasso regression (VL diag + 1 & SMOTE)
4,NPV,99.4514,98.6124,100.0000,Lasso regression (VL diag + 1 & SMOTE)
5,Precision,18.1258,11.9171,27.2727,Lasso regression (VL diag + 1 & SMOTE)
6,Sensitivity,84.3000,60.0000,100.0000,Lasso regression (VL diag + 1 & SMOTE)
7,Specificity,87.5732,79.7352,92.8349,Lasso regression (VL diag + 1 & SMOTE)

## Fitting data list with VL at diagnosis & VL at 2-days after diagnosis

In [8]:
lasso_add2_list = model_func_lasso_tune(split_list_diag2_valid_smote_final)
lasso_add2_met_summary = sum_metric(lasso_add2_list)
lasso_add2_metrics_summary = lasso_add2_met_summary["metric_summary"]
lasso_add2_summary = met_collate_func(lasso_add2_metrics_summary).assign(
    models = "Lasso regression (VL diag + 2 & SMOTE)"
)
lasso_add2_summary

/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:  16%|█▌        | 162/1000 [00:00<00:00, 1612.13it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:  16%|█▌        | 155/1000 [00:00<00:00, 1547.88it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:  31%|███       | 310/1000 [00:00<00:00, 1514.77it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:  32%|███▏      | 320/1000 [00:00<00:00, 1597.56it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:  63%|██████▎   | 629/1000 [00:00<00:00, 1486.70it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1461.05it/s]
Bootstrapping pr_auc:  58%|█████▊    | 582/1000 [00:00<00:00, 1412.36it/s]Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1534.22it/s]
Bootstrapping pr_auc:  48%|████▊     | 479/1000 [00:00<00:00, 1396.23it/s]Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1415.54it/s]
Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1556.42it/s]
Bootstrapping pr_auc:  73%|███████▎  | 731/1000 [00:00<00:00, 1436.45it/s]Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1468.08it/s]
Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1451.67it/s]
Bootstrapping pr_auc:  64%|██████▍   | 639/1000 [00:00<00:00, 1469.08it/s]Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1218.51it/s]
Bootstrapping pr_auc:  89%|████████▉ | 894/1000 [00:00<00:00, 1436.82it/s]Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1371.83it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1504.00it/s]
Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Bootstrapping pr_auc:  76%|███████▌  | 758/1000 [00:00<00:00, 1279.87it/s]Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1412.48it/s]
Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Bootstrapping pr_auc:  68%|██████▊   | 683/1000 [00:00<00:00, 1443.22it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1351.10it/s]
Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1343.91it/s]
Bootstrapping pr_auc:  12%|█▏        | 118/1000 [00:00<00:00, 1172.48it/s]Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Bootstrapping pr_auc:  11%|█▏        | 113/1000 [00:00<00:00, 1123.55it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1404.77it/s]
Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:  86%|████████▌ | 861/1000 [00:00<00:00, 1326.18it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1405.26it/s]
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Bootstrapping pr_auc:  26%|██▋       | 264/1000 [00:00<00:00, 1339.34it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:  13%|█▎        | 133/1000 [00:00<00:00, 1329.86it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1263.28it/s]
Background dataset has 1926 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=1926 when initializing the masker.
Bootstrapping pr_auc:   8%|▊         | 85/1000 [00:00<00:01, 843.34it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:  15%|█▌        | 153/1000 [00:00<00:00, 1525.88it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:  23%|██▎       | 234/1000 [00:00<00:00, 1219.07it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
Bootstrapping pr_auc:  75%|███████▍  | 749/1000 [00:00<00:00, 1554.28it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(

bound,Metrics,estimate,lower,upper,models
0,AUPRC_value,40.4784,17.1303,64.0892,Lasso regression (VL diag + 2 & SMOTE)
1,AUROC_value,93.4022,86.2344,98.1238,Lasso regression (VL diag + 2 & SMOTE)
2,Accuracy,87.6284,80.7931,92.7492,Lasso regression (VL diag + 2 & SMOTE)
3,Accuracy_train,89.6085,86.1371,92.9141,Lasso regression (VL diag + 2 & SMOTE)
4,NPV,99.4458,98.6182,100.0000,Lasso regression (VL diag + 2 & SMOTE)
5,Precision,18.2773,12.3661,26.8013,Lasso regression (VL diag + 2 & SMOTE)
6,Sensitivity,84.1000,60.0000,100.0000,Lasso regression (VL diag + 2 & SMOTE)
7,Specificity,87.7383,80.6698,93.3100,Lasso regression (VL diag + 2 & SMOTE)

# Save model trained

In [ ]:
path = os.getcwd()

state = {
    "lasso_fil_list": lasso_fil_list,
    "lasso_vlsymp_sim_list": lasso_vlsymp_sim_list,
    "lasso_vldiag_list": lasso_vldiag_list,
    "lasso_add1_list": lasso_add1_list,
    "lasso_add2_list": lasso_add2_list
}

save_file = os.path.join(path, "lasso_trained.pkl")

with open(save_file, "wb") as f:
    dill.dump(state, f)

print(f"Saved to: {save_file}")

In [ ]:
path = os.getcwd()

state = {
    "lasso_fil_summary": lasso_fil_summary,
    "lasso_vlsymp_sim_summary": lasso_vlsymp_sim_summary,
    "lasso_vldiag_summary": lasso_vldiag_summary,
    "lasso_add1_summary": lasso_add1_summary,
    "lasso_add2_summary": lasso_add2_summary
}

save_file = os.path.join(path, "lasso_metric_summary.pkl")

with open(save_file, "wb") as f:
    dill.dump(state, f)

print(f"Saved to: {save_file}")