# Import libraries and dataset into environment

In [1]:
import dill
import os
import sys
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
from sklearn.ensemble import RandomForestClassifier
import math as mt
from sklearn.metrics import confusion_matrix, roc_curve, auc
from MLstatkit import Bootstrapping
import json
import gc
import shap
from joblib import Parallel, delayed, externals
import multiprocessing
num_cores = multiprocessing.cpu_count() - 1
import defined_functions
from defined_functions import sum_metric, met_collate_func
defined_functions.pd = pd

In [2]:
path = os.getcwd()
sys.path.append(path)

save_file = os.path.join(path, "session.pkl")

with open(save_file, "rb") as f:
    state = dill.load(f)

split_list_valid_smote = state["split_list_valid_smote"]
split_list_valid_smote_final = state["split_list_valid_smote_final"]
split_list_fil_valid_smote_final = state["split_list_fil_valid_smote_final"]
split_list_sim_onset_valid_smote_final = state["split_list_sim_onset_valid_smote_final"]
split_list_vldiag_valid_smote_final = state["split_list_vldiag_valid_smote_final"]
split_list_diag1_valid_smote_final = state["split_list_diag1_valid_smote_final"]
split_list_diag2_valid_smote_final = state["split_list_diag2_valid_smote_final"]

# Define functions

In [3]:
# Define function to train Random Forest
def run_single_rf_split(i, split):
    """Process a single cross-vaidation data split loop iteration"""
    train_df = split['train'].copy()
    valid_df = split['valid'].copy()
    test_df = split['test'].copy()

    train_df['outcome'] = train_df['outcome'].cat.reorder_categories(["Non severe", "Severe"], ordered = False)
    valid_df['outcome'] = valid_df['outcome'].cat.reorder_categories(["Non severe", "Severe"], ordered = False)
    test_df['outcome'] = test_df['outcome'].cat.reorder_categories(["Non severe", "Severe"], ordered = False)

    train_x = train_df.drop(columns = ['outcome'])
    valid_x = valid_df.drop(columns = ['outcome'])
    test_x = test_df.drop(columns = ['outcome'])

    features = list(train_x.columns)
    cat_cols = ['age', 'gender', 'vaccination', 'comorbidity']
    for col in cat_cols:
        train_x[col] = train_x[col].astype('category')
        valid_x[col] = valid_x[col].astype('category')
        test_x[col] = test_x[col].astype('category')

    train_x = pd.get_dummies(train_x, columns = cat_cols, drop_first = False)
    valid_x = pd.get_dummies(valid_x, columns = cat_cols, drop_first = False)
    test_x = pd.get_dummies(test_x, columns = cat_cols, drop_first = False)

    feature_names = train_x.columns.tolist()

    # Force valid/test to have same columns and same order as train
    valid_x = valid_x.reindex(columns=feature_names, fill_value=0)
    test_x = test_x.reindex(columns=feature_names, fill_value=0)
    
    mapping = {"Non severe": 0, "Severe": 1}
    
    train_y = train_df['outcome'].map(mapping).astype(int)
    valid_y = valid_df['outcome'].map(mapping).astype(int)
    test_y = test_df['outcome'].map(mapping).astype(int)
    
    #pos = np.sum(train_y == 1)
    #neg = np.sum(train_y == 0)
    
    # Train the random forest model
    rf_model = RandomForestClassifier(
        n_estimators = 2500,    # Total number of decision trees to build
        max_depth = None,   # Maximum structural depth of each individual tree
        criterion = 'gini',    # Mathematical metric used to determine split quality
        min_samples_split = 55,   # Minimum number of samples required to split an internal structural node
        max_features = 'sqrt',    # Size of random subset of features ro inspect when looking for the best split
        min_samples_leaf = 25,    # Minimum number of samples required to be at a leaf node
        min_weight_fraction_leaf = 0.0,    # Minimum weighted fracion of the sum total of weights of all the input samples required to be at a leaf node
        max_leaf_nodes = 800,  # Maximum number of leaf nodes
        min_impurity_decrease = 0.0,   # A node will be split if this split induces a decrease of the impurity greater or equal to this value
        bootstrap = True,   # Boostrap sample when building trees
        oob_score = True,   # Whether to use out-of-bag samples to estimate the generalization score
        max_samples = 0.8, # Number of samples to draw from X to train each base estimator
    )
    rf = rf_model.fit(train_x, train_y)

    # Make prediction on Testing Set
    rf_pred_prob = rf.predict_proba(test_x)[:, 1]
    prediction = (rf_pred_prob >= 0.5).astype(int)
    prediction_labels = np.where(prediction == 0, "Non severe", "Severe")

    # Compute Confusion Matrix (Test)
    tn, fp, fn, tp = confusion_matrix(test_y, prediction, labels = [0, 1]).ravel()

    # Calculate Area Under the ROC curve
    fpr, tpr_curve, _ = roc_curve(test_y, rf_pred_prob, pos_label = 1)
    auc_val_rf = auc(fpr, tpr_curve)
    
    # Store standard structure dictionary to act like R's pROC container
    roc_container = {
        'actual': test_y,
        'probabilities': rf_pred_prob
    }
    
    # Calculate Area Under the Precision-Recall Curve (AUPRC / PR-AUC)
    auprc_val, prc_ci_lower, prc_ci_upper = Bootstrapping(test_y, rf_pred_prob, 'pr_auc')
    
    # Format the evaluation matrix lookip dataframe
    cfm_rf = pd.DataFrame(
        [[tn, fp], [fn, tp]],
        index = ["Non severe", "Severe"],
        columns = ["Non severe", "Severe"]
    )
    cfm_rf.index.name = 'Prediction'
    cfm_rf.columns.name = 'Observed'

    # Calculate performance metrics
    accuracy_rf = (tp + tn) / (tn + fp + fn + tp) if (tn + fp + fn + tp) > 0 else 0
    sensitivity_rf = tp / (tp + fn) if (tp + fn) > 0 else 0
    specificity_rf = tn / (tn + fp) if (tn + fp) > 0 else 0
    npv_rf = tn / (tn + fn) if (tn + fn) > 0 else 0
    precision_rf = tp / (tp + fp) if (tp + fp) > 0 else 0

    # Make predictions on Training Set to gather accuracy
    rf_pred_train_prob = rf.predict_proba(train_x)[:, 1]
    rf_pred_train = (rf_pred_train_prob >= 0.5).astype(int)
    tn_tr, fp_tr, fn_tr, tp_tr = confusion_matrix(train_y, rf_pred_train, labels = [0, 1]).ravel()
    accuracy_rf_train = (tp_tr + tn_tr) / (tn_tr + fp_tr + fn_tr + tp_tr)
    
    explainer = shap.TreeExplainer(model = rf)
    shap_values = explainer(train_x).values
    
    return {
        "model": rf,
        "confusion_matrix": cfm_rf,
        "accuracy_training": accuracy_rf_train,
        "accuracy_testing": accuracy_rf,
        "sensitivity": sensitivity_rf,
        "specificity": specificity_rf,
        "precision": precision_rf,
        "npv": npv_rf,
        "roc": roc_container,
        "AUC_value": auc_val_rf,
        "PRC_val": auprc_val,
        "PRC_lower_ci": prc_ci_lower,
        "PRC_upper_ci": prc_ci_upper,
        "SHAP_values": shap_values,
        "prediction": prediction_labels,
        "pred_prob": rf_pred_prob
    }

# Define function to train Random Forest for 100 times in parallel
def model_func_rf_tune(data_list):
    """Main execution wrapper to distribute XGBoost tuning loops over system CPU threads."""
    # Count system resource availability profiles
    num_cores = multiprocessing.cpu_count() - 1
    
    if __name__ == '__main__':
        try:
            result_list = Parallel(n_jobs = num_cores)(
                delayed(run_single_rf_split)(i, data_list[i]) 
                for i in range(100)
                )
        finally:
            externals.loky.get_reusable_executor().shutdown(wait = True)
            gc.collect()

    return result_list

# Fitting dataset into the model

## Fitting data list without VL information

In [4]:
rf_fil_list = model_func_rf_tune(split_list_fil_valid_smote_final)
rf_fil_met_summary = sum_metric(rf_fil_list)
rf_fil_metrics_summary = rf_fil_met_summary["metric_summary"]
rf_fil_summary = met_collate_func(rf_fil_metrics_summary).assign(
    models = "Random Forest (No VL info & SMOTE)"
)
rf_fil_summary

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1381.23it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1454.26it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1508.01it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1425.27it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1459.88it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1387.76it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1544.57it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1296.91it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1459.65it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1481.98it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1375.84it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1491.74it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1493.37it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1325.85it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1196.88it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1410.05it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1486.22it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1531.81it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1325.23it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1346.15it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1482.92it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1473.16it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1375.08it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1259.14it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1385.65it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1507.42it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1393.14it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1248.03it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1500.93it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1488.72it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1538.78it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1562.71it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1556.08it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1455.33it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1474.89it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1464.74it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1595.66it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1560.76it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1401.37it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1408.52it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1529.65it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1503.12it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1453.11it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1494.56it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1533.27it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1530.67it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1374.17it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1389.61it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1474.79it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1334.49it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1518.47it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1532.57it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1627.49it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1588.84it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1523.38it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1466.53it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1612.89it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1547.08it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1193.14it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1553.71it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1382.75it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1491.05it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1622.21it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1482.97it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1486.88it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1357.98it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1571.14it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1278.20it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1466.74it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1484.12it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1546.07it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1378.55it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1413.73it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1499.10it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1526.96it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1334.11it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1567.98it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1494.12it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1500.78it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1526.04it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1333.95it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1478.70it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1443.50it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1545.53it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1418.25it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1472.73it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1517.28it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1202.05it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1471.85it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1510.17it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1589.59it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1531.64it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1506.12it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1469.34it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1572.56it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1528.76it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1535.97it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1591.15it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1482.74it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1589.82it/s]

bound,Metrics,estimate,lower,upper,models
0,AUPRC_value,37.9473,19.9196,61.9078,Random Forest (No VL info & SMOTE)
1,AUROC_value,92.7111,85.6441,97.6429,Random Forest (No VL info & SMOTE)
2,Accuracy,87.6828,79.9018,94.4184,Random Forest (No VL info & SMOTE)
3,Accuracy_train,88.4408,84.5145,92.0145,Random Forest (No VL info & SMOTE)
4,NPV,99.3575,98.6076,100.0000,Random Forest (No VL info & SMOTE)
5,Precision,18.3367,11.7246,31.0714,Random Forest (No VL info & SMOTE)
6,Sensitivity,81.5000,60.0000,100.0000,Random Forest (No VL info & SMOTE)
7,Specificity,87.8754,79.5872,95.0156,Random Forest (No VL info & SMOTE)

## Fitting data list with simulated VL at symptom onset

In [5]:
rf_vlsymp_sim_list = model_func_rf_tune(split_list_sim_onset_valid_smote_final)
rf_vlsymp_sim_met_summary = sum_metric(rf_vlsymp_sim_list)
rf_vlsymp_sim_metrics_summary = rf_vlsymp_sim_met_summary["metric_summary"]
rf_vlsymp_sim_summary = met_collate_func(rf_vlsymp_sim_metrics_summary).assign(
    models = "Random Forest (VL symp simulated & SMOTE)"
)
rf_vlsymp_sim_summary

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1463.73it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1588.12it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1416.71it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1454.92it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1303.73it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1427.81it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1511.36it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1382.35it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1518.03it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1311.86it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1435.54it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1129.94it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1240.10it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1454.97it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1156.92it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1314.62it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1375.94it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1557.56it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1290.88it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1335.78it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1393.39it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1508.56it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1573.31it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1527.09it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1386.68it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1542.03it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1460.51it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1314.21it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1460.37it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1466.77it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1596.97it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1520.35it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1503.31it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1259.80it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1401.08it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1563.38it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1360.63it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1439.47it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1409.64it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1262.19it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1519.56it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1328.34it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1442.38it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1543.17it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1311.92it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1631.18it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1417.59it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1429.44it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1148.89it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1338.30it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1313.82it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1460.28it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1408.06it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1382.54it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1453.48it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1463.27it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1230.12it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1314.36it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1408.11it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1263.24it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1543.28it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1473.50it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1594.28it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1523.15it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1352.62it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1306.99it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1528.04it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1564.72it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1282.33it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1336.28it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1499.57it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1505.95it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1515.67it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1413.88it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1372.57it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1579.55it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1352.38it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1241.99it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1377.05it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1492.96it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1337.30it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1297.32it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1378.78it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1418.93it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1428.39it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1214.78it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1431.58it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1411.60it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1509.80it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1216.55it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1229.60it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1480.59it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1500.79it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1450.54it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1556.08it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1537.11it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1458.78it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1470.85it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1488.23it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1503.62it/s]

bound,Metrics,estimate,lower,upper,models
0,AUPRC_value,37.6844,19.1849,63.6578,Random Forest (VL symp simulated & SMOTE)
1,AUROC_value,92.4702,84.7445,97.4264,Random Forest (VL symp simulated & SMOTE)
2,Accuracy,88.5076,81.5710,93.3535,Random Forest (VL symp simulated & SMOTE)
3,Accuracy_train,89.2586,86.0774,92.6571,Random Forest (VL symp simulated & SMOTE)
4,NPV,99.2790,98.6365,100.0000,Random Forest (VL symp simulated & SMOTE)
5,Precision,18.9007,11.7966,27.9545,Random Forest (VL symp simulated & SMOTE)
6,Sensitivity,79.1000,60.0000,100.0000,Random Forest (VL symp simulated & SMOTE)
7,Specificity,88.8006,80.9969,94.5561,Random Forest (VL symp simulated & SMOTE)

## Fitting data list with VL at diagnosis

In [6]:
rf_vldiag_list = model_func_rf_tune(split_list_vldiag_valid_smote_final)
rf_vldiag_met_summary = sum_metric(rf_vldiag_list)
rf_vldiag_metrics_summary = rf_vldiag_met_summary["metric_summary"]
rf_vldiag_summary = met_collate_func(rf_vldiag_metrics_summary).assign(
    models = "Random Forest (VL diag & SMOTE)"
)
rf_vldiag_summary

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1438.68it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1407.28it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1563.51it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1329.03it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1447.07it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1452.81it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1467.56it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1485.56it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1366.48it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1398.94it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1541.37it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1305.30it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1482.74it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1454.56it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1390.54it/s]
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s] 1373.79it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1448.03it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1491.10it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1443.63it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1338.64it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1340.52it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1353.70it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1457.82it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1178.07it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1310.14it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1423.47it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1329.45it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1297.79it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1220.74it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1270.05it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1573.25it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1425.93it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1410.52it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1376.94it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1539.03it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1562.86it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1355.77it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1445.68it/s]

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1566.39it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1414.76it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1500.29it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1425.41it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1444.65it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1436.71it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1312.47it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1558.05it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1332.00it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1369.74it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1324.50it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1351.31it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1408.95it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1422.46it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1303.86it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1329.30it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1351.60it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1429.82it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1502.74it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1483.15it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1388.18it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1212.89it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1389.59it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1477.80it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1574.23it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1547.95it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1487.11it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1370.07it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1395.95it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1488.25it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1534.23it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1362.04it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1312.12it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1339.88it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1483.59it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1384.16it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1459.01it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1310.68it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1375.15it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1320.45it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1385.99it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1432.95it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1502.59it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1371.51it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1510.14it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1498.27it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1459.65it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1404.24it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1446.95it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1374.68it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1405.01it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1491.48it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1356.81it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1485.69it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1475.03it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1444.41it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1472.45it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1426.81it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1405.44it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1450.16it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1528.16it/s]

bound,Metrics,estimate,lower,upper,models
0,AUPRC_value,42.6382,20.6410,67.2396,Random Forest (VL diag & SMOTE)
1,AUROC_value,93.5528,84.7850,98.1480,Random Forest (VL diag & SMOTE)
2,Accuracy,89.4894,83.0665,93.3535,Random Forest (VL diag & SMOTE)
3,Accuracy_train,89.7160,86.8614,92.9712,Random Forest (VL diag & SMOTE)
4,NPV,99.3577,98.6732,100.0000,Random Forest (VL diag & SMOTE)
5,Precision,20.6041,12.7484,29.1028,Random Forest (VL diag & SMOTE)
6,Sensitivity,81.2000,60.0000,100.0000,Random Forest (VL diag & SMOTE)
7,Specificity,89.7477,82.7025,94.0810,Random Forest (VL diag & SMOTE)

## Fitting data list with VL at diagnosis & VL at 1-day after diagnosis

In [7]:
rf_add1_list = model_func_rf_tune(split_list_diag1_valid_smote_final)
rf_add1_met_summary = sum_metric(rf_add1_list)
rf_add1_metrics_summary = rf_add1_met_summary["metric_summary"]
rf_add1_summary = met_collate_func(rf_add1_metrics_summary).assign(
    models = "Random Forest (VL diag + 1 & SMOTE)"
)
rf_add1_summary

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1558.64it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1295.42it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1558.36it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1469.33it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1573.32it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1439.75it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1492.12it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1339.39it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1458.42it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1524.11it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1482.08it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1457.96it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1191.12it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1434.28it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1198.52it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1463.94it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1551.06it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1357.13it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1254.07it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1452.36it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1591.10it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1505.40it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1427.79it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1508.49it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1514.45it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1510.87it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1418.02it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1475.28it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1451.73it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1264.09it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1445.89it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1366.03it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1491.91it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1365.91it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1441.54it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1500.06it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1551.92it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1554.28it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1489.48it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1471.60it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1475.69it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1543.37it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1431.18it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1461.27it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1322.32it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1490.13it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1421.69it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1488.79it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1487.31it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1547.03it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1487.36it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1487.92it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1548.71it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1385.89it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1465.12it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1479.70it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1442.50it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1320.14it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1537.53it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1537.46it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1413.17it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1454.10it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1476.72it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1588.35it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1575.61it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1573.31it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1470.00it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1484.26it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1477.57it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1536.62it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1506.23it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1418.50it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1433.92it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1391.05it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1526.84it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1550.13it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1235.04it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1433.89it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1269.12it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1353.12it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1315.51it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1498.93it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1500.36it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1507.82it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1296.87it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1362.16it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1497.44it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1518.76it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1428.29it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1192.20it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1502.85it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1574.32it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1448.52it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1487.21it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1435.07it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1565.70it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1556.90it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1535.26it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1489.76it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1500.64it/s]

bound,Metrics,estimate,lower,upper,models
0,AUPRC_value,44.3261,21.3254,69.4472,Random Forest (VL diag + 1 & SMOTE)
1,AUROC_value,93.8879,85.3224,98.5670,Random Forest (VL diag + 1 & SMOTE)
2,Accuracy,89.5257,84.5770,93.2100,Random Forest (VL diag + 1 & SMOTE)
3,Accuracy_train,90.6391,87.8453,93.4631,Random Forest (VL diag + 1 & SMOTE)
4,NPV,99.3473,98.3441,100.0000,Random Forest (VL diag + 1 & SMOTE)
5,Precision,20.4276,14.1961,28.1250,Random Forest (VL diag + 1 & SMOTE)
6,Sensitivity,80.9000,50.0000,100.0000,Random Forest (VL diag + 1 & SMOTE)
7,Specificity,89.7944,84.2601,93.6215,Random Forest (VL diag + 1 & SMOTE)

## Fitting data list with VL at diagnosis & VL 2-days after diagnosis

In [8]:
rf_add2_list = model_func_rf_tune(split_list_diag2_valid_smote_final)
rf_add2_met_summary = sum_metric(rf_add2_list)
rf_add2_metrics_summary = rf_add2_met_summary["metric_summary"]
rf_add2_summary = met_collate_func(rf_add2_metrics_summary).assign(
    models = "Random Forest (VL diag + 2 & SMOTE)"
)
rf_add2_summary

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1549.53it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1455.71it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1394.16it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1415.84it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1474.05it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1443.53it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1509.31it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1482.56it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1409.13it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1383.15it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1230.32it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1462.06it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1383.51it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1344.94it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1207.99it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1340.55it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1389.09it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1453.08it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1498.37it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1353.24it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1297.22it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1308.26it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1502.69it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1428.28it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1254.64it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1513.64it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1387.86it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1492.05it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1349.46it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1440.18it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1471.58it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1412.88it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1394.40it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1492.57it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1449.59it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1286.72it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1518.54it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1310.12it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1265.81it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1479.16it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1411.97it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1412.52it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1553.76it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1566.09it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1550.78it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1552.42it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1439.40it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1295.63it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1375.22it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1549.24it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1372.44it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1314.08it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1293.30it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1177.53it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1390.22it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1390.81it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1370.80it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1411.52it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1449.29it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1268.48it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1522.76it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1407.36it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1384.84it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1487.87it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1526.46it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1599.40it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1421.32it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1405.40it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1383.81it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1432.52it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1337.98it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1508.48it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1563.22it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1519.44it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1410.32it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1563.28it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1439.57it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1431.23it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1385.67it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1422.33it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1414.51it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1387.92it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1463.77it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1451.46it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1546.32it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1575.98it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1453.53it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1425.52it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1452.49it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1522.09it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1531.59it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1488.86it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1622.31it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1525.67it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1549.95it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1551.79it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1602.91it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1532.88it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1579.97it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1569.84it/s]

bound,Metrics,estimate,lower,upper,models
0,AUPRC_value,45.3322,22.2453,67.6982,Random Forest (VL diag + 2 & SMOTE)
1,AUROC_value,94.2847,87.2430,98.4899,Random Forest (VL diag + 2 & SMOTE)
2,Accuracy,89.8248,84.2749,93.3535,Random Forest (VL diag + 2 & SMOTE)
3,Accuracy_train,90.9979,88.2386,93.7967,Random Forest (VL diag + 2 & SMOTE)
4,NPV,99.3557,98.3813,100.0000,Random Forest (VL diag + 2 & SMOTE)
5,Precision,20.9718,13.9916,29.1094,Random Forest (VL diag + 2 & SMOTE)
6,Sensitivity,81.1000,50.0000,100.0000,Random Forest (VL diag + 2 & SMOTE)
7,Specificity,90.0966,83.9486,94.0810,Random Forest (VL diag + 2 & SMOTE)

# Save model trained

In [9]:
path = os.getcwd()

state = {
    "rf_fil_list": rf_fil_list,
    "rf_vlsymp_sim_list": rf_vlsymp_sim_list,
    "rf_vldiag_list": rf_vldiag_list,
    "rf_add1_list": rf_add1_list,
    "rf_add2_list": rf_add2_list
}

save_file = os.path.join(path, "rf_trained.pkl")

with open(save_file, "wb") as f:
    dill.dump(state, f)

#print(f"Saved to: {save_file}")

In [10]:
path = os.getcwd()

state = {
    "rf_fil_summary": rf_fil_summary,
    "rf_vldiag_summary": rf_vldiag_summary,
    "rf_add1_summary": rf_add1_summary,
    "rf_add2_summary": rf_add2_summary,
    "rf_vlsymp_sim_summary": rf_vlsymp_sim_summary
}

save_file = os.path.join(path, "rf_metric_summary.pkl")

with open(save_file, "wb") as f:
    dill.dump(state, f)

#print(f"Saved to: {save_file}")