# Import libraries and dataset into environment

In [1]:
import dill
import os
import sys
import pandas as pd
import numpy as np
import xgboost as xgb
import math as mt
import shap
from sklearn.metrics import confusion_matrix, roc_curve, auc
from MLstatkit import Bootstrapping
import gc
from joblib import Parallel, delayed, externals
import multiprocessing
num_cores = multiprocessing.cpu_count() - 1
import defined_functions
from defined_functions import sum_metric, met_collate_func
defined_functions.pd = pd

In [2]:
path = os.getcwd()
sys.path.append(path)

save_file = os.path.join(path, "session.pkl")

with open(save_file, "rb") as f:
    state = dill.load(f)

split_list_valid_smote = state["split_list_valid_smote"]
split_list_valid_smote_final = state["split_list_valid_smote_final"]
split_list_fil_valid_smote_final = state["split_list_fil_valid_smote_final"]
split_list_sim_onset_valid_smote_final = state["split_list_sim_onset_valid_smote_final"]
split_list_vldiag_valid_smote_final = state["split_list_vldiag_valid_smote_final"]
split_list_diag1_valid_smote_final = state["split_list_diag1_valid_smote_final"]
split_list_diag2_valid_smote_final = state["split_list_diag2_valid_smote_final"]

# Define functions

In [3]:
# Define function to train XGBoost model
def run_single_xgboost_split(i, split):
    """Processes a single cross-validation data split loop iteration."""
    train_df = split['train'].copy()
    valid_df = split['valid'].copy()
    test_df = split['test'].copy()
    
    # Target label mapping ('Non severe' -> 0, 'Severe' -> 1)
    # Assumes categorical strings matching previous blocks
    label_map = {"Non severe": 0, "Severe": 1}
    y_train = train_df['outcome'].map(label_map).values
    y_valid = valid_df['outcome'].map(label_map).values
    y_test = test_df['outcome'].map(label_map).values

    X_train = train_df.drop(columns = ['outcome'])
    X_valid = valid_df.drop(columns = ['outcome'])
    X_test = test_df.drop(columns = ['outcome'])

    cat_cols = ['age', 'gender', 'vaccination', 'comorbidity']
    for col in cat_cols:
        X_train[col] = X_train[col].astype('category')
        X_valid[col] = X_valid[col].astype('category')
        X_test[col] = X_test[col].astype('category')

    dtrain = xgb.DMatrix(X_train, label = y_train, enable_categorical = True)
    dvalid = xgb.DMatrix(X_valid, label = y_valid, enable_categorical = True)
    dtest = xgb.DMatrix(X_test, label = y_test, enable_categorical = True)
    
   # Setting model parameters
    params = {
        'objective': 'binary:logistic',
        'eval_metric': ['aucpr'],
        'learning_rate': 0.003,    # Step size shrinkage used in update to prevents overfitting. (eta)
        'max_depth': 1,    # Maximum depth of a tree.
        'min_child_weight': 2,    # Minimum sum of instance weight (hessian) needed in a child.
        'subsample': 0.6,   # Subsample ratio of the training instances.
        'colsample_bytree': 0.6,    # Subsample ratio of columns when constructing each tree.
        'colsample_bynode': 0.6,    # Subsample ratio of columns when constructing each node.
        'colsample_bylevel': 0.6,    # Subsample ratio of columns when constructing each level.
        'gamma': 0.08, # Minimum loss reduction to make a further partition
        'lambda': 2.5,    # L2 regularization term on weights.
        'alpha': 0.5, # L1 regularization term on weights.
        'max_delta_step': 7,   # Maximum delta step we allow each leaf output to be.
        'scale_pos_weight': 1,  # Control the balance of positive and negative weights
        'tree_method': 'hist',
        'max_leaves': 2,  # Maximum number of nodes to be added
        'max_bin': 255, # Maximum number of discrete bins to bucket continuous features
        'grow_policy': 'depthwise', # Controls a way nodes are added to the tree
        'device': 'cuda',   # Utilizes GPU acceleration; If no GPU in device, please change to 'cpu' to enable model train on CPU.
        'verbosity': 0
    }
    
    # Setup model evaluation validation monitoring
    evals = [(dtrain, 'train'), (dvalid, 'validation')]
    
    # Train the XGBoost model
    xgb_model = xgb.train(
        params = params,
        dtrain = dtrain,
        num_boost_round = 1000,
        evals = evals,
        early_stopping_rounds = 200,
        verbose_eval = 100
    )
    
    # Make predictions on Testing Set
    xgb_pred_prob = xgb_model.predict(dtest)

    # Calculate Area Under the ROC curve
    fpr, tpr_curve, _ = roc_curve(y_test, xgb_pred_prob, pos_label = 1)
    auc_val_xgb = auc(fpr, tpr_curve)
    
    # Store standard structure dictionary to act like R's pROC container
    roc_container = {
        'actual': y_test,
        'probabilities': xgb_pred_prob
    }
    
    # Calculate Area Under the Precision-Recall Curve (AUPRC / PR-AUC)
    auprc_val, prc_ci_lower, prc_ci_upper = Bootstrapping(y_test, xgb_pred_prob, 'pr_auc')

    # Convert predicted probabilities to the labels
    xgb_pred = (xgb_pred_prob >= 0.5).astype(int)
    xgb_pred_res = np.where(xgb_pred == 0, "Non severe", "Severe")
    
    # Compute Confusion Matrix (Test)
    tn, fp, fn, tp = confusion_matrix(y_test, xgb_pred, labels = [0, 1]).ravel()
    
    # Format a formal R-styled evaluation matrix lookup dataframe 
    cfm_xgb = pd.DataFrame(
        [[tn, fp], [fn, tp]], 
        index = ["Non severe", "Severe"], 
        columns = ["Non severe", "Severe"]
    )
    cfm_xgb.index.name = 'Prediction'
    cfm_xgb.columns.name = 'Observed'
    
    # Calculate performance metrics
    accuracy_xgb = (tp + tn) / (tn + fp + fn + tp) if (tn + fp + fn + tp) > 0 else 0
    sensitivity_xgb = tp / (tp + fn) if (tp + fn) > 0 else 0
    specificity_xgb = tn / (tn + fp) if (tn + fp) > 0 else 0
    npv_xgb = tn / (tn + fn) if (tn + fn) > 0 else 0
    precision_xgb = tp / (tp + fp) if (tp + fp) > 0 else 0
    
    # Make predictions on Training Set to gather accuracy
    xgb_pred_train_prob = xgb_model.predict(dtrain)
    xgb_pred_train = (xgb_pred_train_prob >= 0.5).astype(int)
    tn_tr, fp_tr, fn_tr, tp_tr = confusion_matrix(y_train, xgb_pred_train, labels = [0, 1]).ravel()
    accuracy_xgb_train = (tp_tr + tn_tr) / (tn_tr + fp_tr + fn_tr + tp_tr)
     
    explainer = shap.TreeExplainer(model = xgb_model)
    shap_values = explainer(dtrain).values
    
    return {
        "model": xgb_model,
        "confusion_matrix": cfm_xgb,
        "accuracy_training": accuracy_xgb_train,
        "accuracy_testing": accuracy_xgb,
        "sensitivity": sensitivity_xgb,
        "specificity": specificity_xgb,
        "precision": precision_xgb,
        "npv": npv_xgb,
        "roc": roc_container,
        "AUC_value": auc_val_xgb,
        "PRC_val": auprc_val,
        "PRC_lower_ci": prc_ci_lower,
        "PRC_upper_ci": prc_ci_upper,
        "SHAP_values": shap_values,
        "prediction": xgb_pred_res,
        "pred_prob": xgb_pred_prob
    }

# Define function to train XGBoost for 100 times in parallel
def model_func_xgb_tune(data_list):
    """Main execution wrapper to distribute XGBoost tuning loops over system CPU threads."""
    # Count system resource availability profiles
    num_cores = multiprocessing.cpu_count() - 1
    
    if __name__ == '__main__':
        try:
            result_list = Parallel(n_jobs = num_cores)(
                delayed(run_single_xgboost_split)(i, data_list[i]) 
                for i in range(100)
                )
        finally:
            externals.loky.get_reusable_executor().shutdown(wait = True)
            gc.collect()

    return result_list

# Fitting dataset into the model

## Fitting data list without VL information

In [4]:
xgb_fil_list = model_func_xgb_tune(split_list_fil_valid_smote_final)
xgb_fil_met_summary = sum_metric(xgb_fil_list)
xgb_fil_metrics_summary = xgb_fil_met_summary["metric_summary"]
xgb_fil_summary = met_collate_func(xgb_fil_metrics_summary).assign(
    models = "XGBoost (No VL info & SMOTE)"
)
xgb_fil_summary

/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:17] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:17] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:17] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:17] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:17] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:17] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:17] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:17] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:17] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:17] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:17] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:17] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:17] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:17] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:17] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:17] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:17] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:17] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:17] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:17] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:18] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:18] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:18] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:18] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:18] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:18] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
Bootstrapping pr_auc:  16%|█▌        | 161/1000 [00:00<00:00, 1605.26it/s]

[0]	train-aucpr:0.54305	validation-aucpr:0.04013[0]	train-aucpr:0.51998	validation-aucpr:0.03169[0]	train-aucpr:0.52290	validation-aucpr:0.03592


[0]	train-aucpr:0.51440	validation-aucpr:0.03697
[0]	train-aucpr:0.54171	validation-aucpr:0.03141
[100]	train-aucpr:0.89278	validation-aucpr:0.29217
[100]	train-aucpr:0.93296	validation-aucpr:0.26603
[100]	train-aucpr:0.91587	validation-aucpr:0.18920
[100]	train-aucpr:0.93666	validation-aucpr:0.20598
[0]	train-aucpr:0.52476	validation-aucpr:0.03936
[100]	train-aucpr:0.91765	validation-aucpr:0.24318
[200]	train-aucpr:0.89278	validation-aucpr:0.29217
[200]	train-aucpr:0.93194	validation-aucpr:0.26766
[0]	train-aucpr:0.56957	validation-aucpr:0.02647
[200]	train-aucpr:0.91367	validation-aucpr:0.16805
[205]	train-aucpr:0.91367	validation-aucpr:0.16805
[220]	train-aucpr:0.89278	validation-aucpr:0.29217
[222]	train-aucpr:0.93201	validation-aucpr:0.26766
[0]	train-aucpr:0.56935	validation-aucpr:0.04865
[100]	train-aucpr:0.90003	validation-aucpr:0.40607
[200]	train-aucpr:0.93666	validation-aucpr:0.20598
[0]	train-aucpr:0.54920	validation-aucpr:0.02984
[0]	train-aucpr:0.55870	validation-aucpr:0.04176
[200]	train-aucpr:0.91701	validation-aucpr:0.24959
[203]	train-aucpr:0.91701	validation-aucpr:0.24959
[100]	train-aucpr:0.93948	validation-aucpr:0.22771
[283]	train-aucpr:0.93544	validation-aucpr:0.20598
[0]	train-aucpr:0.53639	validation-aucpr:0.03127
[100]	train-aucpr:0.89803	validation-aucpr:0.24866
[100]	train-aucpr:0.91250	validation-aucpr:0.28349
[100]	train-aucpr:0.91127	validation-aucpr:0.35193
[200]	train-aucpr:0.90268	validation-aucpr:0.41189
[200]	train-aucpr:0.93824	validation-aucpr:0.23214
[206]	train-aucpr:0.93824	validation-aucpr:0.23214
[200]	train-aucpr:0.89803	validation-aucpr:0.24866
[100]	train-aucpr:0.92705	validation-aucpr:0.19723
[200]	train-aucpr:0.91250	validation-aucpr:0.28349
[220]	train-aucpr:0.89803	validation-aucpr:0.24866
[200]	train-aucpr:0.91127	validation-aucpr:0.35193
[221]	train-aucpr:0.91127	validation-aucpr:0.35193
[240]	train-aucpr:0.91250	validation-aucpr:0.28349
[0]	train-aucpr:0.54628	validation-aucpr:0.03734
[300]	train-aucpr:0.90228	validation-aucpr:0.41706
[200]	train-aucpr:0.92508	validation-aucpr:0.19746
[218]	train-aucpr:0.92508	validation-aucpr:0.19746
[100]	train-aucpr:0.93436	validation-aucpr:0.27923
[400]	train-aucpr:0.91536	validation-aucpr:0.46441
[0]	train-aucpr:0.57115	validation-aucpr:0.02235
[200]	train-aucpr:0.93384	validation-aucpr:0.27863
[216]	train-aucpr:0.93384	validation-aucpr:0.27863
[100]	train-aucpr:0.90473	validation-aucpr:0.15363

Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:18] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:18] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
Bootstrapping pr_auc:  16%|█▋        | 165/1000 [00:00<00:00, 1646.84it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:18] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:18] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
Bootstrapping pr_auc:  46%|████▌     | 461/1000 [00:00<00:00, 1568.37it/s]

[500]	train-aucpr:0.92125	validation-aucpr:0.46352
[553]	train-aucpr:0.92137	validation-aucpr:0.44218
[200]	train-aucpr:0.90569	validation-aucpr:0.15497
[206]	train-aucpr:0.90569	validation-aucpr:0.15497
[0]	train-aucpr:0.57580	validation-aucpr:0.03009
[0]	train-aucpr:0.57182	validation-aucpr:0.03021
[100]	train-aucpr:0.92062	validation-aucpr:0.38131
[100]	train-aucpr:0.92213	validation-aucpr:0.19746
[200]	train-aucpr:0.92211	validation-aucpr:0.39427
[263]	train-aucpr:0.92062	validation-aucpr:0.38131
[200]	train-aucpr:0.92146	validation-aucpr:0.19904
[283]	train-aucpr:0.92146	validation-aucpr:0.19904

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1613.49it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1503.93it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1526.24it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1543.59it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1359.67it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1515.13it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1403.16it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1285.68it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1173.46it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1448.10it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1296.53it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1279.60it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1301.66it/s]
Bootstrapping pr_auc:  94%|█████████▎| 935/1000 [00:00<00:00, 1265.23it/s]

[0]	train-aucpr:0.58121	validation-aucpr:0.03047
[100]	train-aucpr:0.92142	validation-aucpr:0.39564
[0]	train-aucpr:0.57678	validation-aucpr:0.02647
[200]	train-aucpr:0.91933	validation-aucpr:0.37797
[0]	train-aucpr:0.56698	validation-aucpr:0.02688
[0]	train-aucpr:0.52542	validation-aucpr:0.03141
[300]	train-aucpr:0.91933	validation-aucpr:0.37797
[100]	train-aucpr:0.91261	validation-aucpr:0.22268
[100]	train-aucpr:0.91830	validation-aucpr:0.28791
[318]	train-aucpr:0.91933	validation-aucpr:0.37797
[100]	train-aucpr:0.92590	validation-aucpr:0.17389
[200]	train-aucpr:0.91245	validation-aucpr:0.29168
[200]	train-aucpr:0.92590	validation-aucpr:0.17389
[200]	train-aucpr:0.91261	validation-aucpr:0.22268
[211]	train-aucpr:0.92590	validation-aucpr:0.17389
[0]	train-aucpr:0.54291	validation-aucpr:0.03477
[0]	train-aucpr:0.53003	validation-aucpr:0.02540
[300]	train-aucpr:0.91245	validation-aucpr:0.29168
[319]	train-aucpr:0.91245	validation-aucpr:0.29168

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1359.56it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1329.96it/s]
Bootstrapping pr_auc:  21%|██        | 210/1000 [00:00<00:00, 1047.80it/s]

[267]	train-aucpr:0.91261	validation-aucpr:0.22268
[100]	train-aucpr:0.92569	validation-aucpr:0.16942
[200]	train-aucpr:0.92602	validation-aucpr:0.16647
[0]	train-aucpr:0.53873	validation-aucpr:0.03526
[100]	train-aucpr:0.88778	validation-aucpr:0.51228
[295]	train-aucpr:0.92435	validation-aucpr:0.16647[100]	train-aucpr:0.91624	validation-aucpr:0.34176[200]	train-aucpr:0.88695	validation-aucpr:0.51228

[0]	train-aucpr:0.54859	validation-aucpr:0.03198
[0]	train-aucpr:0.54972	validation-aucpr:0.02568
[229]	train-aucpr:0.88695	validation-aucpr:0.51228

[0]	train-aucpr:0.57174	validation-aucpr:0.02365
[100]	train-aucpr:0.87582	validation-aucpr:0.27926
[100]	train-aucpr:0.92250	validation-aucpr:0.24052
[0]	train-aucpr:0.57798	validation-aucpr:0.02947
[200]	train-aucpr:0.92545	validation-aucpr:0.32656
[205]	train-aucpr:0.92545	validation-aucpr:0.32656
[100]	train-aucpr:0.88531	validation-aucpr:0.23740
[200]	train-aucpr:0.87220	validation-aucpr:0.28035
[0]	train-aucpr:0.57338	validation-aucpr:0.02444
[200]	train-aucpr:0.92071	validation-aucpr:0.24052
[203]	train-aucpr:0.92250	validation-aucpr:0.24052
[100]	train-aucpr:0.91129	validation-aucpr:0.19215
[200]	train-aucpr:0.88504	validation-aucpr:0.19413
[300]	train-aucpr:0.87220	validation-aucpr:0.28035
[223]	train-aucpr:0.88450	validation-aucpr:0.23740
[320]	train-aucpr:0.87220	validation-aucpr:0.28035
[200]	train-aucpr:0.91463	validation-aucpr:0.19292

Bootstrapping pr_auc:  52%|█████▏    | 517/1000 [00:00<00:00, 1236.27it/s]

[0]	train-aucpr:0.52272	validation-aucpr:0.02578
[205]	train-aucpr:0.91463	validation-aucpr:0.19292
[100]	train-aucpr:0.93605	validation-aucpr:0.21544
[100]	train-aucpr:0.91477	validation-aucpr:0.36153
[200]	train-aucpr:0.93446	validation-aucpr:0.20371
[290]	train-aucpr:0.93356	validation-aucpr:0.20371
[200]	train-aucpr:0.91199	validation-aucpr:0.35926
[205]	train-aucpr:0.91199	validation-aucpr:0.35926
[0]	train-aucpr:0.54154	validation-aucpr:0.02607
[100]	train-aucpr:0.92072	validation-aucpr:0.16458
[0]	train-aucpr:0.52366	validation-aucpr:0.02688
[200]	train-aucpr:0.92072	validation-aucpr:0.16458
[225]	train-aucpr:0.92072	validation-aucpr:0.16458
[100]	train-aucpr:0.90973	validation-aucpr:0.22195
[200]	train-aucpr:0.90817	validation-aucpr:0.21879
[206]	train-aucpr:0.90817	validation-aucpr:0.21879

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1356.84it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1449.23it/s]
Bootstrapping pr_auc:  96%|█████████▌| 959/1000 [00:00<00:00, 1235.55it/s]

[0]	train-aucpr:0.52943	validation-aucpr:0.04093
[100]	train-aucpr:0.87512	validation-aucpr:0.46072
[0]	train-aucpr:0.55288	validation-aucpr:0.03034
[200]	train-aucpr:0.87480	validation-aucpr:0.46368
[216]	train-aucpr:0.88000	validation-aucpr:0.46377
[100]	train-aucpr:0.90125	validation-aucpr:0.42872
[0]	train-aucpr:0.53932	validation-aucpr:0.04134
[200]	train-aucpr:0.90011	validation-aucpr:0.42763
[100]	train-aucpr:0.91782	validation-aucpr:0.30336
[295]	train-aucpr:0.89930	validation-aucpr:0.42763
[200]	train-aucpr:0.91782	validation-aucpr:0.30336[0]	train-aucpr:0.59043	validation-aucpr:0.02677
[218]	train-aucpr:0.91782	validation-aucpr:0.30336

[100]	train-aucpr:0.93397	validation-aucpr:0.45351
[0]	train-aucpr:0.58291	validation-aucpr:0.03169

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1467.25it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1216.75it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1093.60it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1591.12it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1410.82it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1484.61it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1460.52it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1536.90it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1325.34it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1190.33it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1470.67it/s]
Bootstrapping pr_auc:  14%|█▎        | 136/1000 [00:00<00:00, 1356.06it/s]

[0]	train-aucpr:0.54723	validation-aucpr:0.02647
[200]	train-aucpr:0.93087	validation-aucpr:0.44172
[100]	train-aucpr:0.91892	validation-aucpr:0.26282
[222]	train-aucpr:0.93230	validation-aucpr:0.45365
[100]	train-aucpr:0.91983	validation-aucpr:0.14692
[0]	train-aucpr:0.51524	validation-aucpr:0.03370
[200]	train-aucpr:0.91892	validation-aucpr:0.26282
[204]	train-aucpr:0.91892	validation-aucpr:0.26282
[200]	train-aucpr:0.91855	validation-aucpr:0.14612
[0]	train-aucpr:0.56558	validation-aucpr:0.03155
[100]	train-aucpr:0.93553	validation-aucpr:0.29406[300]	train-aucpr:0.91825	validation-aucpr:0.14663

[0]	train-aucpr:0.56447	validation-aucpr:0.02959
[100]	train-aucpr:0.90815	validation-aucpr:0.24070
[0]	train-aucpr:0.57372	validation-aucpr:0.02325
[400]	train-aucpr:0.91825	validation-aucpr:0.14663
[200]	train-aucpr:0.93557	validation-aucpr:0.29254
[100]	train-aucpr:0.87581	validation-aucpr:0.45176
[206]	train-aucpr:0.93556	validation-aucpr:0.29254
[100]	train-aucpr:0.93249	validation-aucpr:0.27992
[500]	train-aucpr:0.92748	validation-aucpr:0.15088
[0]	train-aucpr:0.52454	validation-aucpr:0.03155
[200]	train-aucpr:0.90619	validation-aucpr:0.24622
[200]	train-aucpr:0.93323	validation-aucpr:0.20350
[207]	train-aucpr:0.93232	validation-aucpr:0.28061
[600]	train-aucpr:0.92826	validation-aucpr:0.15021
[300]	train-aucpr:0.90619	validation-aucpr:0.24622
[316]	train-aucpr:0.90619	validation-aucpr:0.24622
[667]	train-aucpr:0.92831	validation-aucpr:0.15021
[100]	train-aucpr:0.89162	validation-aucpr:0.39990

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1498.44it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1469.40it/s]
Bootstrapping pr_auc:  16%|█▋        | 163/1000 [00:00<00:00, 1620.60it/s]

[200]	train-aucpr:0.87643	validation-aucpr:0.45315
[0]	train-aucpr:0.56141	validation-aucpr:0.03009
[223]	train-aucpr:0.87581	validation-aucpr:0.45176
[200]	train-aucpr:0.89260	validation-aucpr:0.38199
[216]	train-aucpr:0.89260	validation-aucpr:0.38199
[100]	train-aucpr:0.90587	validation-aucpr:0.28665
[0]	train-aucpr:0.55093	validation-aucpr:0.02731
[200]	train-aucpr:0.90460	validation-aucpr:0.28771
[263]	train-aucpr:0.90365	validation-aucpr:0.28771
[100]	train-aucpr:0.91330	validation-aucpr:0.21957
[0]	train-aucpr:0.53050	validation-aucpr:0.03575
[200]	train-aucpr:0.91330	validation-aucpr:0.21957
[218]	train-aucpr:0.91330	validation-aucpr:0.21957
[100]	train-aucpr:0.90972	validation-aucpr:0.25093
[0]	train-aucpr:0.52690	validation-aucpr:0.02753
[200]	train-aucpr:0.90972	validation-aucpr:0.25093
[218]	train-aucpr:0.90972	validation-aucpr:0.25093
[100]	train-aucpr:0.90963	validation-aucpr:0.33607
[200]	train-aucpr:0.90819	validation-aucpr:0.33013

Bootstrapping pr_auc:  64%|██████▍   | 643/1000 [00:00<00:00, 1552.96it/s]

[230]	train-aucpr:0.90819	validation-aucpr:0.33013

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1303.75it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1351.80it/s]

[0]	train-aucpr:0.51070	validation-aucpr:0.04176
[100]	train-aucpr:0.87710	validation-aucpr:0.43918
[0]	train-aucpr:0.52618	validation-aucpr:0.04113
[200]	train-aucpr:0.87710	validation-aucpr:0.43918
[210]	train-aucpr:0.87710	validation-aucpr:0.43918
[100]	train-aucpr:0.90567	validation-aucpr:0.32453
[0]	train-aucpr:0.55687	validation-aucpr:0.03202
[200]	train-aucpr:0.90298	validation-aucpr:0.32453
[0]	train-aucpr:0.51307	validation-aucpr:0.03385
[215]	train-aucpr:0.90298	validation-aucpr:0.32453
[100]	train-aucpr:0.91194	validation-aucpr:0.11056
[100]	train-aucpr:0.89464	validation-aucpr:0.57525
[0]	train-aucpr:0.54214	validation-aucpr:0.02742

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1542.14it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1308.22it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1418.18it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1584.23it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1422.13it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1568.45it/s]
Bootstrapping pr_auc:  91%|█████████ | 909/1000 [00:00<00:00, 1364.75it/s]

[100]	train-aucpr:0.92259	validation-aucpr:0.35177
[0]	train-aucpr:0.52333	validation-aucpr:0.01720
[200]	train-aucpr:0.89093	validation-aucpr:0.58146
[220]	train-aucpr:0.89464	validation-aucpr:0.57525
[200]	train-aucpr:0.91194	validation-aucpr:0.11056
[203]	train-aucpr:0.91194	validation-aucpr:0.11056
[100]	train-aucpr:0.87451	validation-aucpr:0.21314
[200]	train-aucpr:0.92117	validation-aucpr:0.33973
[225]	train-aucpr:0.92117	validation-aucpr:0.33973
[0]	train-aucpr:0.56197	validation-aucpr:0.03477
[200]	train-aucpr:0.87191	validation-aucpr:0.21332
[230]	train-aucpr:0.87191	validation-aucpr:0.21332
[100]	train-aucpr:0.90194	validation-aucpr:0.36616
[0]	train-aucpr:0.54499	validation-aucpr:0.03242
[200]	train-aucpr:0.89991	validation-aucpr:0.36888
[220]	train-aucpr:0.90194	validation-aucpr:0.36616
[100]	train-aucpr:0.89723	validation-aucpr:0.34403
[0]	train-aucpr:0.51480	validation-aucpr:0.03446

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1352.06it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1345.58it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1408.66it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1454.02it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1217.32it/s]
Bootstrapping pr_auc:  12%|█▎        | 125/1000 [00:00<00:00, 1244.30it/s]

[200]	train-aucpr:0.89686	validation-aucpr:0.34388
[218]	train-aucpr:0.89686	validation-aucpr:0.34388
[100]	train-aucpr:0.90935	validation-aucpr:0.26347
[0]	train-aucpr:0.53709	validation-aucpr:0.02657
[0]	train-aucpr:0.59897	validation-aucpr:0.02779
[200]	train-aucpr:0.90777	validation-aucpr:0.26472
[241]	train-aucpr:0.90777	validation-aucpr:0.26472
[100]	train-aucpr:0.90724	validation-aucpr:0.18348
[0]	train-aucpr:0.56836	validation-aucpr:0.02657
[200]	train-aucpr:0.90554	validation-aucpr:0.17237
[205]	train-aucpr:0.90660	validation-aucpr:0.18255
[100]	train-aucpr:0.92194	validation-aucpr:0.24753
[100]	train-aucpr:0.93105	validation-aucpr:0.11420
[0]	train-aucpr:0.56487	validation-aucpr:0.03644
[200]	train-aucpr:0.93105	validation-aucpr:0.11420[200]	train-aucpr:0.92089	validation-aucpr:0.24753

[100]	train-aucpr:0.94877	validation-aucpr:0.22602
[0]	train-aucpr:0.52663	validation-aucpr:0.04497
[221]	train-aucpr:0.93105	validation-aucpr:0.11420
[0]	train-aucpr:0.55743	validation-aucpr:0.03936
[284]	train-aucpr:0.92089	validation-aucpr:0.24753
[100]	train-aucpr:0.90169	validation-aucpr:0.30298

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1330.79it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1348.28it/s]
Bootstrapping pr_auc:  17%|█▋        | 168/1000 [00:00<00:00, 1675.03it/s]

[200]	train-aucpr:0.94877	validation-aucpr:0.22602
[220]	train-aucpr:0.94877	validation-aucpr:0.22602
[200]	train-aucpr:0.90755	validation-aucpr:0.28556
[100]	train-aucpr:0.89951	validation-aucpr:0.76571
[300]	train-aucpr:0.91871	validation-aucpr:0.36918
[200]	train-aucpr:0.89931	validation-aucpr:0.76571
[216]	train-aucpr:0.89931	validation-aucpr:0.76571
[400]	train-aucpr:0.92225	validation-aucpr:0.36839
[422]	train-aucpr:0.92094	validation-aucpr:0.36843

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1237.18it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1403.39it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1160.11it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1300.34it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1360.61it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1268.34it/s]
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

[0]	train-aucpr:0.50635	validation-aucpr:0.04093
[100]	train-aucpr:0.86522	validation-aucpr:0.44264
[0]	train-aucpr:0.56007	validation-aucpr:0.03009
[200]	train-aucpr:0.86440	validation-aucpr:0.44465
[100]	train-aucpr:0.92346	validation-aucpr:0.25581
[300]	train-aucpr:0.86080	validation-aucpr:0.44544
[352]	train-aucpr:0.86080	validation-aucpr:0.44544
[200]	train-aucpr:0.92346	validation-aucpr:0.25581
[220]	train-aucpr:0.92346	validation-aucpr:0.25581
[0]	train-aucpr:0.58304	validation-aucpr:0.04197
[100]	train-aucpr:0.92368	validation-aucpr:0.41656
[0]	train-aucpr:0.59480	validation-aucpr:0.02374

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1332.77it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1376.06it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1353.61it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1357.18it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1523.62it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1432.68it/s]
Bootstrapping pr_auc:  14%|█▍        | 145/1000 [00:00<00:00, 1440.28it/s]

[200]	train-aucpr:0.92173	validation-aucpr:0.42096
[100]	train-aucpr:0.90440	validation-aucpr:0.20908
[200]	train-aucpr:0.90440	validation-aucpr:0.20908
[204]	train-aucpr:0.90345	validation-aucpr:0.21677
[0]	train-aucpr:0.53938	validation-aucpr:0.03073
[300]	train-aucpr:0.92086	validation-aucpr:0.42096
[100]	train-aucpr:0.94422	validation-aucpr:0.22531
[361]	train-aucpr:0.92086	validation-aucpr:0.42096
[200]	train-aucpr:0.94331	validation-aucpr:0.22369
[0]	train-aucpr:0.57981	validation-aucpr:0.02513
[300]	train-aucpr:0.94391	validation-aucpr:0.22582
[0]	train-aucpr:0.57956	validation-aucpr:0.02616
[323]	train-aucpr:0.94391	validation-aucpr:0.22582
[100]	train-aucpr:0.93938	validation-aucpr:0.12759
[0]	train-aucpr:0.52676	validation-aucpr:0.02310

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1512.62it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1307.47it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1384.18it/s]
Bootstrapping pr_auc:  46%|████▌     | 456/1000 [00:00<00:00, 1407.65it/s]

[200]	train-aucpr:0.93868	validation-aucpr:0.10562
[100]	train-aucpr:0.94239	validation-aucpr:0.10617
[0]	train-aucpr:0.55642	validation-aucpr:0.03542
[221]	train-aucpr:0.93868	validation-aucpr:0.10562
[100]	train-aucpr:0.93832	validation-aucpr:0.13284
[0]	train-aucpr:0.53434	validation-aucpr:0.03662
[200]	train-aucpr:0.93835	validation-aucpr:0.13284
[200]	train-aucpr:0.93724	validation-aucpr:0.10402
[204]	train-aucpr:0.93724	validation-aucpr:0.10402
[100]	train-aucpr:0.90747	validation-aucpr:0.38632
[0]	train-aucpr:0.54542	validation-aucpr:0.03918
[100]	train-aucpr:0.91226	validation-aucpr:0.21040
[296]	train-aucpr:0.93836	validation-aucpr:0.13284
[100]	train-aucpr:0.91875	validation-aucpr:0.21455
[200]	train-aucpr:0.90591	validation-aucpr:0.38632
[221]	train-aucpr:0.90747	validation-aucpr:0.38632
[0]	train-aucpr:0.52599	validation-aucpr:0.04033
[200]	train-aucpr:0.91193	validation-aucpr:0.20886
[0]	train-aucpr:0.52378	validation-aucpr:0.03430
[210]	train-aucpr:0.91193	validation-aucpr:0.20886
[200]	train-aucpr:0.91734	validation-aucpr:0.21550
[209]	train-aucpr:0.91734	validation-aucpr:0.21550
[100]	train-aucpr:0.90687	validation-aucpr:0.24218
[100]	train-aucpr:0.87868	validation-aucpr:0.31656
[0]	train-aucpr:0.53155	validation-aucpr:0.03609

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1583.90it/s]
Bootstrapping pr_auc:  33%|███▎      | 326/1000 [00:00<00:00, 1460.73it/s]

[200]	train-aucpr:0.90465	validation-aucpr:0.24833
[216]	train-aucpr:0.90465	validation-aucpr:0.24833
[200]	train-aucpr:0.87868	validation-aucpr:0.31656
[203]	train-aucpr:0.87868	validation-aucpr:0.31656
[100]	train-aucpr:0.93672	validation-aucpr:0.28416
[200]	train-aucpr:0.93352	validation-aucpr:0.28416
[216]	train-aucpr:0.93672	validation-aucpr:0.28416
[0]	train-aucpr:0.51733	validation-aucpr:0.03326
[100]	train-aucpr:0.90299	validation-aucpr:0.15414
[200]	train-aucpr:0.90299	validation-aucpr:0.15414
[206]	train-aucpr:0.90299	validation-aucpr:0.15414
[0]	train-aucpr:0.57055	validation-aucpr:0.03326

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1333.45it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1456.12it/s]
Bootstrapping pr_auc:  64%|██████▎   | 637/1000 [00:00<00:00, 1518.04it/s]

[100]	train-aucpr:0.92399	validation-aucpr:0.33521
[200]	train-aucpr:0.92479	validation-aucpr:0.32858
[216]	train-aucpr:0.92479	validation-aucpr:0.32858
[0]	train-aucpr:0.57372	validation-aucpr:0.02971
[100]	train-aucpr:0.91279	validation-aucpr:0.33362
[200]	train-aucpr:0.91279	validation-aucpr:0.33362
[206]	train-aucpr:0.91279	validation-aucpr:0.33362
[0]	train-aucpr:0.53572	validation-aucpr:0.02408

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1300.44it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1383.97it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1351.45it/s]
Bootstrapping pr_auc:  82%|████████▏ | 821/1000 [00:00<00:00, 1350.29it/s]

[100]	train-aucpr:0.91105	validation-aucpr:0.24956
[200]	train-aucpr:0.91129	validation-aucpr:0.24919
[223]	train-aucpr:0.91129	validation-aucpr:0.24919
[0]	train-aucpr:0.53202	validation-aucpr:0.02657
[100]	train-aucpr:0.91199	validation-aucpr:0.27968
[0]	train-aucpr:0.50232	validation-aucpr:0.02374
[200]	train-aucpr:0.91222	validation-aucpr:0.26112
[215]	train-aucpr:0.91222	validation-aucpr:0.26112
[100]	train-aucpr:0.88198	validation-aucpr:0.22865
[0]	train-aucpr:0.56007	validation-aucpr:0.03697

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1344.97it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1383.31it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1268.57it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1418.50it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1514.74it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1274.16it/s]
Bootstrapping pr_auc:  28%|██▊       | 281/1000 [00:00<00:00, 1424.43it/s]

[200]	train-aucpr:0.88198	validation-aucpr:0.22865
[216]	train-aucpr:0.88198	validation-aucpr:0.22865
[100]	train-aucpr:0.93748	validation-aucpr:0.17359
[0]	train-aucpr:0.50203	validation-aucpr:0.03592
[100]	train-aucpr:0.89806	validation-aucpr:0.16525
[200]	train-aucpr:0.93748	validation-aucpr:0.17359
[203]	train-aucpr:0.93748	validation-aucpr:0.17359
[200]	train-aucpr:0.89806	validation-aucpr:0.16525
[203]	train-aucpr:0.89806	validation-aucpr:0.16525
[0]	train-aucpr:0.55389	validation-aucpr:0.04033
[0]	train-aucpr:0.54331	validation-aucpr:0.03326
[0]	train-aucpr:0.54805	validation-aucpr:0.02626
[100]	train-aucpr:0.92311	validation-aucpr:0.40885
[100]	train-aucpr:0.91963	validation-aucpr:0.19512
[200]	train-aucpr:0.92084	validation-aucpr:0.40922
[100]	train-aucpr:0.92745	validation-aucpr:0.16674
[0]	train-aucpr:0.53631	validation-aucpr:0.02587

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1208.12it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1214.29it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1381.64it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1552.42it/s]
Bootstrapping pr_auc:  37%|███▋      | 374/1000 [00:00<00:00, 1123.71it/s]

[200]	train-aucpr:0.91934	validation-aucpr:0.17675
[215]	train-aucpr:0.91952	validation-aucpr:0.18561
[0]	train-aucpr:0.57356	validation-aucpr:0.03141
[300]	train-aucpr:0.92084	validation-aucpr:0.40922
[100]	train-aucpr:0.88847	validation-aucpr:0.16491
[200]	train-aucpr:0.92746	validation-aucpr:0.16674
[320]	train-aucpr:0.92084	validation-aucpr:0.40922
[252]	train-aucpr:0.92750	validation-aucpr:0.16674
[0]	train-aucpr:0.51733	validation-aucpr:0.03400
[200]	train-aucpr:0.88092	validation-aucpr:0.16722
[221]	train-aucpr:0.88574	validation-aucpr:0.16722
[100]	train-aucpr:0.91306	validation-aucpr:0.33634
[0]	train-aucpr:0.58713	validation-aucpr:0.03169
[100]	train-aucpr:0.90656	validation-aucpr:0.35648
[200]	train-aucpr:0.91306	validation-aucpr:0.33634
[100]	train-aucpr:0.94415	validation-aucpr:0.14228
[231]	train-aucpr:0.91306	validation-aucpr:0.33634
[0]	train-aucpr:0.54071	validation-aucpr:0.03526
[200]	train-aucpr:0.91952	validation-aucpr:0.43328
[200]	train-aucpr:0.94415	validation-aucpr:0.14228
[229]	train-aucpr:0.94415	validation-aucpr:0.14228
[100]	train-aucpr:0.89730	validation-aucpr:0.32548
[300]	train-aucpr:0.92011	validation-aucpr:0.43439
[200]	train-aucpr:0.89694	validation-aucpr:0.32338
[341]	train-aucpr:0.92011	validation-aucpr:0.43439
[203]	train-aucpr:0.89710	validation-aucpr:0.32496

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1406.80it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1365.35it/s]
Bootstrapping pr_auc:  34%|███▍      | 343/1000 [00:00<00:00, 989.10it/s]

[0]	train-aucpr:0.55999	validation-aucpr:0.02947
[100]	train-aucpr:0.89439	validation-aucpr:0.25463
[0]	train-aucpr:0.59373	validation-aucpr:0.04033
[200]	train-aucpr:0.89365	validation-aucpr:0.25668
[263]	train-aucpr:0.89365	validation-aucpr:0.25668
[100]	train-aucpr:0.91846	validation-aucpr:0.43760
[200]	train-aucpr:0.91846	validation-aucpr:0.43760
[222]	train-aucpr:0.91846	validation-aucpr:0.43760
[0]	train-aucpr:0.52823	validation-aucpr:0.03461
[100]	train-aucpr:0.86820	validation-aucpr:0.31282

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1355.22it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1224.06it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1447.53it/s]
Bootstrapping pr_auc:  88%|████████▊ | 885/1000 [00:00<00:00, 1195.40it/s]

[200]	train-aucpr:0.86820	validation-aucpr:0.31282
[218]	train-aucpr:0.86820	validation-aucpr:0.31282
[0]	train-aucpr:0.55591	validation-aucpr:0.03155
[100]	train-aucpr:0.94259	validation-aucpr:0.19123
[200]	train-aucpr:0.94283	validation-aucpr:0.18608
[203]	train-aucpr:0.94282	validation-aucpr:0.18608
[0]	train-aucpr:0.57430	validation-aucpr:0.02667

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1150.96it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1336.86it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1349.78it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1351.23it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1298.95it/s]

[0]	train-aucpr:0.54650	validation-aucpr:0.03183
[100]	train-aucpr:0.89924	validation-aucpr:0.29527
[100]	train-aucpr:0.89237	validation-aucpr:0.36024
[0]	train-aucpr:0.55065	validation-aucpr:0.03644
[200]	train-aucpr:0.89202	validation-aucpr:0.36024
[100]	train-aucpr:0.94531	validation-aucpr:0.28793
[200]	train-aucpr:0.89225	validation-aucpr:0.30980
[300]	train-aucpr:0.88913	validation-aucpr:0.36040
[0]	train-aucpr:0.57260	validation-aucpr:0.03198
[200]	train-aucpr:0.94531	validation-aucpr:0.28793
[367]	train-aucpr:0.88913	validation-aucpr:0.36040
[300]	train-aucpr:0.89532	validation-aucpr:0.29608
[218]	train-aucpr:0.94531	validation-aucpr:0.28793
[318]	train-aucpr:0.89532	validation-aucpr:0.29608
[0]	train-aucpr:0.58415	validation-aucpr:0.03021
[100]	train-aucpr:0.90429	validation-aucpr:0.41417

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1433.92it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1199.90it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1251.27it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1474.48it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1202.38it/s]
Bootstrapping pr_auc:  28%|██▊       | 283/1000 [00:00<00:00, 1452.69it/s]

[200]	train-aucpr:0.90209	validation-aucpr:0.41714
[0]	train-aucpr:0.50911	validation-aucpr:0.04052
[100]	train-aucpr:0.91049	validation-aucpr:0.34030
[300]	train-aucpr:0.90209	validation-aucpr:0.41714
[100]	train-aucpr:0.90319	validation-aucpr:0.24988
[345]	train-aucpr:0.90209	validation-aucpr:0.41714
[200]	train-aucpr:0.90757	validation-aucpr:0.33356
[221]	train-aucpr:0.91049	validation-aucpr:0.34030
[200]	train-aucpr:0.90343	validation-aucpr:0.25536
[203]	train-aucpr:0.90319	validation-aucpr:0.24988

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1259.30it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1230.39it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1411.89it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1612.34it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1568.15it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1555.90it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1570.83it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1563.69it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1541.15it/s]

bound,Metrics,estimate,lower,upper,models
0,AUPRC_value,40.4812,22.3328,65.7593,XGBoost (No VL info & SMOTE)
1,AUROC_value,91.5237,80.6452,97.6636,XGBoost (No VL info & SMOTE)
2,Accuracy,87.6314,81.3822,93.0665,XGBoost (No VL info & SMOTE)
3,Accuracy_train,86.4616,81.2513,90.4322,XGBoost (No VL info & SMOTE)
4,NPV,99.3997,98.3108,100.0000,XGBoost (No VL info & SMOTE)
5,Precision,18.1561,12.3177,26.8013,XGBoost (No VL info & SMOTE)
6,Sensitivity,82.7000,50.0000,100.0000,XGBoost (No VL info & SMOTE)
7,Specificity,87.7850,80.9657,94.0810,XGBoost (No VL info & SMOTE)

## Fitting data list with simulated VL at symptom onset

In [5]:
xgb_vlsymp_sim_list = model_func_xgb_tune(split_list_sim_onset_valid_smote_final)
xgb_vlsymp_sim_met_summary = sum_metric(xgb_vlsymp_sim_list)
xgb_vlsymp_sim_metrics_summary = xgb_vlsymp_sim_met_summary["metric_summary"]
xgb_vlsymp_sim_summary = met_collate_func(xgb_vlsymp_sim_metrics_summary).assign(
    models = "XGBoost (VL symp simulated & SMOTE)"
)
xgb_vlsymp_sim_summary

/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:27] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:27] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:27] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:27] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:27] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:27] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:27] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:27] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:27] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:27] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:27] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:27] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:27] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:27] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:27] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:27] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:27] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:27] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:27] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:27] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]1551.24it/s]

[0]	train-aucpr:0.51440	validation-aucpr:0.03697
[0]	train-aucpr:0.54305	validation-aucpr:0.04013
[100]	train-aucpr:0.92000	validation-aucpr:0.17265
[0]	train-aucpr:0.57580	validation-aucpr:0.03009
[0]	train-aucpr:0.53639	validation-aucpr:0.03127
[0]	train-aucpr:0.54628	validation-aucpr:0.03734
[0]	train-aucpr:0.56935	validation-aucpr:0.04865
[200]	train-aucpr:0.91966	validation-aucpr:0.17626
[100]	train-aucpr:0.89948	validation-aucpr:0.30697
[0]	train-aucpr:0.52476	validation-aucpr:0.03936
[209]	train-aucpr:0.91966	validation-aucpr:0.17626
[0]	train-aucpr:0.57182	validation-aucpr:0.03021
[100]	train-aucpr:0.92566	validation-aucpr:0.39720
[100]	train-aucpr:0.94450	validation-aucpr:0.23491
[100]	train-aucpr:0.93525	validation-aucpr:0.22830
[200]	train-aucpr:0.89636	validation-aucpr:0.30800
[204]	train-aucpr:0.89780	validation-aucpr:0.30656
[100]	train-aucpr:0.94962	validation-aucpr:0.26426
[100]	train-aucpr:0.90286	validation-aucpr:0.45641
[0]	train-aucpr:0.54920	validation-aucpr:0.02984
[100]	train-aucpr:0.92852	validation-aucpr:0.19376
[200]	train-aucpr:0.94601	validation-aucpr:0.23531
[200]	train-aucpr:0.93528	validation-aucpr:0.23139
[204]	train-aucpr:0.94600	validation-aucpr:0.23531
[204]	train-aucpr:0.93587	validation-aucpr:0.23333
[200]	train-aucpr:0.92316	validation-aucpr:0.40251
[200]	train-aucpr:0.94733	validation-aucpr:0.24698
[205]	train-aucpr:0.94719	validation-aucpr:0.24698
[200]	train-aucpr:0.90181	validation-aucpr:0.43769
[100]	train-aucpr:0.90418	validation-aucpr:0.27724
[200]	train-aucpr:0.92707	validation-aucpr:0.18535
[300]	train-aucpr:0.92297	validation-aucpr:0.40264
[0]	train-aucpr:0.54171	validation-aucpr:0.03141
[200]	train-aucpr:0.90621	validation-aucpr:0.27877
[300]	train-aucpr:0.92886	validation-aucpr:0.18717
[300]	train-aucpr:0.90406	validation-aucpr:0.43145
[327]	train-aucpr:0.92918	validation-aucpr:0.18578
[228]	train-aucpr:0.90594	validation-aucpr:0.27968
[325]	train-aucpr:0.90711	validation-aucpr:0.43578
[400]	train-aucpr:0.92277	validation-aucpr:0.39594
[407]	train-aucpr:0.92264	validation-aucpr:0.39594
[100]	train-aucpr:0.93688	validation-aucpr:0.22018
[0]	train-aucpr:0.57115	validation-aucpr:0.02235

Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:27] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:27] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:27] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:27] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
Bootstrapping pr_auc:  15%|█▍        | 146/1000 [00:00<00:00, 1285.52it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:28] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:28] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
Bootstrapping pr_auc:  12%|█▏        | 118/1000 [00:00<00:00, 1045.39it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:28] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:28] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
Bootstrapping pr_auc:  13%|█▎        | 129/1000 [00:00<00:00, 1288.93it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:28] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:28] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
Bootstrapping pr_auc:  32%|███▏      | 324/1000 [00:00<00:00, 1617.62it/s]

[200]	train-aucpr:0.94003	validation-aucpr:0.22034
[204]	train-aucpr:0.93924	validation-aucpr:0.22109
[0]	train-aucpr:0.55870	validation-aucpr:0.04176
[100]	train-aucpr:0.91904	validation-aucpr:0.18286
[0]	train-aucpr:0.56957	validation-aucpr:0.02647
[0]	train-aucpr:0.52290	validation-aucpr:0.03592
[100]	train-aucpr:0.92027	validation-aucpr:0.48612
[200]	train-aucpr:0.91824	validation-aucpr:0.17473
[100]	train-aucpr:0.91687	validation-aucpr:0.30202
[100]	train-aucpr:0.91895	validation-aucpr:0.39489
[200]	train-aucpr:0.92153	validation-aucpr:0.47576
[0]	train-aucpr:0.51998	validation-aucpr:0.03169
[300]	train-aucpr:0.91877	validation-aucpr:0.16766
[200]	train-aucpr:0.91652	validation-aucpr:0.30094
[317]	train-aucpr:0.92279	validation-aucpr:0.17071
[222]	train-aucpr:0.91609	validation-aucpr:0.29197
[200]	train-aucpr:0.92289	validation-aucpr:0.48152
[292]	train-aucpr:0.92441	validation-aucpr:0.47338
[100]	train-aucpr:0.93736	validation-aucpr:0.37773
[300]	train-aucpr:0.92381	validation-aucpr:0.48228
[200]	train-aucpr:0.93790	validation-aucpr:0.37832
[400]	train-aucpr:0.92601	validation-aucpr:0.44829
[300]	train-aucpr:0.93894	validation-aucpr:0.37761
[420]	train-aucpr:0.92602	validation-aucpr:0.44829

Bootstrapping pr_auc:  57%|█████▊    | 575/1000 [00:00<00:00, 1396.75it/s]

[321]	train-aucpr:0.93919	validation-aucpr:0.37708

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1537.53it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1416.50it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1472.68it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1384.51it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1418.25it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1367.62it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1342.49it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1393.76it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1277.84it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1204.32it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1515.47it/s]
Bootstrapping pr_auc:  77%|███████▋  | 772/1000 [00:00<00:00, 1246.01it/s]

[0]	train-aucpr:0.58121	validation-aucpr:0.03047
[100]	train-aucpr:0.93138	validation-aucpr:0.35268
[200]	train-aucpr:0.92922	validation-aucpr:0.35811
[236]	train-aucpr:0.93191	validation-aucpr:0.34641
[0]	train-aucpr:0.57678	validation-aucpr:0.02647
[0]	train-aucpr:0.56698	validation-aucpr:0.02688
[100]	train-aucpr:0.91463	validation-aucpr:0.28122
[100]	train-aucpr:0.92062	validation-aucpr:0.25461
[0]	train-aucpr:0.52542	validation-aucpr:0.03141
[200]	train-aucpr:0.92234	validation-aucpr:0.28757

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1326.58it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1256.55it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1314.62it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1269.05it/s]
Bootstrapping pr_auc:  11%|█▏        | 113/1000 [00:00<00:00, 1125.58it/s]

[0]	train-aucpr:0.53003	validation-aucpr:0.02540
[0]	train-aucpr:0.54291	validation-aucpr:0.03477
[200]	train-aucpr:0.92135	validation-aucpr:0.25753
[100]	train-aucpr:0.93307	validation-aucpr:0.18127
[271]	train-aucpr:0.92132	validation-aucpr:0.25756
[100]	train-aucpr:0.93519	validation-aucpr:0.21390
[300]	train-aucpr:0.92669	validation-aucpr:0.27431
[304]	train-aucpr:0.92674	validation-aucpr:0.27431
[200]	train-aucpr:0.93440	validation-aucpr:0.16995
[100]	train-aucpr:0.89686	validation-aucpr:0.43588
[0]	train-aucpr:0.53873	validation-aucpr:0.03526
[212]	train-aucpr:0.93426	validation-aucpr:0.17048
[0]	train-aucpr:0.54859	validation-aucpr:0.03198
[200]	train-aucpr:0.93788	validation-aucpr:0.17063
[218]	train-aucpr:0.93743	validation-aucpr:0.17121
[200]	train-aucpr:0.89640	validation-aucpr:0.43588
[100]	train-aucpr:0.92494	validation-aucpr:0.42187
[207]	train-aucpr:0.89655	validation-aucpr:0.43588
[100]	train-aucpr:0.92692	validation-aucpr:0.28796
[0]	train-aucpr:0.54972	validation-aucpr:0.02568
[200]	train-aucpr:0.92348	validation-aucpr:0.43245
[200]	train-aucpr:0.92732	validation-aucpr:0.26959
[300]	train-aucpr:0.92881	validation-aucpr:0.51563
[100]	train-aucpr:0.87975	validation-aucpr:0.31515
[0]	train-aucpr:0.57174	validation-aucpr:0.02365
[300]	train-aucpr:0.92747	validation-aucpr:0.25276
[327]	train-aucpr:0.92750	validation-aucpr:0.25276
[400]	train-aucpr:0.93033	validation-aucpr:0.50257
[0]	train-aucpr:0.57798	validation-aucpr:0.02947
[200]	train-aucpr:0.87895	validation-aucpr:0.31580
[100]	train-aucpr:0.88115	validation-aucpr:0.30026

Bootstrapping pr_auc:  12%|█▏        | 115/1000 [00:00<00:00, 1145.96it/s]

[500]	train-aucpr:0.93282	validation-aucpr:0.49296
[531]	train-aucpr:0.93329	validation-aucpr:0.49296
[291]	train-aucpr:0.87930	validation-aucpr:0.31580
[200]	train-aucpr:0.88118	validation-aucpr:0.28509
[100]	train-aucpr:0.91889	validation-aucpr:0.25480
[0]	train-aucpr:0.57338	validation-aucpr:0.02444
[300]	train-aucpr:0.88605	validation-aucpr:0.27245
[301]	train-aucpr:0.89008	validation-aucpr:0.26989
[200]	train-aucpr:0.91467	validation-aucpr:0.25303
[100]	train-aucpr:0.93816	validation-aucpr:0.25005
[0]	train-aucpr:0.52272	validation-aucpr:0.02578
[300]	train-aucpr:0.91649	validation-aucpr:0.26989
[100]	train-aucpr:0.92117	validation-aucpr:0.35732
[200]	train-aucpr:0.93750	validation-aucpr:0.25557
[0]	train-aucpr:0.54154	validation-aucpr:0.02607
[200]	train-aucpr:0.92203	validation-aucpr:0.36244
[204]	train-aucpr:0.92223	validation-aucpr:0.36244
[400]	train-aucpr:0.91670	validation-aucpr:0.29536
[300]	train-aucpr:0.93906	validation-aucpr:0.25850
[100]	train-aucpr:0.93003	validation-aucpr:0.16239
[0]	train-aucpr:0.52366	validation-aucpr:0.02688
[400]	train-aucpr:0.94079	validation-aucpr:0.25843
[500]	train-aucpr:0.92011	validation-aucpr:0.29604
[200]	train-aucpr:0.93172	validation-aucpr:0.16472

Bootstrapping pr_auc:  68%|██████▊   | 680/1000 [00:00<00:00, 1292.86it/s]

[204]	train-aucpr:0.93203	validation-aucpr:0.16241
[100]	train-aucpr:0.91890	validation-aucpr:0.24584
[564]	train-aucpr:0.91918	validation-aucpr:0.29363
[488]	train-aucpr:0.94023	validation-aucpr:0.25843
[200]	train-aucpr:0.92101	validation-aucpr:0.24554
[206]	train-aucpr:0.92121	validation-aucpr:0.24652

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1367.65it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1556.88it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1488.36it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1541.04it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1440.37it/s]

[0]	train-aucpr:0.52943	validation-aucpr:0.04093
[100]	train-aucpr:0.88993	validation-aucpr:0.49701
[200]	train-aucpr:0.89102	validation-aucpr:0.50440
[0]	train-aucpr:0.55288	validation-aucpr:0.03034
[277]	train-aucpr:0.89472	validation-aucpr:0.49968
[100]	train-aucpr:0.90862	validation-aucpr:0.46753
[0]	train-aucpr:0.53932	validation-aucpr:0.04134
[200]	train-aucpr:0.90904	validation-aucpr:0.47438
[206]	train-aucpr:0.90900	validation-aucpr:0.47438

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1287.92it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1447.22it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1333.11it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1301.21it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1316.29it/s]

[100]	train-aucpr:0.91863	validation-aucpr:0.33075
[200]	train-aucpr:0.91888	validation-aucpr:0.33396
[204]	train-aucpr:0.91889	validation-aucpr:0.33396
[0]	train-aucpr:0.59043	validation-aucpr:0.02677
[0]	train-aucpr:0.58291	validation-aucpr:0.03169
[100]	train-aucpr:0.93788	validation-aucpr:0.47039
[0]	train-aucpr:0.54723	validation-aucpr:0.02647
[200]	train-aucpr:0.93706	validation-aucpr:0.44583
[218]	train-aucpr:0.93708	validation-aucpr:0.44583
[100]	train-aucpr:0.93113	validation-aucpr:0.31380
[0]	train-aucpr:0.51524	validation-aucpr:0.03370
[100]	train-aucpr:0.92683	validation-aucpr:0.17619
[0]	train-aucpr:0.56558	validation-aucpr:0.03155

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1405.89it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1528.42it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1582.68it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1311.33it/s]
Bootstrapping pr_auc:  48%|████▊     | 476/1000 [00:00<00:00, 1557.99it/s]

[200]	train-aucpr:0.93257	validation-aucpr:0.31976
[204]	train-aucpr:0.93297	validation-aucpr:0.30328
[200]	train-aucpr:0.92740	validation-aucpr:0.24468
[100]	train-aucpr:0.94174	validation-aucpr:0.28340
[0]	train-aucpr:0.56447	validation-aucpr:0.02959
[100]	train-aucpr:0.91706	validation-aucpr:0.26397
[300]	train-aucpr:0.92841	validation-aucpr:0.24574
[200]	train-aucpr:0.94171	validation-aucpr:0.28895
[321]	train-aucpr:0.92810	validation-aucpr:0.24494
[100]	train-aucpr:0.88513	validation-aucpr:0.51399
[200]	train-aucpr:0.91849	validation-aucpr:0.22495
[237]	train-aucpr:0.91935	validation-aucpr:0.22462
[300]	train-aucpr:0.94115	validation-aucpr:0.29430
[200]	train-aucpr:0.88217	validation-aucpr:0.50559
[0]	train-aucpr:0.57372	validation-aucpr:0.02325
[400]	train-aucpr:0.94187	validation-aucpr:0.29380
[300]	train-aucpr:0.88239	validation-aucpr:0.50725
[325]	train-aucpr:0.88266	validation-aucpr:0.50725
[100]	train-aucpr:0.93590	validation-aucpr:0.28817
[0]	train-aucpr:0.52454	validation-aucpr:0.03155
[500]	train-aucpr:0.94829	validation-aucpr:0.24686
[200]	train-aucpr:0.93711	validation-aucpr:0.24098
[211]	train-aucpr:0.93772	validation-aucpr:0.17525
[542]	train-aucpr:0.94818	validation-aucpr:0.24729
[0]	train-aucpr:0.56141	validation-aucpr:0.03009
[100]	train-aucpr:0.89690	validation-aucpr:0.47585

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1227.66it/s]
Bootstrapping pr_auc:  14%|█▎        | 136/1000 [00:00<00:00, 1352.98it/s]

[0]	train-aucpr:0.55093	validation-aucpr:0.02731
[100]	train-aucpr:0.91254	validation-aucpr:0.28982
[0]	train-aucpr:0.53050	validation-aucpr:0.03575
[200]	train-aucpr:0.89420	validation-aucpr:0.42496
[204]	train-aucpr:0.89434	validation-aucpr:0.42496
[100]	train-aucpr:0.92118	validation-aucpr:0.23380
[200]	train-aucpr:0.91358	validation-aucpr:0.28361
[100]	train-aucpr:0.92177	validation-aucpr:0.21034
[277]	train-aucpr:0.91519	validation-aucpr:0.28260
[200]	train-aucpr:0.92214	validation-aucpr:0.28438
[200]	train-aucpr:0.91910	validation-aucpr:0.21179
[204]	train-aucpr:0.91914	validation-aucpr:0.21179
[300]	train-aucpr:0.92266	validation-aucpr:0.28041
[0]	train-aucpr:0.52690	validation-aucpr:0.02753
[400]	train-aucpr:0.92347	validation-aucpr:0.28032
[406]	train-aucpr:0.92416	validation-aucpr:0.27891
[100]	train-aucpr:0.91126	validation-aucpr:0.36669

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1251.84it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1331.44it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1440.64it/s]
Bootstrapping pr_auc:  86%|████████▌ | 857/1000 [00:00<00:00, 1307.80it/s]

[200]	train-aucpr:0.91264	validation-aucpr:0.35068
[209]	train-aucpr:0.91120	validation-aucpr:0.34414
[0]	train-aucpr:0.51070	validation-aucpr:0.04176
[0]	train-aucpr:0.52618	validation-aucpr:0.04113
[100]	train-aucpr:0.87884	validation-aucpr:0.48022
[100]	train-aucpr:0.90974	validation-aucpr:0.30201
[0]	train-aucpr:0.55687	validation-aucpr:0.03202

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1313.40it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1396.13it/s]
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]1546.18it/s]

[200]	train-aucpr:0.87739	validation-aucpr:0.47806
[224]	train-aucpr:0.87838	validation-aucpr:0.47740
[200]	train-aucpr:0.90882	validation-aucpr:0.31952
[204]	train-aucpr:0.90883	validation-aucpr:0.31952
[100]	train-aucpr:0.89868	validation-aucpr:0.53885
[0]	train-aucpr:0.51307	validation-aucpr:0.03385
[200]	train-aucpr:0.89776	validation-aucpr:0.52997
[100]	train-aucpr:0.91275	validation-aucpr:0.11288
[260]	train-aucpr:0.89774	validation-aucpr:0.52997
[200]	train-aucpr:0.91348	validation-aucpr:0.10750
[204]	train-aucpr:0.91514	validation-aucpr:0.10759
[0]	train-aucpr:0.54214	validation-aucpr:0.02742
[100]	train-aucpr:0.92401	validation-aucpr:0.45437

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1293.41it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1300.28it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1514.52it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1454.13it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1199.32it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1378.93it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1461.79it/s]

[200]	train-aucpr:0.92314	validation-aucpr:0.52924
[0]	train-aucpr:0.52333	validation-aucpr:0.01720
[300]	train-aucpr:0.92363	validation-aucpr:0.55012
[100]	train-aucpr:0.88184	validation-aucpr:0.22065
[0]	train-aucpr:0.56197	validation-aucpr:0.03477
[400]	train-aucpr:0.92559	validation-aucpr:0.56447[200]	train-aucpr:0.87928	validation-aucpr:0.22128

[0]	train-aucpr:0.54499	validation-aucpr:0.03242
[300]	train-aucpr:0.88164	validation-aucpr:0.22206
[500]	train-aucpr:0.93362	validation-aucpr:0.54955
[100]	train-aucpr:0.90343	validation-aucpr:0.38741
[100]	train-aucpr:0.89792	validation-aucpr:0.47629
[400]	train-aucpr:0.88497	validation-aucpr:0.20702
[572]	train-aucpr:0.93396	validation-aucpr:0.54955
[0]	train-aucpr:0.51480	validation-aucpr:0.03446
[486]	train-aucpr:0.88492	validation-aucpr:0.21522
[200]	train-aucpr:0.89726	validation-aucpr:0.47812
[204]	train-aucpr:0.89728	validation-aucpr:0.47812
[200]	train-aucpr:0.90394	validation-aucpr:0.37829
[205]	train-aucpr:0.90395	validation-aucpr:0.37829

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1285.65it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1433.82it/s]
Bootstrapping pr_auc:  65%|██████▌   | 654/1000 [00:00<00:00, 1571.80it/s]

[0]	train-aucpr:0.53709	validation-aucpr:0.02657
[100]	train-aucpr:0.91604	validation-aucpr:0.23271
[100]	train-aucpr:0.91687	validation-aucpr:0.21059
[200]	train-aucpr:0.91348	validation-aucpr:0.23323
[0]	train-aucpr:0.59897	validation-aucpr:0.02779
[257]	train-aucpr:0.91348	validation-aucpr:0.23323
[0]	train-aucpr:0.56836	validation-aucpr:0.02657
[200]	train-aucpr:0.91765	validation-aucpr:0.20039
[207]	train-aucpr:0.91736	validation-aucpr:0.19897
[100]	train-aucpr:0.93429	validation-aucpr:0.20815
[0]	train-aucpr:0.56487	validation-aucpr:0.03644
[100]	train-aucpr:0.93391	validation-aucpr:0.13629
[200]	train-aucpr:0.93407	validation-aucpr:0.21656
[236]	train-aucpr:0.93393	validation-aucpr:0.21606
[100]	train-aucpr:0.96048	validation-aucpr:0.36016
[0]	train-aucpr:0.52663	validation-aucpr:0.04497
[0]	train-aucpr:0.55743	validation-aucpr:0.03936
[200]	train-aucpr:0.93332	validation-aucpr:0.14404
[204]	train-aucpr:0.93342	validation-aucpr:0.14336

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1289.21it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1557.37it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1478.42it/s]
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]1076.24it/s]

[200]	train-aucpr:0.95905	validation-aucpr:0.33248
[100]	train-aucpr:0.90502	validation-aucpr:0.28383
[100]	train-aucpr:0.89971	validation-aucpr:0.78716
[200]	train-aucpr:0.91258	validation-aucpr:0.30297
[300]	train-aucpr:0.95964	validation-aucpr:0.37866
[200]	train-aucpr:0.90363	validation-aucpr:0.78716
[204]	train-aucpr:0.90367	validation-aucpr:0.78716
[0]	train-aucpr:0.50635	validation-aucpr:0.04093
[230]	train-aucpr:0.91230	validation-aucpr:0.29476
[0]	train-aucpr:0.56007	validation-aucpr:0.03009
[400]	train-aucpr:0.96051	validation-aucpr:0.37866
[100]	train-aucpr:0.93171	validation-aucpr:0.25412
[100]	train-aucpr:0.87157	validation-aucpr:0.45783
[500]	train-aucpr:0.95996	validation-aucpr:0.39521
[200]	train-aucpr:0.93093	validation-aucpr:0.24941
[204]	train-aucpr:0.93048	validation-aucpr:0.24941
[200]	train-aucpr:0.87154	validation-aucpr:0.46127
[205]	train-aucpr:0.87154	validation-aucpr:0.46127
[600]	train-aucpr:0.95985	validation-aucpr:0.39735

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1506.45it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1504.41it/s]
Bootstrapping pr_auc:  15%|█▍        | 148/1000 [00:00<00:00, 1478.90it/s]

[621]	train-aucpr:0.95984	validation-aucpr:0.39758
[0]	train-aucpr:0.58304	validation-aucpr:0.04197
[0]	train-aucpr:0.59480	validation-aucpr:0.02374
[100]	train-aucpr:0.92951	validation-aucpr:0.40613
[100]	train-aucpr:0.91029	validation-aucpr:0.25742
[200]	train-aucpr:0.92796	validation-aucpr:0.40505
[219]	train-aucpr:0.92811	validation-aucpr:0.40505
[200]	train-aucpr:0.91032	validation-aucpr:0.25547
[300]	train-aucpr:0.91061	validation-aucpr:0.25556
[314]	train-aucpr:0.91150	validation-aucpr:0.25556

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1562.00it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1328.58it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1371.20it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1297.91it/s]
Bootstrapping pr_auc:  82%|████████▏ | 821/1000 [00:00<00:00, 1366.46it/s]

[0]	train-aucpr:0.53938	validation-aucpr:0.03073
[100]	train-aucpr:0.94845	validation-aucpr:0.23786
[0]	train-aucpr:0.57981	validation-aucpr:0.02513
[200]	train-aucpr:0.94889	validation-aucpr:0.23601
[231]	train-aucpr:0.94885	validation-aucpr:0.23601
[100]	train-aucpr:0.94810	validation-aucpr:0.11230
[0]	train-aucpr:0.57956	validation-aucpr:0.02616
[200]	train-aucpr:0.94907	validation-aucpr:0.11281
[100]	train-aucpr:0.94558	validation-aucpr:0.11893
[228]	train-aucpr:0.94731	validation-aucpr:0.09580
[0]	train-aucpr:0.52676	validation-aucpr:0.02310
[0]	train-aucpr:0.55642	validation-aucpr:0.03542
[100]	train-aucpr:0.94040	validation-aucpr:0.12499

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1399.08it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1293.00it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1387.64it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1360.94it/s]
Bootstrapping pr_auc:  16%|█▋        | 164/1000 [00:00<00:00, 1635.54it/s]

[200]	train-aucpr:0.94580	validation-aucpr:0.10876
[204]	train-aucpr:0.94581	validation-aucpr:0.10876
[200]	train-aucpr:0.93810	validation-aucpr:0.12210
[204]	train-aucpr:0.93813	validation-aucpr:0.12210
[0]	train-aucpr:0.53434	validation-aucpr:0.03662
[100]	train-aucpr:0.90856	validation-aucpr:0.43397
[0]	train-aucpr:0.54542	validation-aucpr:0.03918
[200]	train-aucpr:0.90820	validation-aucpr:0.43174
[100]	train-aucpr:0.91346	validation-aucpr:0.25474
[0]	train-aucpr:0.52599	validation-aucpr:0.04033
[100]	train-aucpr:0.92249	validation-aucpr:0.20305
[300]	train-aucpr:0.90642	validation-aucpr:0.43174
[0]	train-aucpr:0.52378	validation-aucpr:0.03430
[200]	train-aucpr:0.91422	validation-aucpr:0.25906
[100]	train-aucpr:0.87861	validation-aucpr:0.36093
[209]	train-aucpr:0.91363	validation-aucpr:0.25906
[200]	train-aucpr:0.92222	validation-aucpr:0.20917
[400]	train-aucpr:0.90987	validation-aucpr:0.42856
[408]	train-aucpr:0.90971	validation-aucpr:0.42856
[200]	train-aucpr:0.88162	validation-aucpr:0.34384
[204]	train-aucpr:0.88179	validation-aucpr:0.34384

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1354.49it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1378.75it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1336.71it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1343.60it/s]
Bootstrapping pr_auc:  49%|████▉     | 491/1000 [00:00<00:00, 1500.44it/s]

[300]	train-aucpr:0.92276	validation-aucpr:0.24885
[0]	train-aucpr:0.53155	validation-aucpr:0.03609
[100]	train-aucpr:0.91029	validation-aucpr:0.27749
[400]	train-aucpr:0.92296	validation-aucpr:0.24885
[408]	train-aucpr:0.92284	validation-aucpr:0.24885
[0]	train-aucpr:0.51733	validation-aucpr:0.03326
[200]	train-aucpr:0.91230	validation-aucpr:0.26652
[204]	train-aucpr:0.91230	validation-aucpr:0.26652
[100]	train-aucpr:0.94935	validation-aucpr:0.17676
[100]	train-aucpr:0.91231	validation-aucpr:0.17592
[200]	train-aucpr:0.94709	validation-aucpr:0.15296
[0]	train-aucpr:0.57055	validation-aucpr:0.03326
[227]	train-aucpr:0.94613	validation-aucpr:0.15682
[200]	train-aucpr:0.91366	validation-aucpr:0.27746
[0]	train-aucpr:0.57372	validation-aucpr:0.02971
[300]	train-aucpr:0.91337	validation-aucpr:0.27746
[100]	train-aucpr:0.93131	validation-aucpr:0.30532
[400]	train-aucpr:0.91501	validation-aucpr:0.27684
[100]	train-aucpr:0.92428	validation-aucpr:0.30779
[200]	train-aucpr:0.93130	validation-aucpr:0.30853
[200]	train-aucpr:0.92378	validation-aucpr:0.32179
[207]	train-aucpr:0.92381	validation-aucpr:0.32179
[280]	train-aucpr:0.93183	validation-aucpr:0.30586
[500]	train-aucpr:0.91552	validation-aucpr:0.27462
[501]	train-aucpr:0.91550	validation-aucpr:0.27367

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1369.99it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1103.82it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1214.36it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1425.39it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1484.73it/s]
Bootstrapping pr_auc:  85%|████████▍ | 846/1000 [00:00<00:00, 1490.00it/s]

[0]	train-aucpr:0.53572	validation-aucpr:0.02408
[100]	train-aucpr:0.91671	validation-aucpr:0.20317
[0]	train-aucpr:0.53202	validation-aucpr:0.02657
[200]	train-aucpr:0.91625	validation-aucpr:0.20116
[100]	train-aucpr:0.92498	validation-aucpr:0.25170
[232]	train-aucpr:0.91605	validation-aucpr:0.20373
[200]	train-aucpr:0.92316	validation-aucpr:0.19824
[252]	train-aucpr:0.92325	validation-aucpr:0.20275
[0]	train-aucpr:0.50232	validation-aucpr:0.02374
[100]	train-aucpr:0.89690	validation-aucpr:0.18083

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1390.04it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1258.59it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1462.86it/s]
Bootstrapping pr_auc:  78%|███████▊  | 775/1000 [00:00<00:00, 1097.51it/s]

[0]	train-aucpr:0.56007	validation-aucpr:0.03697
[200]	train-aucpr:0.90014	validation-aucpr:0.15150
[224]	train-aucpr:0.90016	validation-aucpr:0.15158
[100]	train-aucpr:0.94605	validation-aucpr:0.20367
[200]	train-aucpr:0.94647	validation-aucpr:0.21206
[204]	train-aucpr:0.94647	validation-aucpr:0.21206
[0]	train-aucpr:0.50203	validation-aucpr:0.03592
[100]	train-aucpr:0.90542	validation-aucpr:0.17970
[0]	train-aucpr:0.55389	validation-aucpr:0.04033
[200]	train-aucpr:0.90341	validation-aucpr:0.18674
[204]	train-aucpr:0.90419	validation-aucpr:0.18072
[100]	train-aucpr:0.93116	validation-aucpr:0.55449
[200]	train-aucpr:0.93059	validation-aucpr:0.60156

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1427.60it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1542.20it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1266.36it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1287.86it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1327.66it/s]
Bootstrapping pr_auc:  42%|████▏     | 415/1000 [00:00<00:00, 1398.12it/s]

[0]	train-aucpr:0.54331	validation-aucpr:0.03326
[300]	train-aucpr:0.93190	validation-aucpr:0.59979
[0]	train-aucpr:0.54805	validation-aucpr:0.02626
[100]	train-aucpr:0.92453	validation-aucpr:0.25236
[400]	train-aucpr:0.93205	validation-aucpr:0.60156
[200]	train-aucpr:0.92390	validation-aucpr:0.25449
[0]	train-aucpr:0.53631	validation-aucpr:0.02587
[100]	train-aucpr:0.93176	validation-aucpr:0.17289
[289]	train-aucpr:0.92421	validation-aucpr:0.25558
[0]	train-aucpr:0.57356	validation-aucpr:0.03141
[200]	train-aucpr:0.93259	validation-aucpr:0.17014
[100]	train-aucpr:0.90350	validation-aucpr:0.13487
[252]	train-aucpr:0.93276	validation-aucpr:0.17014
[0]	train-aucpr:0.51733	validation-aucpr:0.03400
[100]	train-aucpr:0.91631	validation-aucpr:0.38908
[200]	train-aucpr:0.90331	validation-aucpr:0.13468

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1220.09it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1179.70it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1153.65it/s]

[255]	train-aucpr:0.90470	validation-aucpr:0.13468
[200]	train-aucpr:0.91773	validation-aucpr:0.40551
[100]	train-aucpr:0.92013	validation-aucpr:0.39241
[0]	train-aucpr:0.58713	validation-aucpr:0.03169
[200]	train-aucpr:0.92582	validation-aucpr:0.38909
[300]	train-aucpr:0.91866	validation-aucpr:0.39707
[296]	train-aucpr:0.92763	validation-aucpr:0.38996
[363]	train-aucpr:0.91842	validation-aucpr:0.39251
[100]	train-aucpr:0.95402	validation-aucpr:0.12289
[200]	train-aucpr:0.95442	validation-aucpr:0.12556
[222]	train-aucpr:0.95399	validation-aucpr:0.12505[0]	train-aucpr:0.54071	validation-aucpr:0.03526

[100]	train-aucpr:0.89995	validation-aucpr:0.32838
[0]	train-aucpr:0.55999	validation-aucpr:0.02947
[200]	train-aucpr:0.89589	validation-aucpr:0.33366
[204]	train-aucpr:0.89589	validation-aucpr:0.33366

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1281.59it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1478.48it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1221.72it/s]
Bootstrapping pr_auc:  15%|█▌        | 153/1000 [00:00<00:00, 1520.69it/s]

[100]	train-aucpr:0.90049	validation-aucpr:0.29248
[0]	train-aucpr:0.59373	validation-aucpr:0.04033
[200]	train-aucpr:0.90209	validation-aucpr:0.29019
[100]	train-aucpr:0.91939	validation-aucpr:0.62960[219]	train-aucpr:0.90090	validation-aucpr:0.29026

[0]	train-aucpr:0.52823	validation-aucpr:0.03461
[200]	train-aucpr:0.92530	validation-aucpr:0.60968
[100]	train-aucpr:0.87556	validation-aucpr:0.36306
[0]	train-aucpr:0.55591	validation-aucpr:0.03155
[300]	train-aucpr:0.92576	validation-aucpr:0.57357
[0]	train-aucpr:0.57430	validation-aucpr:0.02667
[100]	train-aucpr:0.94627	validation-aucpr:0.19817
[333]	train-aucpr:0.92585	validation-aucpr:0.56949
[200]	train-aucpr:0.87074	validation-aucpr:0.37778
[204]	train-aucpr:0.87386	validation-aucpr:0.36595
[200]	train-aucpr:0.94591	validation-aucpr:0.18330
[204]	train-aucpr:0.94589	validation-aucpr:0.18330

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1243.01it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1384.21it/s]
Bootstrapping pr_auc:  91%|█████████ | 911/1000 [00:00<00:00, 1472.31it/s]

[100]	train-aucpr:0.90988	validation-aucpr:0.33675
[200]	train-aucpr:0.91001	validation-aucpr:0.29780
[0]	train-aucpr:0.54650	validation-aucpr:0.03183
[280]	train-aucpr:0.91006	validation-aucpr:0.29780
[100]	train-aucpr:0.89732	validation-aucpr:0.29925
[0]	train-aucpr:0.55065	validation-aucpr:0.03644
[200]	train-aucpr:0.89408	validation-aucpr:0.29118
[232]	train-aucpr:0.89409	validation-aucpr:0.29194
[100]	train-aucpr:0.95240	validation-aucpr:0.25403
[200]	train-aucpr:0.95186	validation-aucpr:0.24819

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1440.74it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1346.99it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1168.87it/s]
Bootstrapping pr_auc:  31%|███▏      | 314/1000 [00:00<00:00, 1570.61it/s]

[226]	train-aucpr:0.95111	validation-aucpr:0.25502
[0]	train-aucpr:0.57260	validation-aucpr:0.03198
[100]	train-aucpr:0.90928	validation-aucpr:0.37116
[0]	train-aucpr:0.58415	validation-aucpr:0.03021
[200]	train-aucpr:0.90674	validation-aucpr:0.37434
[219]	train-aucpr:0.90798	validation-aucpr:0.35818
[0]	train-aucpr:0.50911	validation-aucpr:0.04052
[100]	train-aucpr:0.91287	validation-aucpr:0.30460
[100]	train-aucpr:0.90015	validation-aucpr:0.33743
[200]	train-aucpr:0.91285	validation-aucpr:0.27896
[207]	train-aucpr:0.91192	validation-aucpr:0.27681

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1479.33it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1327.20it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1148.57it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1471.54it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1217.42it/s]
Bootstrapping pr_auc:  16%|█▌        | 156/1000 [00:00<00:00, 1558.15it/s]

[200]	train-aucpr:0.90475	validation-aucpr:0.31945
[204]	train-aucpr:0.90485	validation-aucpr:0.31945

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1423.16it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1377.63it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1298.55it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1266.68it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1515.03it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1320.20it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1511.75it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1566.07it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1554.47it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1512.72it/s]

bound,Metrics,estimate,lower,upper,models
0,AUPRC_value,39.6819,19.6116,61.3963,XGBoost (VL symp simulated & SMOTE)
1,AUROC_value,91.1760,79.7924,97.5389,XGBoost (VL symp simulated & SMOTE)
2,Accuracy,88.8338,83.9879,93.5272,XGBoost (VL symp simulated & SMOTE)
3,Accuracy_train,86.3551,81.6965,90.4102,XGBoost (VL symp simulated & SMOTE)
4,NPV,99.2729,98.3301,100.0000,XGBoost (VL symp simulated & SMOTE)
5,Precision,19.0760,13.6383,29.1028,XGBoost (VL symp simulated & SMOTE)
6,Sensitivity,78.8000,50.0000,100.0000,XGBoost (VL symp simulated & SMOTE)
7,Specificity,89.1464,84.1121,94.2601,XGBoost (VL symp simulated & SMOTE)

## Fitting data list with VL at diagnosis

In [6]:
xgb_vldiag_list = model_func_xgb_tune(split_list_vldiag_valid_smote_final)
xgb_vldiag_met_summary = sum_metric(xgb_vldiag_list)
xgb_vldiag_metrics_summary = xgb_vldiag_met_summary["metric_summary"]
xgb_vldiag_summary = met_collate_func(xgb_vldiag_metrics_summary).assign(
    models = "XGBoost (VL diag & SMOTE)"
)
xgb_vldiag_summary

/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:37] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:37] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:37] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:37] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:37] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:37] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:37] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:37] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:37] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:37] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:37] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:37] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:37] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:37] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
Bootstrapping pr_auc:  16%|█▌        | 161/1000 [00:00<00:00, 1608.95it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:37] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:37] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()

[0]	train-aucpr:0.54171	validation-aucpr:0.03141
[0]	train-aucpr:0.54305	validation-aucpr:0.04013
[100]	train-aucpr:0.94442	validation-aucpr:0.30630
[100]	train-aucpr:0.91024	validation-aucpr:0.32457
[0]	train-aucpr:0.53639	validation-aucpr:0.03127
[200]	train-aucpr:0.90878	validation-aucpr:0.34234
[204]	train-aucpr:0.90801	validation-aucpr:0.34234
[0]	train-aucpr:0.56935	validation-aucpr:0.04865
[200]	train-aucpr:0.94454	validation-aucpr:0.31688
[0]	train-aucpr:0.51440	validation-aucpr:0.03697
[100]	train-aucpr:0.93949	validation-aucpr:0.27505
[100]	train-aucpr:0.95642	validation-aucpr:0.33776
[300]	train-aucpr:0.94414	validation-aucpr:0.31591
[100]	train-aucpr:0.93029	validation-aucpr:0.32423
[200]	train-aucpr:0.93941	validation-aucpr:0.28690
[204]	train-aucpr:0.94024	validation-aucpr:0.28952
[200]	train-aucpr:0.95550	validation-aucpr:0.31922
[0]	train-aucpr:0.51998	validation-aucpr:0.03169
[400]	train-aucpr:0.94528	validation-aucpr:0.31600
[200]	train-aucpr:0.92637	validation-aucpr:0.31932
[210]	train-aucpr:0.92625	validation-aucpr:0.32753
[426]	train-aucpr:0.94620	validation-aucpr:0.30570
[297]	train-aucpr:0.95473	validation-aucpr:0.32089
[100]	train-aucpr:0.93886	validation-aucpr:0.52973
[0]	train-aucpr:0.52476	validation-aucpr:0.03936
[0]	train-aucpr:0.54628	validation-aucpr:0.03734
[200]	train-aucpr:0.93837	validation-aucpr:0.61302
[100]	train-aucpr:0.91415	validation-aucpr:0.50656

/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:37] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:37] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:37] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:37] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:37] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:37] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:38] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:38] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:38] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:38] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:38] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:38] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
Bootstrapping pr_auc:  14%|█▍        | 142/1000 [00:00<00:00, 1271.54it/s]

[0]	train-aucpr:0.57580	validation-aucpr:0.03009
[100]	train-aucpr:0.94885	validation-aucpr:0.23028
[300]	train-aucpr:0.93924	validation-aucpr:0.61618
[0]	train-aucpr:0.54920	validation-aucpr:0.02984
[0]	train-aucpr:0.55870	validation-aucpr:0.04176
[200]	train-aucpr:0.91105	validation-aucpr:0.49585
[100]	train-aucpr:0.93784	validation-aucpr:0.30242
[200]	train-aucpr:0.94809	validation-aucpr:0.21827
[204]	train-aucpr:0.94807	validation-aucpr:0.21827
[100]	train-aucpr:0.91950	validation-aucpr:0.34320
[100]	train-aucpr:0.92271	validation-aucpr:0.51840
[300]	train-aucpr:0.91540	validation-aucpr:0.46737
[400]	train-aucpr:0.94176	validation-aucpr:0.61596
[335]	train-aucpr:0.91672	validation-aucpr:0.46997
[200]	train-aucpr:0.93794	validation-aucpr:0.30780
[227]	train-aucpr:0.93752	validation-aucpr:0.30883
[200]	train-aucpr:0.92006	validation-aucpr:0.34864
[205]	train-aucpr:0.91983	validation-aucpr:0.34889
[200]	train-aucpr:0.92371	validation-aucpr:0.51341
[0]	train-aucpr:0.56957	validation-aucpr:0.02647
[488]	train-aucpr:0.94621	validation-aucpr:0.61327
[297]	train-aucpr:0.92740	validation-aucpr:0.47461
[100]	train-aucpr:0.92217	validation-aucpr:0.56673
[0]	train-aucpr:0.57182	validation-aucpr:0.03021
[200]	train-aucpr:0.92190	validation-aucpr:0.56857
[0]	train-aucpr:0.52290	validation-aucpr:0.03592
[100]	train-aucpr:0.93102	validation-aucpr:0.27680

Bootstrapping pr_auc:  16%|█▌        | 162/1000 [00:00<00:00, 1611.51it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:38] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:38] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
Bootstrapping pr_auc:  45%|████▌     | 453/1000 [00:00<00:00, 1391.82it/s]

[100]	train-aucpr:0.94057	validation-aucpr:0.18465
[300]	train-aucpr:0.92288	validation-aucpr:0.56877
[200]	train-aucpr:0.93473	validation-aucpr:0.27172
[204]	train-aucpr:0.93484	validation-aucpr:0.27172
[200]	train-aucpr:0.94121	validation-aucpr:0.18018
[228]	train-aucpr:0.93990	validation-aucpr:0.17786
[368]	train-aucpr:0.92263	validation-aucpr:0.56557
[0]	train-aucpr:0.57115	validation-aucpr:0.02235
[100]	train-aucpr:0.92051	validation-aucpr:0.24731

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1546.55it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1561.94it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1384.15it/s]
Bootstrapping pr_auc:  79%|███████▉  | 788/1000 [00:00<00:00, 1321.44it/s]

[200]	train-aucpr:0.92050	validation-aucpr:0.15766
[289]	train-aucpr:0.92277	validation-aucpr:0.15536

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1449.05it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1509.92it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1209.24it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1380.27it/s]
Bootstrapping pr_auc:  63%|██████▎   | 633/1000 [00:00<00:00, 1142.18it/s]

[0]	train-aucpr:0.58121	validation-aucpr:0.03047
[100]	train-aucpr:0.94124	validation-aucpr:0.43926
[200]	train-aucpr:0.94228	validation-aucpr:0.45546
[210]	train-aucpr:0.94388	validation-aucpr:0.44914
[0]	train-aucpr:0.57678	validation-aucpr:0.02647
[100]	train-aucpr:0.92429	validation-aucpr:0.31906
[0]	train-aucpr:0.56698	validation-aucpr:0.02688
[0]	train-aucpr:0.52542	validation-aucpr:0.03141

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1458.21it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1378.50it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1234.19it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1245.06it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1318.74it/s]
Bootstrapping pr_auc:  91%|█████████▏| 914/1000 [00:00<00:00, 1189.12it/s]

[0]	train-aucpr:0.54291	validation-aucpr:0.03477
[200]	train-aucpr:0.92873	validation-aucpr:0.30062
[100]	train-aucpr:0.94378	validation-aucpr:0.17115
[100]	train-aucpr:0.93430	validation-aucpr:0.30140
[200]	train-aucpr:0.94196	validation-aucpr:0.16545
[209]	train-aucpr:0.94170	validation-aucpr:0.16422
[100]	train-aucpr:0.94858	validation-aucpr:0.25572
[200]	train-aucpr:0.93536	validation-aucpr:0.27170
[251]	train-aucpr:0.93553	validation-aucpr:0.27324
[300]	train-aucpr:0.92914	validation-aucpr:0.30029
[304]	train-aucpr:0.92915	validation-aucpr:0.30029
[0]	train-aucpr:0.53003	validation-aucpr:0.02540
[0]	train-aucpr:0.53873	validation-aucpr:0.03526
[200]	train-aucpr:0.94906	validation-aucpr:0.26170
[100]	train-aucpr:0.93085	validation-aucpr:0.41641
[100]	train-aucpr:0.90974	validation-aucpr:0.50902
[0]	train-aucpr:0.54859	validation-aucpr:0.03198
[0]	train-aucpr:0.54972	validation-aucpr:0.02568
[300]	train-aucpr:0.94937	validation-aucpr:0.26717
[200]	train-aucpr:0.93555	validation-aucpr:0.43661
[210]	train-aucpr:0.93474	validation-aucpr:0.43528
[200]	train-aucpr:0.90849	validation-aucpr:0.53110
[100]	train-aucpr:0.89641	validation-aucpr:0.34217
[400]	train-aucpr:0.94922	validation-aucpr:0.26152
[100]	train-aucpr:0.92867	validation-aucpr:0.27086
[300]	train-aucpr:0.90758	validation-aucpr:0.51577

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1198.99it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1186.74it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1369.95it/s]
Bootstrapping pr_auc:  14%|█▎        | 136/1000 [00:00<00:00, 1353.27it/s]

[200]	train-aucpr:0.89843	validation-aucpr:0.34717
[388]	train-aucpr:0.91272	validation-aucpr:0.51711
[500]	train-aucpr:0.94906	validation-aucpr:0.26459
[200]	train-aucpr:0.92833	validation-aucpr:0.27519
[209]	train-aucpr:0.92927	validation-aucpr:0.27492
[0]	train-aucpr:0.57174	validation-aucpr:0.02365
[276]	train-aucpr:0.89774	validation-aucpr:0.34717
[0]	train-aucpr:0.57798	validation-aucpr:0.02947
[100]	train-aucpr:0.89206	validation-aucpr:0.56523
[0]	train-aucpr:0.57338	validation-aucpr:0.02444
[200]	train-aucpr:0.89235	validation-aucpr:0.63263
[0]	train-aucpr:0.52272	validation-aucpr:0.02578
[100]	train-aucpr:0.92518	validation-aucpr:0.23554
[300]	train-aucpr:0.89674	validation-aucpr:0.62754
[100]	train-aucpr:0.94425	validation-aucpr:0.25628
[322]	train-aucpr:0.89467	validation-aucpr:0.62754
[100]	train-aucpr:0.93146	validation-aucpr:0.33310
[200]	train-aucpr:0.92395	validation-aucpr:0.23689
[210]	train-aucpr:0.92382	validation-aucpr:0.23481
[200]	train-aucpr:0.94483	validation-aucpr:0.25920
[210]	train-aucpr:0.94464	validation-aucpr:0.25920
[200]	train-aucpr:0.93238	validation-aucpr:0.31287
[212]	train-aucpr:0.93251	validation-aucpr:0.30952

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1379.65it/s]

[0]	train-aucpr:0.54154	validation-aucpr:0.02607
[100]	train-aucpr:0.93311	validation-aucpr:0.19105
[200]	train-aucpr:0.93521	validation-aucpr:0.19460
[204]	train-aucpr:0.93519	validation-aucpr:0.19460
[0]	train-aucpr:0.52366	validation-aucpr:0.02688
[100]	train-aucpr:0.92921	validation-aucpr:0.22943
[200]	train-aucpr:0.92998	validation-aucpr:0.22659
[232]	train-aucpr:0.93042	validation-aucpr:0.22910
[0]	train-aucpr:0.52943	validation-aucpr:0.04093

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1506.39it/s]
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]1547.89it/s]

[100]	train-aucpr:0.89102	validation-aucpr:0.65261
[200]	train-aucpr:0.89303	validation-aucpr:0.64433
[296]	train-aucpr:0.89861	validation-aucpr:0.64694
[0]	train-aucpr:0.55288	validation-aucpr:0.03034
[100]	train-aucpr:0.91660	validation-aucpr:0.42392
[0]	train-aucpr:0.53932	validation-aucpr:0.04134
[200]	train-aucpr:0.91603	validation-aucpr:0.43735
[206]	train-aucpr:0.91540	validation-aucpr:0.43735

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1427.28it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1315.70it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1378.01it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1438.26it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1391.65it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1355.75it/s]
Bootstrapping pr_auc:  94%|█████████▎| 935/1000 [00:00<00:00, 1507.76it/s]

[0]	train-aucpr:0.59043	validation-aucpr:0.02677
[100]	train-aucpr:0.92869	validation-aucpr:0.37370
[0]	train-aucpr:0.58291	validation-aucpr:0.03169
[100]	train-aucpr:0.94778	validation-aucpr:0.55484
[200]	train-aucpr:0.92865	validation-aucpr:0.40817
[0]	train-aucpr:0.54723	validation-aucpr:0.02647
[100]	train-aucpr:0.94186	validation-aucpr:0.41832
[200]	train-aucpr:0.94644	validation-aucpr:0.52050
[300]	train-aucpr:0.92834	validation-aucpr:0.40861
[218]	train-aucpr:0.94608	validation-aucpr:0.51823
[200]	train-aucpr:0.94062	validation-aucpr:0.39219
[204]	train-aucpr:0.94105	validation-aucpr:0.39428
[0]	train-aucpr:0.51524	validation-aucpr:0.03370
[100]	train-aucpr:0.93850	validation-aucpr:0.13897
[400]	train-aucpr:0.93213	validation-aucpr:0.40649
[420]	train-aucpr:0.93224	validation-aucpr:0.40649
[0]	train-aucpr:0.56558	validation-aucpr:0.03155
[200]	train-aucpr:0.93778	validation-aucpr:0.14127
[100]	train-aucpr:0.94676	validation-aucpr:0.24656
[100]	train-aucpr:0.92526	validation-aucpr:0.26290
[300]	train-aucpr:0.93831	validation-aucpr:0.16872
[200]	train-aucpr:0.94593	validation-aucpr:0.25223

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1384.10it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1526.77it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1441.99it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1364.03it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1514.72it/s]
Bootstrapping pr_auc:  14%|█▍        | 144/1000 [00:00<00:00, 1433.99it/s]

[200]	train-aucpr:0.92209	validation-aucpr:0.29721
[400]	train-aucpr:0.94068	validation-aucpr:0.16796
[0]	train-aucpr:0.56447	validation-aucpr:0.02959
[300]	train-aucpr:0.94391	validation-aucpr:0.26867
[300]	train-aucpr:0.92688	validation-aucpr:0.33958
[500]	train-aucpr:0.94370	validation-aucpr:0.17149
[100]	train-aucpr:0.89636	validation-aucpr:0.59749
[400]	train-aucpr:0.94485	validation-aucpr:0.26613
[400]	train-aucpr:0.92641	validation-aucpr:0.34060
[0]	train-aucpr:0.57372	validation-aucpr:0.02325
[600]	train-aucpr:0.94388	validation-aucpr:0.17195
[200]	train-aucpr:0.89735	validation-aucpr:0.62983
[204]	train-aucpr:0.89735	validation-aucpr:0.62983
[499]	train-aucpr:0.94590	validation-aucpr:0.25830
[0]	train-aucpr:0.52454	validation-aucpr:0.03155
[500]	train-aucpr:0.92810	validation-aucpr:0.38851
[700]	train-aucpr:0.94392	validation-aucpr:0.17055
[100]	train-aucpr:0.94564	validation-aucpr:0.28948
[774]	train-aucpr:0.94464	validation-aucpr:0.17144
[100]	train-aucpr:0.91226	validation-aucpr:0.61991
[600]	train-aucpr:0.92951	validation-aucpr:0.38563
[200]	train-aucpr:0.94739	validation-aucpr:0.22019
[222]	train-aucpr:0.94797	validation-aucpr:0.19973
[0]	train-aucpr:0.56141	validation-aucpr:0.03009
[700]	train-aucpr:0.93029	validation-aucpr:0.38546
[738]	train-aucpr:0.93047	validation-aucpr:0.38273

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1212.95it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1231.77it/s]

[200]	train-aucpr:0.91262	validation-aucpr:0.74761
[100]	train-aucpr:0.92665	validation-aucpr:0.36302
[0]	train-aucpr:0.55093	validation-aucpr:0.02731
[300]	train-aucpr:0.91555	validation-aucpr:0.74791
[200]	train-aucpr:0.92849	validation-aucpr:0.35708
[232]	train-aucpr:0.92841	validation-aucpr:0.35708
[349]	train-aucpr:0.91754	validation-aucpr:0.74781
[100]	train-aucpr:0.93320	validation-aucpr:0.27040
[0]	train-aucpr:0.53050	validation-aucpr:0.03575
[200]	train-aucpr:0.93452	validation-aucpr:0.27082
[248]	train-aucpr:0.93508	validation-aucpr:0.27082
[100]	train-aucpr:0.92613	validation-aucpr:0.24509
[0]	train-aucpr:0.52690	validation-aucpr:0.02753
[100]	train-aucpr:0.92470	validation-aucpr:0.34949
[200]	train-aucpr:0.92100	validation-aucpr:0.25041
[204]	train-aucpr:0.92110	validation-aucpr:0.25188

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1320.08it/s]
Bootstrapping pr_auc:  23%|██▎       | 232/1000 [00:00<00:00, 1169.28it/s]

[200]	train-aucpr:0.92520	validation-aucpr:0.35704
[0]	train-aucpr:0.51070	validation-aucpr:0.04176
[300]	train-aucpr:0.92773	validation-aucpr:0.35761
[318]	train-aucpr:0.93160	validation-aucpr:0.35715
[100]	train-aucpr:0.89698	validation-aucpr:0.36908
[200]	train-aucpr:0.90120	validation-aucpr:0.37987
[204]	train-aucpr:0.90248	validation-aucpr:0.37987

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1466.93it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1175.89it/s]
Bootstrapping pr_auc:   8%|▊         | 78/1000 [00:00<00:01, 754.50it/s]s]

[0]	train-aucpr:0.52618	validation-aucpr:0.04113
[0]	train-aucpr:0.55687	validation-aucpr:0.03202
[100]	train-aucpr:0.92116	validation-aucpr:0.34923
[100]	train-aucpr:0.90593	validation-aucpr:0.83088
[200]	train-aucpr:0.92040	validation-aucpr:0.36192
[204]	train-aucpr:0.92057	validation-aucpr:0.36192
[0]	train-aucpr:0.51307	validation-aucpr:0.03385
[200]	train-aucpr:0.90552	validation-aucpr:0.84184
[100]	train-aucpr:0.92890	validation-aucpr:0.11928
[300]	train-aucpr:0.90535	validation-aucpr:0.84184

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1214.64it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1147.25it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1380.03it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1403.51it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1244.17it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1421.86it/s]

[370]	train-aucpr:0.90994	validation-aucpr:0.82875
[200]	train-aucpr:0.92816	validation-aucpr:0.16626
[204]	train-aucpr:0.92971	validation-aucpr:0.14844
[0]	train-aucpr:0.54214	validation-aucpr:0.02742
[0]	train-aucpr:0.52333	validation-aucpr:0.01720
[100]	train-aucpr:0.93255	validation-aucpr:0.49814
[0]	train-aucpr:0.56197	validation-aucpr:0.03477
[100]	train-aucpr:0.89625	validation-aucpr:0.23058
[200]	train-aucpr:0.93151	validation-aucpr:0.50040
[210]	train-aucpr:0.93059	validation-aucpr:0.49862
[200]	train-aucpr:0.89632	validation-aucpr:0.21052
[100]	train-aucpr:0.91780	validation-aucpr:0.51500

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1298.05it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1377.46it/s]
Bootstrapping pr_auc:  66%|██████▌   | 657/1000 [00:00<00:00, 1160.03it/s]

[0]	train-aucpr:0.54499	validation-aucpr:0.03242
[200]	train-aucpr:0.91864	validation-aucpr:0.48783
[219]	train-aucpr:0.89685	validation-aucpr:0.20196
[271]	train-aucpr:0.91998	validation-aucpr:0.49172
[100]	train-aucpr:0.91413	validation-aucpr:0.58993
[0]	train-aucpr:0.51480	validation-aucpr:0.03446
[200]	train-aucpr:0.91577	validation-aucpr:0.57286
[100]	train-aucpr:0.92718	validation-aucpr:0.29712
[0]	train-aucpr:0.53709	validation-aucpr:0.02657
[300]	train-aucpr:0.91507	validation-aucpr:0.58449
[306]	train-aucpr:0.91534	validation-aucpr:0.58449
[200]	train-aucpr:0.92292	validation-aucpr:0.33736
[100]	train-aucpr:0.92012	validation-aucpr:0.26950
[0]	train-aucpr:0.59897	validation-aucpr:0.02779
[200]	train-aucpr:0.91946	validation-aucpr:0.27523
[209]	train-aucpr:0.91956	validation-aucpr:0.27523
[300]	train-aucpr:0.92211	validation-aucpr:0.34192
[0]	train-aucpr:0.56836	validation-aucpr:0.02657
[100]	train-aucpr:0.93505	validation-aucpr:0.21110

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1121.98it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1117.95it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1248.95it/s]
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]1415.52it/s]

[400]	train-aucpr:0.92376	validation-aucpr:0.33935
[0]	train-aucpr:0.56487	validation-aucpr:0.03644
[200]	train-aucpr:0.93783	validation-aucpr:0.19304
[211]	train-aucpr:0.93727	validation-aucpr:0.19410
[100]	train-aucpr:0.94449	validation-aucpr:0.12801
[500]	train-aucpr:0.92523	validation-aucpr:0.34023
[100]	train-aucpr:0.95733	validation-aucpr:0.20581
[200]	train-aucpr:0.94258	validation-aucpr:0.11451
[219]	train-aucpr:0.94442	validation-aucpr:0.12748
[600]	train-aucpr:0.92596	validation-aucpr:0.34506
[200]	train-aucpr:0.95732	validation-aucpr:0.20567
[229]	train-aucpr:0.95707	validation-aucpr:0.20567
[700]	train-aucpr:0.92346	validation-aucpr:0.37197
[0]	train-aucpr:0.52663	validation-aucpr:0.04497
[0]	train-aucpr:0.55743	validation-aucpr:0.03936
[800]	train-aucpr:0.92794	validation-aucpr:0.45747
[100]	train-aucpr:0.91806	validation-aucpr:0.30485

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1072.85it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1246.78it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1571.51it/s]
Bootstrapping pr_auc:  27%|██▋       | 270/1000 [00:00<00:00, 1218.22it/s]

[100]	train-aucpr:0.90934	validation-aucpr:0.74250
[900]	train-aucpr:0.92973	validation-aucpr:0.48453
[0]	train-aucpr:0.50635	validation-aucpr:0.04093
[200]	train-aucpr:0.92019	validation-aucpr:0.31236
[209]	train-aucpr:0.92058	validation-aucpr:0.30057
[200]	train-aucpr:0.91189	validation-aucpr:0.74250
[228]	train-aucpr:0.91276	validation-aucpr:0.74250
[999]	train-aucpr:0.93135	validation-aucpr:0.48656
[100]	train-aucpr:0.88791	validation-aucpr:0.50602
[0]	train-aucpr:0.56007	validation-aucpr:0.03009
[200]	train-aucpr:0.88861	validation-aucpr:0.48536
[100]	train-aucpr:0.94120	validation-aucpr:0.28226
[300]	train-aucpr:0.88672	validation-aucpr:0.49116
[200]	train-aucpr:0.94109	validation-aucpr:0.28419
[204]	train-aucpr:0.94107	validation-aucpr:0.28419
[400]	train-aucpr:0.89308	validation-aucpr:0.53340
[0]	train-aucpr:0.58304	validation-aucpr:0.04197
[500]	train-aucpr:0.89618	validation-aucpr:0.48041

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1183.61it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1604.19it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1192.91it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1489.13it/s]
Bootstrapping pr_auc:  84%|████████▍ | 844/1000 [00:00<00:00, 1244.21it/s]

[525]	train-aucpr:0.89640	validation-aucpr:0.48041
[100]	train-aucpr:0.94234	validation-aucpr:0.42910
[0]	train-aucpr:0.59480	validation-aucpr:0.02374
[200]	train-aucpr:0.94355	validation-aucpr:0.41977
[219]	train-aucpr:0.94277	validation-aucpr:0.42669
[100]	train-aucpr:0.92041	validation-aucpr:0.31319
[0]	train-aucpr:0.53938	validation-aucpr:0.03073
[200]	train-aucpr:0.92177	validation-aucpr:0.36563
[100]	train-aucpr:0.95339	validation-aucpr:0.33702[300]	train-aucpr:0.92192	validation-aucpr:0.36563

[328]	train-aucpr:0.92177	validation-aucpr:0.36603
[0]	train-aucpr:0.57981	validation-aucpr:0.02513
[200]	train-aucpr:0.95483	validation-aucpr:0.33646
[206]	train-aucpr:0.95483	validation-aucpr:0.33646
[100]	train-aucpr:0.94787	validation-aucpr:0.13635

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1238.86it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1323.65it/s]
Bootstrapping pr_auc:  33%|███▎      | 330/1000 [00:00<00:00, 1350.28it/s]

[200]	train-aucpr:0.94767	validation-aucpr:0.11149
[289]	train-aucpr:0.94918	validation-aucpr:0.11067
[0]	train-aucpr:0.57956	validation-aucpr:0.02616
[100]	train-aucpr:0.94922	validation-aucpr:0.13523
[200]	train-aucpr:0.94732	validation-aucpr:0.13845
[0]	train-aucpr:0.52676	validation-aucpr:0.02310
[300]	train-aucpr:0.94650	validation-aucpr:0.14044
[0]	train-aucpr:0.55642	validation-aucpr:0.03542
[100]	train-aucpr:0.94503	validation-aucpr:0.14508
[400]	train-aucpr:0.94679	validation-aucpr:0.14007
[100]	train-aucpr:0.92057	validation-aucpr:0.51235
[200]	train-aucpr:0.94240	validation-aucpr:0.16322
[204]	train-aucpr:0.94208	validation-aucpr:0.15620

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1241.00it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1269.32it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1307.43it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1363.92it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1617.49it/s]
Bootstrapping pr_auc:  84%|████████▎ | 837/1000 [00:00<00:00, 1309.76it/s]

[500]	train-aucpr:0.95225	validation-aucpr:0.13197
[0]	train-aucpr:0.53434	validation-aucpr:0.03662
[200]	train-aucpr:0.91890	validation-aucpr:0.54370
[600]	train-aucpr:0.95258	validation-aucpr:0.13268
[602]	train-aucpr:0.95259	validation-aucpr:0.13268
[0]	train-aucpr:0.54542	validation-aucpr:0.03918
[300]	train-aucpr:0.91836	validation-aucpr:0.54370
[100]	train-aucpr:0.92566	validation-aucpr:0.39040
[100]	train-aucpr:0.92983	validation-aucpr:0.28135
[400]	train-aucpr:0.91978	validation-aucpr:0.54370
[0]	train-aucpr:0.52599	validation-aucpr:0.04033
[200]	train-aucpr:0.93058	validation-aucpr:0.29620[500]	train-aucpr:0.92155	validation-aucpr:0.52476
[501]	train-aucpr:0.92155	validation-aucpr:0.52476
[200]	train-aucpr:0.92488	validation-aucpr:0.39830

[205]	train-aucpr:0.92982	validation-aucpr:0.29882
[0]	train-aucpr:0.52378	validation-aucpr:0.03430
[100]	train-aucpr:0.88828	validation-aucpr:0.48040
[300]	train-aucpr:0.92406	validation-aucpr:0.39093
[200]	train-aucpr:0.89364	validation-aucpr:0.56910
[204]	train-aucpr:0.89429	validation-aucpr:0.57083
[100]	train-aucpr:0.91869	validation-aucpr:0.28318
[385]	train-aucpr:0.92544	validation-aucpr:0.39491

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1366.93it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1272.31it/s]
Bootstrapping pr_auc:  92%|█████████▏| 923/1000 [00:00<00:00, 1336.70it/s]

[200]	train-aucpr:0.92183	validation-aucpr:0.27497
[0]	train-aucpr:0.53155	validation-aucpr:0.03609
[300]	train-aucpr:0.92151	validation-aucpr:0.27408
[315]	train-aucpr:0.92206	validation-aucpr:0.27408
[100]	train-aucpr:0.95200	validation-aucpr:0.34606
[200]	train-aucpr:0.95146	validation-aucpr:0.37781
[0]	train-aucpr:0.51733	validation-aucpr:0.03326
[300]	train-aucpr:0.95052	validation-aucpr:0.38423
[100]	train-aucpr:0.92226	validation-aucpr:0.21663
[0]	train-aucpr:0.57055	validation-aucpr:0.03326
[400]	train-aucpr:0.95184	validation-aucpr:0.37628
[420]	train-aucpr:0.95186	validation-aucpr:0.37630
[200]	train-aucpr:0.91974	validation-aucpr:0.21675

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1250.28it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1392.51it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1370.24it/s]
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]1315.08it/s]

[209]	train-aucpr:0.91913	validation-aucpr:0.21398
[100]	train-aucpr:0.93601	validation-aucpr:0.35603
[0]	train-aucpr:0.57372	validation-aucpr:0.02971
[200]	train-aucpr:0.93566	validation-aucpr:0.38720
[100]	train-aucpr:0.92955	validation-aucpr:0.44894
[0]	train-aucpr:0.53572	validation-aucpr:0.02408
[300]	train-aucpr:0.93554	validation-aucpr:0.38273
[200]	train-aucpr:0.92958	validation-aucpr:0.42429
[100]	train-aucpr:0.92295	validation-aucpr:0.27112
[400]	train-aucpr:0.93647	validation-aucpr:0.38052
[289]	train-aucpr:0.93377	validation-aucpr:0.42467
[0]	train-aucpr:0.53202	validation-aucpr:0.02657
[490]	train-aucpr:0.94228	validation-aucpr:0.35912
[200]	train-aucpr:0.92277	validation-aucpr:0.26857
[100]	train-aucpr:0.92669	validation-aucpr:0.35982
[261]	train-aucpr:0.92330	validation-aucpr:0.26897

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1310.22it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1262.63it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1323.79it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1647.58it/s]
Bootstrapping pr_auc:  26%|██▌       | 257/1000 [00:00<00:00, 1241.62it/s]

[0]	train-aucpr:0.50232	validation-aucpr:0.02374
[200]	train-aucpr:0.92727	validation-aucpr:0.38090
[209]	train-aucpr:0.92745	validation-aucpr:0.36650
[100]	train-aucpr:0.90886	validation-aucpr:0.22313
[200]	train-aucpr:0.91012	validation-aucpr:0.23165
[206]	train-aucpr:0.91012	validation-aucpr:0.23165
[0]	train-aucpr:0.56007	validation-aucpr:0.03697
[100]	train-aucpr:0.95023	validation-aucpr:0.25922
[0]	train-aucpr:0.50203	validation-aucpr:0.03592
[200]	train-aucpr:0.95089	validation-aucpr:0.26664
[204]	train-aucpr:0.95094	validation-aucpr:0.26664
[0]	train-aucpr:0.55389	validation-aucpr:0.04033
[100]	train-aucpr:0.91227	validation-aucpr:0.24823

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1269.38it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1242.13it/s]

[200]	train-aucpr:0.91053	validation-aucpr:0.23893
[204]	train-aucpr:0.91053	validation-aucpr:0.23893
[100]	train-aucpr:0.93280	validation-aucpr:0.49804
[200]	train-aucpr:0.93065	validation-aucpr:0.49684
[226]	train-aucpr:0.93097	validation-aucpr:0.50213
[0]	train-aucpr:0.54331	validation-aucpr:0.03326

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1103.49it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1230.56it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1138.29it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1224.46it/s]
Bootstrapping pr_auc:  82%|████████▏ | 821/1000 [00:00<00:00, 1067.95it/s]

[0]	train-aucpr:0.54805	validation-aucpr:0.02626
[100]	train-aucpr:0.93197	validation-aucpr:0.25928
[0]	train-aucpr:0.53631	validation-aucpr:0.02587
[100]	train-aucpr:0.93243	validation-aucpr:0.18530
[200]	train-aucpr:0.93289	validation-aucpr:0.18427
[204]	train-aucpr:0.93302	validation-aucpr:0.18463
[200]	train-aucpr:0.93070	validation-aucpr:0.22522
[209]	train-aucpr:0.93052	validation-aucpr:0.21513
[0]	train-aucpr:0.57356	validation-aucpr:0.03141
[100]	train-aucpr:0.90856	validation-aucpr:0.17185
[0]	train-aucpr:0.51733	validation-aucpr:0.03400
[100]	train-aucpr:0.92349	validation-aucpr:0.40681
[100]	train-aucpr:0.92237	validation-aucpr:0.39953
[200]	train-aucpr:0.90614	validation-aucpr:0.17791
[200]	train-aucpr:0.93252	validation-aucpr:0.44184
[204]	train-aucpr:0.93192	validation-aucpr:0.44184
[251]	train-aucpr:0.90657	validation-aucpr:0.17592
[200]	train-aucpr:0.92472	validation-aucpr:0.41799
[204]	train-aucpr:0.92481	validation-aucpr:0.40681

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1249.22it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1151.63it/s]
Bootstrapping pr_auc:  63%|██████▎   | 627/1000 [00:00<00:00, 1120.05it/s]

[0]	train-aucpr:0.58713	validation-aucpr:0.03169
[100]	train-aucpr:0.95353	validation-aucpr:0.12102
[200]	train-aucpr:0.95391	validation-aucpr:0.12009
[211]	train-aucpr:0.95288	validation-aucpr:0.11530
[0]	train-aucpr:0.54071	validation-aucpr:0.03526
[100]	train-aucpr:0.91506	validation-aucpr:0.61113
[0]	train-aucpr:0.55999	validation-aucpr:0.02947

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1230.61it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1097.44it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1210.50it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1535.02it/s]
Bootstrapping pr_auc:  84%|████████▍ | 840/1000 [00:00<00:00, 1309.01it/s]

[200]	train-aucpr:0.91634	validation-aucpr:0.66840
[100]	train-aucpr:0.91202	validation-aucpr:0.31495
[300]	train-aucpr:0.91699	validation-aucpr:0.66254
[0]	train-aucpr:0.59373	validation-aucpr:0.04033
[200]	train-aucpr:0.91245	validation-aucpr:0.31596
[0]	train-aucpr:0.52823	validation-aucpr:0.03461
[400]	train-aucpr:0.91963	validation-aucpr:0.66422
[276]	train-aucpr:0.91331	validation-aucpr:0.31427
[452]	train-aucpr:0.91922	validation-aucpr:0.65866
[100]	train-aucpr:0.92489	validation-aucpr:0.54660
[100]	train-aucpr:0.89300	validation-aucpr:0.35502
[0]	train-aucpr:0.55591	validation-aucpr:0.03155
[200]	train-aucpr:0.92316	validation-aucpr:0.52153
[204]	train-aucpr:0.92318	validation-aucpr:0.52153
[100]	train-aucpr:0.95580	validation-aucpr:0.20504
[0]	train-aucpr:0.57430	validation-aucpr:0.02667
[200]	train-aucpr:0.89432	validation-aucpr:0.34708
[200]	train-aucpr:0.95310	validation-aucpr:0.20054
[204]	train-aucpr:0.95332	validation-aucpr:0.20054
[0]	train-aucpr:0.54650	validation-aucpr:0.03183
[0]	train-aucpr:0.55065	validation-aucpr:0.03644
[300]	train-aucpr:0.89658	validation-aucpr:0.37831
[100]	train-aucpr:0.91300	validation-aucpr:0.35858
[100]	train-aucpr:0.90289	validation-aucpr:0.48881

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1093.89it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1127.52it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1309.88it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1328.23it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1577.71it/s]
Bootstrapping pr_auc:  15%|█▌        | 152/1000 [00:00<00:00, 1514.62it/s]

[200]	train-aucpr:0.91089	validation-aucpr:0.35435
[200]	train-aucpr:0.90193	validation-aucpr:0.49106
[100]	train-aucpr:0.95714	validation-aucpr:0.31877
[0]	train-aucpr:0.57260	validation-aucpr:0.03198
[400]	train-aucpr:0.89972	validation-aucpr:0.38135
[300]	train-aucpr:0.90343	validation-aucpr:0.47895
[200]	train-aucpr:0.95687	validation-aucpr:0.31144
[300]	train-aucpr:0.91106	validation-aucpr:0.34931
[0]	train-aucpr:0.58415	validation-aucpr:0.03021
[238]	train-aucpr:0.95685	validation-aucpr:0.31144
[450]	train-aucpr:0.90084	validation-aucpr:0.38204
[400]	train-aucpr:0.90464	validation-aucpr:0.49552
[100]	train-aucpr:0.92130	validation-aucpr:0.41665
[400]	train-aucpr:0.91745	validation-aucpr:0.39390
[500]	train-aucpr:0.90486	validation-aucpr:0.48354
[100]	train-aucpr:0.92784	validation-aucpr:0.37425
[527]	train-aucpr:0.90502	validation-aucpr:0.48757
[500]	train-aucpr:0.91782	validation-aucpr:0.39497
[200]	train-aucpr:0.92248	validation-aucpr:0.42378
[206]	train-aucpr:0.92298	validation-aucpr:0.40646
[200]	train-aucpr:0.93036	validation-aucpr:0.35669
[218]	train-aucpr:0.92847	validation-aucpr:0.35390
[600]	train-aucpr:0.91824	validation-aucpr:0.40489
[700]	train-aucpr:0.91906	validation-aucpr:0.39838

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1186.13it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1282.34it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1238.77it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1305.97it/s]
Bootstrapping pr_auc:  72%|███████▎  | 725/1000 [00:00<00:00, 1385.95it/s]

[800]	train-aucpr:0.91942	validation-aucpr:0.40389
[821]	train-aucpr:0.91936	validation-aucpr:0.40274
[0]	train-aucpr:0.50911	validation-aucpr:0.04052
[100]	train-aucpr:0.90924	validation-aucpr:0.34841
[200]	train-aucpr:0.91326	validation-aucpr:0.32581
[204]	train-aucpr:0.91341	validation-aucpr:0.32581

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1018.13it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1378.07it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1336.70it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1308.74it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1294.62it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1534.48it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1424.87it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1405.47it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1390.05it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1406.53it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1533.31it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1630.76it/s]

bound         Metrics  estimate    lower     upper                     models
0         AUPRC_value   43.5403  24.7038   64.8809  XGBoost (VL diag & SMOTE)
1         AUROC_value   92.8433  84.2551   98.2773  XGBoost (VL diag & SMOTE)
2            Accuracy   89.8429  84.7356   93.6556  XGBoost (VL diag & SMOTE)
3      Accuracy_train   86.3126  81.7952   91.4901  XGBoost (VL diag & SMOTE)
4                 NPV   99.3111  98.6506  100.0000  XGBoost (VL diag & SMOTE)
5           Precision   20.8185  14.0774   30.5478  XGBoost (VL diag & SMOTE)
6         Sensitivity   79.8000  60.0000  100.0000  XGBoost (VL diag & SMOTE)
7         Specificity   90.1558  84.8676   94.0966  XGBoost (VL diag & SMOTE)

## Fitting data list with VL at diagnosis & VL at 1-day after diagnosis

In [7]:
xgb_add1_list = model_func_xgb_tune(split_list_diag1_valid_smote_final)
xgb_add1_met_summary = sum_metric(xgb_add1_list)
xgb_add1_metrics_summary = xgb_add1_met_summary["metric_summary"]
xgb_add1_summary = met_collate_func(xgb_add1_metrics_summary).assign(
    models = "XGBoost (VL diag + 1 & SMOTE)"
)
xgb_add1_summary

/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:48] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:48] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:48] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:48] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:48] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:48] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:48] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:48] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:48] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:48] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:48] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:48] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:48] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:48] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:48] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:48] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:48] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:48] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:48] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:48] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:48] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:48] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:48] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:48] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:48] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:48] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:48] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:48] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:48] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:48] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

[0]	train-aucpr:0.54305	validation-aucpr:0.04013
[0]	train-aucpr:0.52476	validation-aucpr:0.03936
[0]	train-aucpr:0.51998	validation-aucpr:0.03169
[0]	train-aucpr:0.53639	validation-aucpr:0.03127
[0]	train-aucpr:0.54628	validation-aucpr:0.03734
[100]	train-aucpr:0.90460	validation-aucpr:0.38568
[100]	train-aucpr:0.90632	validation-aucpr:0.54510
[0]	train-aucpr:0.54171	validation-aucpr:0.03141
[100]	train-aucpr:0.92694	validation-aucpr:0.60456
[100]	train-aucpr:0.93936	validation-aucpr:0.35165
[100]	train-aucpr:0.95322	validation-aucpr:0.18642
[200]	train-aucpr:0.90942	validation-aucpr:0.39777
[0]	train-aucpr:0.57182	validation-aucpr:0.03021
[200]	train-aucpr:0.91296	validation-aucpr:0.57822
[100]	train-aucpr:0.93838	validation-aucpr:0.36408
[0]	train-aucpr:0.57580	validation-aucpr:0.03009
[200]	train-aucpr:0.93531	validation-aucpr:0.59167
[200]	train-aucpr:0.94332	validation-aucpr:0.35745
[200]	train-aucpr:0.95561	validation-aucpr:0.19708
[242]	train-aucpr:0.94073	validation-aucpr:0.36161
[252]	train-aucpr:0.93362	validation-aucpr:0.59732
[300]	train-aucpr:0.91104	validation-aucpr:0.39863
[100]	train-aucpr:0.94454	validation-aucpr:0.19348
[0]	train-aucpr:0.56935	validation-aucpr:0.04865
[300]	train-aucpr:0.91432	validation-aucpr:0.57542
[100]	train-aucpr:0.93165	validation-aucpr:0.18592
[200]	train-aucpr:0.94217	validation-aucpr:0.32498
[0]	train-aucpr:0.52290	validation-aucpr:0.03592
[300]	train-aucpr:0.95500	validation-aucpr:0.19871
[0]	train-aucpr:0.51440	validation-aucpr:0.03697
[400]	train-aucpr:0.91391	validation-aucpr:0.39672
[100]	train-aucpr:0.95513	validation-aucpr:0.32015
[200]	train-aucpr:0.94470	validation-aucpr:0.16823
[390]	train-aucpr:0.92365	validation-aucpr:0.57662
[270]	train-aucpr:0.94259	validation-aucpr:0.32740
[0]	train-aucpr:0.55870	validation-aucpr:0.04176
[200]	train-aucpr:0.93515	validation-aucpr:0.21254
[354]	train-aucpr:0.95499	validation-aucpr:0.19376
[0]	train-aucpr:0.57115	validation-aucpr:0.02235
[100]	train-aucpr:0.94106	validation-aucpr:0.25688
[482]	train-aucpr:0.91389	validation-aucpr:0.39832
[100]	train-aucpr:0.91775	validation-aucpr:0.39620
[200]	train-aucpr:0.95752	validation-aucpr:0.30975
[300]	train-aucpr:0.94487	validation-aucpr:0.16807
[0]	train-aucpr:0.54920	validation-aucpr:0.02984
[0]	train-aucpr:0.56957	validation-aucpr:0.02647
[100]	train-aucpr:0.92168	validation-aucpr:0.49300
[324]	train-aucpr:0.94506	validation-aucpr:0.17114
[300]	train-aucpr:0.93761	validation-aucpr:0.22368
[100]	train-aucpr:0.91627	validation-aucpr:0.24152
[200]	train-aucpr:0.94443	validation-aucpr:0.25398
[345]	train-aucpr:0.93907	validation-aucpr:0.22357
[300]	train-aucpr:0.95671	validation-aucpr:0.30774
[200]	train-aucpr:0.92567	validation-aucpr:0.39013
[100]	train-aucpr:0.92145	validation-aucpr:0.32923
[100]	train-aucpr:0.91574	validation-aucpr:0.47440
[200]	train-aucpr:0.92439	validation-aucpr:0.49371

Bootstrapping pr_auc:  16%|█▌        | 155/1000 [00:00<00:00, 1544.98it/s]

[200]	train-aucpr:0.92004	validation-aucpr:0.21576
[300]	train-aucpr:0.94518	validation-aucpr:0.25398
[345]	train-aucpr:0.94599	validation-aucpr:0.25027
[300]	train-aucpr:0.92956	validation-aucpr:0.37344
[302]	train-aucpr:0.92964	validation-aucpr:0.37344
[200]	train-aucpr:0.92384	validation-aucpr:0.32855
[300]	train-aucpr:0.92549	validation-aucpr:0.48902
[200]	train-aucpr:0.92204	validation-aucpr:0.47490
[300]	train-aucpr:0.92321	validation-aucpr:0.22060
[302]	train-aucpr:0.92318	validation-aucpr:0.22004
[300]	train-aucpr:0.92340	validation-aucpr:0.32849
[300]	train-aucpr:0.92326	validation-aucpr:0.45852
[400]	train-aucpr:0.92973	validation-aucpr:0.48789
[430]	train-aucpr:0.92929	validation-aucpr:0.48752
[353]	train-aucpr:0.92565	validation-aucpr:0.34242
[360]	train-aucpr:0.92563	validation-aucpr:0.46370

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1629.69it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1592.82it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1604.48it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1535.65it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1503.44it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1482.57it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1604.11it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1536.76it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1604.58it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1476.04it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1611.59it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1493.43it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1439.72it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1486.55it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1393.21it/s]

[0]	train-aucpr:0.58121	validation-aucpr:0.03047
[100]	train-aucpr:0.94862	validation-aucpr:0.42538
[200]	train-aucpr:0.94817	validation-aucpr:0.44139
[0]	train-aucpr:0.57678	validation-aucpr:0.02647
[300]	train-aucpr:0.94886	validation-aucpr:0.41334
[0]	train-aucpr:0.56698	validation-aucpr:0.02688
[352]	train-aucpr:0.95001	validation-aucpr:0.41860
[100]	train-aucpr:0.92494	validation-aucpr:0.31958
[100]	train-aucpr:0.93761	validation-aucpr:0.34821
[0]	train-aucpr:0.52542	validation-aucpr:0.03141
[0]	train-aucpr:0.54291	validation-aucpr:0.03477
[200]	train-aucpr:0.92754	validation-aucpr:0.32003
[200]	train-aucpr:0.94009	validation-aucpr:0.36405
[100]	train-aucpr:0.93402	validation-aucpr:0.20545
[100]	train-aucpr:0.94964	validation-aucpr:0.26366
[0]	train-aucpr:0.53003	validation-aucpr:0.02540
[300]	train-aucpr:0.92714	validation-aucpr:0.31807
[300]	train-aucpr:0.94042	validation-aucpr:0.36514
[200]	train-aucpr:0.93633	validation-aucpr:0.20849
[340]	train-aucpr:0.92956	validation-aucpr:0.31039
[340]	train-aucpr:0.94064	validation-aucpr:0.37077
[200]	train-aucpr:0.95108	validation-aucpr:0.26334
[100]	train-aucpr:0.90818	validation-aucpr:0.47180
[0]	train-aucpr:0.53873	validation-aucpr:0.03526
[232]	train-aucpr:0.94832	validation-aucpr:0.26947
[300]	train-aucpr:0.93720	validation-aucpr:0.20066
[355]	train-aucpr:0.93813	validation-aucpr:0.21458
[0]	train-aucpr:0.54859	validation-aucpr:0.03198
[200]	train-aucpr:0.91180	validation-aucpr:0.51533
[100]	train-aucpr:0.92328	validation-aucpr:0.47827
[0]	train-aucpr:0.54972	validation-aucpr:0.02568
[300]	train-aucpr:0.91450	validation-aucpr:0.51565
[0]	train-aucpr:0.57174	validation-aucpr:0.02365
[100]	train-aucpr:0.92670	validation-aucpr:0.37550
[353]	train-aucpr:0.91563	validation-aucpr:0.49151
[0]	train-aucpr:0.57798	validation-aucpr:0.02947
[100]	train-aucpr:0.89659	validation-aucpr:0.70259
[100]	train-aucpr:0.90342	validation-aucpr:0.39146
[200]	train-aucpr:0.93019	validation-aucpr:0.48655
[200]	train-aucpr:0.92987	validation-aucpr:0.36228
[0]	train-aucpr:0.57338	validation-aucpr:0.02444
[100]	train-aucpr:0.91415	validation-aucpr:0.25837
[226]	train-aucpr:0.92911	validation-aucpr:0.46231
[200]	train-aucpr:0.89824	validation-aucpr:0.70211
[200]	train-aucpr:0.90602	validation-aucpr:0.39629
[200]	train-aucpr:0.91705	validation-aucpr:0.26417
[100]	train-aucpr:0.94397	validation-aucpr:0.25614
[300]	train-aucpr:0.93342	validation-aucpr:0.40696

Bootstrapping pr_auc:  31%|███▏      | 314/1000 [00:00<00:00, 1424.26it/s]

[0]	train-aucpr:0.52272	validation-aucpr:0.02578
[300]	train-aucpr:0.89835	validation-aucpr:0.67559
[300]	train-aucpr:0.90719	validation-aucpr:0.39293
[300]	train-aucpr:0.91762	validation-aucpr:0.35185
[0]	train-aucpr:0.54154	validation-aucpr:0.02607
[200]	train-aucpr:0.94664	validation-aucpr:0.25555
[400]	train-aucpr:0.93719	validation-aucpr:0.38503
[341]	train-aucpr:0.90844	validation-aucpr:0.38511
[381]	train-aucpr:0.90200	validation-aucpr:0.65492
[100]	train-aucpr:0.93410	validation-aucpr:0.35940
[230]	train-aucpr:0.94535	validation-aucpr:0.25703
[476]	train-aucpr:0.93670	validation-aucpr:0.37543
[400]	train-aucpr:0.92059	validation-aucpr:0.35810
[100]	train-aucpr:0.93411	validation-aucpr:0.17552
[200]	train-aucpr:0.94064	validation-aucpr:0.34696
[0]	train-aucpr:0.52366	validation-aucpr:0.02688
[200]	train-aucpr:0.93607	validation-aucpr:0.18054
[300]	train-aucpr:0.94050	validation-aucpr:0.32822
[100]	train-aucpr:0.93526	validation-aucpr:0.20610
[500]	train-aucpr:0.92125	validation-aucpr:0.35847
[353]	train-aucpr:0.94035	validation-aucpr:0.33697
[300]	train-aucpr:0.93598	validation-aucpr:0.17728
[200]	train-aucpr:0.94048	validation-aucpr:0.21136
[600]	train-aucpr:0.92491	validation-aucpr:0.35460
[235]	train-aucpr:0.93594	validation-aucpr:0.21103
[350]	train-aucpr:0.93726	validation-aucpr:0.18184
[698]	train-aucpr:0.92769	validation-aucpr:0.35561

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1524.41it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1514.37it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1418.77it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1434.68it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1475.61it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1509.50it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1506.79it/s]

[0]	train-aucpr:0.52943	validation-aucpr:0.04093
[100]	train-aucpr:0.89202	validation-aucpr:0.52057
[200]	train-aucpr:0.89811	validation-aucpr:0.59648
[0]	train-aucpr:0.55288	validation-aucpr:0.03034
[0]	train-aucpr:0.53932	validation-aucpr:0.04134
[300]	train-aucpr:0.90169	validation-aucpr:0.59202
[100]	train-aucpr:0.91985	validation-aucpr:0.39089
[100]	train-aucpr:0.92700	validation-aucpr:0.38881
[352]	train-aucpr:0.90382	validation-aucpr:0.58618
[0]	train-aucpr:0.59043	validation-aucpr:0.02677
[200]	train-aucpr:0.93015	validation-aucpr:0.38931
[0]	train-aucpr:0.58291	validation-aucpr:0.03169
[200]	train-aucpr:0.92158	validation-aucpr:0.42297

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1311.74it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1305.86it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1341.30it/s]
Bootstrapping pr_auc:  16%|█▌        | 161/1000 [00:00<00:00, 1608.19it/s]

[100]	train-aucpr:0.94402	validation-aucpr:0.55682
[300]	train-aucpr:0.93007	validation-aucpr:0.42371
[0]	train-aucpr:0.54723	validation-aucpr:0.02647
[100]	train-aucpr:0.94633	validation-aucpr:0.43956
[300]	train-aucpr:0.92207	validation-aucpr:0.40096
[400]	train-aucpr:0.93229	validation-aucpr:0.39934
[200]	train-aucpr:0.94647	validation-aucpr:0.55063
[425]	train-aucpr:0.93282	validation-aucpr:0.39942[0]	train-aucpr:0.51524	validation-aucpr:0.03370
[100]	train-aucpr:0.93914	validation-aucpr:0.18045
[355]	train-aucpr:0.92292	validation-aucpr:0.40166
[200]	train-aucpr:0.94685	validation-aucpr:0.42589

[100]	train-aucpr:0.94206	validation-aucpr:0.25798
[200]	train-aucpr:0.94437	validation-aucpr:0.17771
[300]	train-aucpr:0.94538	validation-aucpr:0.56058
[300]	train-aucpr:0.94662	validation-aucpr:0.42638
[250]	train-aucpr:0.94290	validation-aucpr:0.17879
[353]	train-aucpr:0.94529	validation-aucpr:0.56058
[313]	train-aucpr:0.94680	validation-aucpr:0.42644
[200]	train-aucpr:0.94523	validation-aucpr:0.25912
[300]	train-aucpr:0.94489	validation-aucpr:0.26670
[400]	train-aucpr:0.94782	validation-aucpr:0.28274

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1280.82it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1150.62it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1276.14it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1186.08it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1185.16it/s]
Bootstrapping pr_auc:  47%|████▋     | 470/1000 [00:00<00:00, 1564.39it/s]

[0]	train-aucpr:0.56558	validation-aucpr:0.03155
[500]	train-aucpr:0.94927	validation-aucpr:0.30131
[100]	train-aucpr:0.92219	validation-aucpr:0.29682
[0]	train-aucpr:0.56447	validation-aucpr:0.02959
[600]	train-aucpr:0.95178	validation-aucpr:0.29156
[200]	train-aucpr:0.92532	validation-aucpr:0.34944
[100]	train-aucpr:0.89496	validation-aucpr:0.66354
[0]	train-aucpr:0.57372	validation-aucpr:0.02325
[691]	train-aucpr:0.95174	validation-aucpr:0.30357
[0]	train-aucpr:0.52454	validation-aucpr:0.03155
[200]	train-aucpr:0.90018	validation-aucpr:0.67622
[300]	train-aucpr:0.92577	validation-aucpr:0.35089
[100]	train-aucpr:0.93870	validation-aucpr:0.31531
[100]	train-aucpr:0.90459	validation-aucpr:0.62608
[300]	train-aucpr:0.90273	validation-aucpr:0.66489
[340]	train-aucpr:0.90363	validation-aucpr:0.65847
[0]	train-aucpr:0.56141	validation-aucpr:0.03009
[200]	train-aucpr:0.94153	validation-aucpr:0.24949
[400]	train-aucpr:0.92837	validation-aucpr:0.35414
[200]	train-aucpr:0.90928	validation-aucpr:0.70965
[100]	train-aucpr:0.93034	validation-aucpr:0.28948
[0]	train-aucpr:0.55093	validation-aucpr:0.02731
[300]	train-aucpr:0.94271	validation-aucpr:0.25365
[307]	train-aucpr:0.94225	validation-aucpr:0.25132
[500]	train-aucpr:0.93003	validation-aucpr:0.40474
[300]	train-aucpr:0.91070	validation-aucpr:0.69968
[345]	train-aucpr:0.91607	validation-aucpr:0.70374
[100]	train-aucpr:0.93263	validation-aucpr:0.31797
[200]	train-aucpr:0.93235	validation-aucpr:0.29471
[600]	train-aucpr:0.93379	validation-aucpr:0.39619
[0]	train-aucpr:0.53050	validation-aucpr:0.03575
[200]	train-aucpr:0.93687	validation-aucpr:0.32684
[669]	train-aucpr:0.93483	validation-aucpr:0.37467
[100]	train-aucpr:0.92365	validation-aucpr:0.22261
[0]	train-aucpr:0.52690	validation-aucpr:0.02753
[300]	train-aucpr:0.93759	validation-aucpr:0.32872
[300]	train-aucpr:0.93250	validation-aucpr:0.30202
[353]	train-aucpr:0.93881	validation-aucpr:0.33065
[200]	train-aucpr:0.92739	validation-aucpr:0.23512
[100]	train-aucpr:0.91243	validation-aucpr:0.42612
[208]	train-aucpr:0.92530	validation-aucpr:0.23269
[400]	train-aucpr:0.93559	validation-aucpr:0.30811
[200]	train-aucpr:0.91723	validation-aucpr:0.40727
[500]	train-aucpr:0.93518	validation-aucpr:0.30708
[300]	train-aucpr:0.92484	validation-aucpr:0.40690
[307]	train-aucpr:0.92474	validation-aucpr:0.41622

Bootstrapping pr_auc:  25%|██▌       | 254/1000 [00:00<00:00, 1313.26it/s]

[600]	train-aucpr:0.93691	validation-aucpr:0.32156
[700]	train-aucpr:0.93579	validation-aucpr:0.31097
[788]	train-aucpr:0.93585	validation-aucpr:0.31123
[0]	train-aucpr:0.51070	validation-aucpr:0.04176
[0]	train-aucpr:0.52618	validation-aucpr:0.04113

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1315.48it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1491.17it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1442.96it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1492.61it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1402.22it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1190.67it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1546.24it/s]
Bootstrapping pr_auc:  74%|███████▍  | 738/1000 [00:00<00:00, 1385.01it/s]

[100]	train-aucpr:0.89660	validation-aucpr:0.36119
[0]	train-aucpr:0.55687	validation-aucpr:0.03202
[100]	train-aucpr:0.92374	validation-aucpr:0.34136
[200]	train-aucpr:0.90170	validation-aucpr:0.36782
[0]	train-aucpr:0.51307	validation-aucpr:0.03385
[200]	train-aucpr:0.92625	validation-aucpr:0.35303
[100]	train-aucpr:0.90964	validation-aucpr:0.79725
[100]	train-aucpr:0.93192	validation-aucpr:0.18528
[300]	train-aucpr:0.90169	validation-aucpr:0.34156
[300]	train-aucpr:0.92729	validation-aucpr:0.32757
[200]	train-aucpr:0.91224	validation-aucpr:0.80310
[353]	train-aucpr:0.92804	validation-aucpr:0.33903
[0]	train-aucpr:0.54214	validation-aucpr:0.02742
[200]	train-aucpr:0.93467	validation-aucpr:0.14307
[387]	train-aucpr:0.90465	validation-aucpr:0.34187
[100]	train-aucpr:0.92077	validation-aucpr:0.44989
[300]	train-aucpr:0.91297	validation-aucpr:0.81249
[0]	train-aucpr:0.52333	validation-aucpr:0.01720
[288]	train-aucpr:0.93481	validation-aucpr:0.14229
[400]	train-aucpr:0.91467	validation-aucpr:0.82813
[100]	train-aucpr:0.90182	validation-aucpr:0.19637
[500]	train-aucpr:0.91748	validation-aucpr:0.84385
[200]	train-aucpr:0.92595	validation-aucpr:0.46703
[200]	train-aucpr:0.90644	validation-aucpr:0.20592
[600]	train-aucpr:0.91936	validation-aucpr:0.84093
[300]	train-aucpr:0.93005	validation-aucpr:0.40159
[0]	train-aucpr:0.56197	validation-aucpr:0.03477
[664]	train-aucpr:0.91983	validation-aucpr:0.84714
[300]	train-aucpr:0.90579	validation-aucpr:0.20301
[353]	train-aucpr:0.91030	validation-aucpr:0.20882
[399]	train-aucpr:0.93364	validation-aucpr:0.40652
[100]	train-aucpr:0.92234	validation-aucpr:0.54780
[200]	train-aucpr:0.92498	validation-aucpr:0.54621
[0]	train-aucpr:0.54499	validation-aucpr:0.03242
[273]	train-aucpr:0.92530	validation-aucpr:0.54639

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1322.76it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1360.14it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1274.28it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1500.85it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1444.78it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1317.41it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1455.86it/s]
Bootstrapping pr_auc:  95%|█████████▌| 950/1000 [00:00<00:00, 1234.54it/s]

[0]	train-aucpr:0.51480	validation-aucpr:0.03446
[100]	train-aucpr:0.90934	validation-aucpr:0.55814
[0]	train-aucpr:0.53709	validation-aucpr:0.02657
[200]	train-aucpr:0.91449	validation-aucpr:0.57745
[100]	train-aucpr:0.91598	validation-aucpr:0.37817
[0]	train-aucpr:0.59897	validation-aucpr:0.02779
[200]	train-aucpr:0.91874	validation-aucpr:0.42374[300]	train-aucpr:0.91645	validation-aucpr:0.58096

[100]	train-aucpr:0.91679	validation-aucpr:0.32248
[0]	train-aucpr:0.56836	validation-aucpr:0.02657
[400]	train-aucpr:0.91912	validation-aucpr:0.58179
[100]	train-aucpr:0.92923	validation-aucpr:0.18485
[300]	train-aucpr:0.91949	validation-aucpr:0.41894
[462]	train-aucpr:0.92226	validation-aucpr:0.57785
[0]	train-aucpr:0.56487	validation-aucpr:0.03644
[100]	train-aucpr:0.93916	validation-aucpr:0.11717
[200]	train-aucpr:0.93578	validation-aucpr:0.19916
[400]	train-aucpr:0.92705	validation-aucpr:0.56929
[100]	train-aucpr:0.95220	validation-aucpr:0.24149
[200]	train-aucpr:0.92038	validation-aucpr:0.33014
[0]	train-aucpr:0.52663	validation-aucpr:0.04497
[300]	train-aucpr:0.93630	validation-aucpr:0.19763
[200]	train-aucpr:0.94326	validation-aucpr:0.11593

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1262.35it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1571.88it/s]

[500]	train-aucpr:0.92800	validation-aucpr:0.56977
[353]	train-aucpr:0.93943	validation-aucpr:0.20703
[200]	train-aucpr:0.95403	validation-aucpr:0.24389
[100]	train-aucpr:0.91503	validation-aucpr:0.34223
[300]	train-aucpr:0.94483	validation-aucpr:0.10927
[300]	train-aucpr:0.92013	validation-aucpr:0.32480
[334]	train-aucpr:0.94502	validation-aucpr:0.10690
[600]	train-aucpr:0.92960	validation-aucpr:0.57051
[200]	train-aucpr:0.91994	validation-aucpr:0.33725
[271]	train-aucpr:0.95482	validation-aucpr:0.23992
[400]	train-aucpr:0.92798	validation-aucpr:0.32084
[410]	train-aucpr:0.92787	validation-aucpr:0.32084
[700]	train-aucpr:0.92870	validation-aucpr:0.57104
[300]	train-aucpr:0.92620	validation-aucpr:0.40700
[800]	train-aucpr:0.93040	validation-aucpr:0.57104
[400]	train-aucpr:0.93188	validation-aucpr:0.40521
[900]	train-aucpr:0.93067	validation-aucpr:0.57210
[500]	train-aucpr:0.93393	validation-aucpr:0.40669
[917]	train-aucpr:0.93077	validation-aucpr:0.57303
[567]	train-aucpr:0.93614	validation-aucpr:0.40378

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1375.00it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1327.61it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1565.59it/s]
Bootstrapping pr_auc:  28%|██▊       | 278/1000 [00:00<00:00, 1333.83it/s]

[0]	train-aucpr:0.55743	validation-aucpr:0.03936
[100]	train-aucpr:0.90537	validation-aucpr:0.73340
[200]	train-aucpr:0.91034	validation-aucpr:0.75414
[0]	train-aucpr:0.50635	validation-aucpr:0.04093
[300]	train-aucpr:0.91108	validation-aucpr:0.75414
[306]	train-aucpr:0.91126	validation-aucpr:0.75414
[0]	train-aucpr:0.56007	validation-aucpr:0.03009
[100]	train-aucpr:0.88993	validation-aucpr:0.51197
[100]	train-aucpr:0.94857	validation-aucpr:0.20573
[200]	train-aucpr:0.89460	validation-aucpr:0.54101
[0]	train-aucpr:0.58304	validation-aucpr:0.04197
[200]	train-aucpr:0.94971	validation-aucpr:0.21481
[300]	train-aucpr:0.89733	validation-aucpr:0.48257
[353]	train-aucpr:0.89778	validation-aucpr:0.48430

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1350.18it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1370.45it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1327.31it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1481.11it/s]

[0]	train-aucpr:0.59480	validation-aucpr:0.02374
[300]	train-aucpr:0.95020	validation-aucpr:0.21495
[100]	train-aucpr:0.94935	validation-aucpr:0.46157
[352]	train-aucpr:0.95100	validation-aucpr:0.22498
[0]	train-aucpr:0.53938	validation-aucpr:0.03073
[100]	train-aucpr:0.92498	validation-aucpr:0.28654
[200]	train-aucpr:0.94940	validation-aucpr:0.47635
[100]	train-aucpr:0.95656	validation-aucpr:0.31033
[0]	train-aucpr:0.57981	validation-aucpr:0.02513
[300]	train-aucpr:0.94750	validation-aucpr:0.49545
[200]	train-aucpr:0.95885	validation-aucpr:0.30826
[200]	train-aucpr:0.92721	validation-aucpr:0.25461
[223]	train-aucpr:0.95694	validation-aucpr:0.31153
[0]	train-aucpr:0.57956	validation-aucpr:0.02616
[400]	train-aucpr:0.94961	validation-aucpr:0.49172
[100]	train-aucpr:0.95196	validation-aucpr:0.15944
[300]	train-aucpr:0.92740	validation-aucpr:0.26677
[415]	train-aucpr:0.94980	validation-aucpr:0.49907
[343]	train-aucpr:0.92754	validation-aucpr:0.26546
[200]	train-aucpr:0.95334	validation-aucpr:0.15201

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1272.37it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1323.20it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1315.52it/s]
Bootstrapping pr_auc:  28%|██▊       | 281/1000 [00:00<00:00, 1406.10it/s]

[300]	train-aucpr:0.95362	validation-aucpr:0.14803
[100]	train-aucpr:0.94269	validation-aucpr:0.17755
[336]	train-aucpr:0.95371	validation-aucpr:0.14792
[0]	train-aucpr:0.52676	validation-aucpr:0.02310
[200]	train-aucpr:0.94566	validation-aucpr:0.17267
[100]	train-aucpr:0.93544	validation-aucpr:0.17480
[300]	train-aucpr:0.94776	validation-aucpr:0.16755
[309]	train-aucpr:0.94737	validation-aucpr:0.16492
[200]	train-aucpr:0.93827	validation-aucpr:0.17611
[300]	train-aucpr:0.93972	validation-aucpr:0.19012
[0]	train-aucpr:0.55642	validation-aucpr:0.03542

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1456.49it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1143.55it/s]
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]1294.43it/s]

[0]	train-aucpr:0.53434	validation-aucpr:0.03662
[400]	train-aucpr:0.94514	validation-aucpr:0.19288
[100]	train-aucpr:0.91671	validation-aucpr:0.53965
[100]	train-aucpr:0.91543	validation-aucpr:0.42999
[500]	train-aucpr:0.94607	validation-aucpr:0.17552
[200]	train-aucpr:0.91907	validation-aucpr:0.52462
[0]	train-aucpr:0.54542	validation-aucpr:0.03918
[576]	train-aucpr:0.94694	validation-aucpr:0.17658
[200]	train-aucpr:0.92020	validation-aucpr:0.44066
[300]	train-aucpr:0.92043	validation-aucpr:0.52322
[235]	train-aucpr:0.91733	validation-aucpr:0.43920
[100]	train-aucpr:0.92719	validation-aucpr:0.36301
[0]	train-aucpr:0.52599	validation-aucpr:0.04033
[374]	train-aucpr:0.92238	validation-aucpr:0.54670
[200]	train-aucpr:0.93014	validation-aucpr:0.33908
[100]	train-aucpr:0.88852	validation-aucpr:0.57586
[0]	train-aucpr:0.52378	validation-aucpr:0.03430
[300]	train-aucpr:0.93193	validation-aucpr:0.34781
[200]	train-aucpr:0.89465	validation-aucpr:0.55271
[100]	train-aucpr:0.92055	validation-aucpr:0.21884

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1102.32it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1353.60it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1350.08it/s]
Bootstrapping pr_auc:  84%|████████▍ | 845/1000 [00:00<00:00, 1360.80it/s]

[400]	train-aucpr:0.93385	validation-aucpr:0.32103
[300]	train-aucpr:0.89558	validation-aucpr:0.55718
[426]	train-aucpr:0.93386	validation-aucpr:0.32374
[200]	train-aucpr:0.92434	validation-aucpr:0.23032
[333]	train-aucpr:0.89567	validation-aucpr:0.55294
[300]	train-aucpr:0.92503	validation-aucpr:0.23378
[345]	train-aucpr:0.92582	validation-aucpr:0.23880
[0]	train-aucpr:0.53155	validation-aucpr:0.03609
[100]	train-aucpr:0.95202	validation-aucpr:0.35987
[0]	train-aucpr:0.51733	validation-aucpr:0.03326
[200]	train-aucpr:0.95403	validation-aucpr:0.36382

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1389.59it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1470.86it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1188.25it/s]
Bootstrapping pr_auc:  96%|█████████▌| 960/1000 [00:00<00:00, 1201.11it/s]

[0]	train-aucpr:0.57055	validation-aucpr:0.03326
[100]	train-aucpr:0.92323	validation-aucpr:0.24021
[100]	train-aucpr:0.93252	validation-aucpr:0.42529
[300]	train-aucpr:0.95369	validation-aucpr:0.36434
[341]	train-aucpr:0.95464	validation-aucpr:0.36493
[0]	train-aucpr:0.57372	validation-aucpr:0.02971
[200]	train-aucpr:0.93788	validation-aucpr:0.37384
[200]	train-aucpr:0.92694	validation-aucpr:0.24026
[0]	train-aucpr:0.53572	validation-aucpr:0.02408
[100]	train-aucpr:0.92511	validation-aucpr:0.35635
[300]	train-aucpr:0.92792	validation-aucpr:0.24113
[300]	train-aucpr:0.93755	validation-aucpr:0.37067
[301]	train-aucpr:0.93757	validation-aucpr:0.37067
[100]	train-aucpr:0.91614	validation-aucpr:0.26682
[350]	train-aucpr:0.92927	validation-aucpr:0.24036
[200]	train-aucpr:0.92956	validation-aucpr:0.36373
[200]	train-aucpr:0.92157	validation-aucpr:0.29064
[0]	train-aucpr:0.53202	validation-aucpr:0.02657
[300]	train-aucpr:0.93023	validation-aucpr:0.36382

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1343.66it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1241.08it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1290.68it/s]
Bootstrapping pr_auc:  89%|████████▉ | 888/1000 [00:00<00:00, 1440.73it/s]

[300]	train-aucpr:0.92282	validation-aucpr:0.29487
[0]	train-aucpr:0.50232	validation-aucpr:0.02374
[100]	train-aucpr:0.92040	validation-aucpr:0.42811
[400]	train-aucpr:0.93331	validation-aucpr:0.43420
[100]	train-aucpr:0.91315	validation-aucpr:0.25394
[400]	train-aucpr:0.92575	validation-aucpr:0.30081
[0]	train-aucpr:0.56007	validation-aucpr:0.03697
[200]	train-aucpr:0.91867	validation-aucpr:0.30701
[200]	train-aucpr:0.92708	validation-aucpr:0.40244
[500]	train-aucpr:0.92594	validation-aucpr:0.27512
[500]	train-aucpr:0.93460	validation-aucpr:0.43960
[226]	train-aucpr:0.92754	validation-aucpr:0.40021
[300]	train-aucpr:0.91785	validation-aucpr:0.31402
[563]	train-aucpr:0.92682	validation-aucpr:0.27286
[100]	train-aucpr:0.94632	validation-aucpr:0.21414
[0]	train-aucpr:0.50203	validation-aucpr:0.03592
[400]	train-aucpr:0.92160	validation-aucpr:0.33079
[600]	train-aucpr:0.93597	validation-aucpr:0.43813
[200]	train-aucpr:0.94857	validation-aucpr:0.21734
[100]	train-aucpr:0.91177	validation-aucpr:0.32615
[500]	train-aucpr:0.92196	validation-aucpr:0.31647
[700]	train-aucpr:0.93703	validation-aucpr:0.43808
[300]	train-aucpr:0.95158	validation-aucpr:0.23481

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1402.87it/s]
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s] 1222.94it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1223.72it/s]
Bootstrapping pr_auc:  30%|███       | 304/1000 [00:00<00:00, 1498.65it/s]

[576]	train-aucpr:0.92390	validation-aucpr:0.32816
[200]	train-aucpr:0.90695	validation-aucpr:0.28931
[800]	train-aucpr:0.93820	validation-aucpr:0.43712
[400]	train-aucpr:0.95442	validation-aucpr:0.23542
[300]	train-aucpr:0.90692	validation-aucpr:0.33100
[312]	train-aucpr:0.90695	validation-aucpr:0.32574
[900]	train-aucpr:0.93976	validation-aucpr:0.43711
[932]	train-aucpr:0.94045	validation-aucpr:0.43473
[500]	train-aucpr:0.95544	validation-aucpr:0.29935
[0]	train-aucpr:0.55389	validation-aucpr:0.04033
[600]	train-aucpr:0.95697	validation-aucpr:0.29699
[100]	train-aucpr:0.93087	validation-aucpr:0.48834
[669]	train-aucpr:0.95670	validation-aucpr:0.29699
[0]	train-aucpr:0.54331	validation-aucpr:0.03326
[200]	train-aucpr:0.93287	validation-aucpr:0.51497
[300]	train-aucpr:0.93281	validation-aucpr:0.50851

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1401.25it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1245.18it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1207.79it/s]
Bootstrapping pr_auc:  48%|████▊     | 478/1000 [00:00<00:00, 1496.71it/s]

[400]	train-aucpr:0.93505	validation-aucpr:0.49874
[0]	train-aucpr:0.54805	validation-aucpr:0.02626
[100]	train-aucpr:0.92418	validation-aucpr:0.24842
[0]	train-aucpr:0.53631	validation-aucpr:0.02587
[100]	train-aucpr:0.93465	validation-aucpr:0.19653
[0]	train-aucpr:0.57356	validation-aucpr:0.03141
[200]	train-aucpr:0.93263	validation-aucpr:0.23654
[200]	train-aucpr:0.94013	validation-aucpr:0.19718
[100]	train-aucpr:0.91748	validation-aucpr:0.16799
[100]	train-aucpr:0.92403	validation-aucpr:0.45085
[300]	train-aucpr:0.93532	validation-aucpr:0.23896
[312]	train-aucpr:0.93603	validation-aucpr:0.22795
[0]	train-aucpr:0.51733	validation-aucpr:0.03400
[300]	train-aucpr:0.94093	validation-aucpr:0.17546
[200]	train-aucpr:0.92064	validation-aucpr:0.17233
[200]	train-aucpr:0.92768	validation-aucpr:0.45924
[400]	train-aucpr:0.94300	validation-aucpr:0.17764
[300]	train-aucpr:0.92029	validation-aucpr:0.17260
[409]	train-aucpr:0.94299	validation-aucpr:0.17759
[273]	train-aucpr:0.92829	validation-aucpr:0.45947
[362]	train-aucpr:0.92231	validation-aucpr:0.17466
[100]	train-aucpr:0.92221	validation-aucpr:0.34589

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1414.80it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1337.07it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1169.97it/s]
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]1341.67it/s]

[200]	train-aucpr:0.93130	validation-aucpr:0.39963
[300]	train-aucpr:0.93366	validation-aucpr:0.34120[0]	train-aucpr:0.58713	validation-aucpr:0.03169

[100]	train-aucpr:0.94999	validation-aucpr:0.07777
[381]	train-aucpr:0.93575	validation-aucpr:0.34629
[200]	train-aucpr:0.95277	validation-aucpr:0.08033
[0]	train-aucpr:0.54071	validation-aucpr:0.03526
[300]	train-aucpr:0.95195	validation-aucpr:0.08206
[100]	train-aucpr:0.91746	validation-aucpr:0.67223
[352]	train-aucpr:0.95271	validation-aucpr:0.08743
[0]	train-aucpr:0.55999	validation-aucpr:0.02947
[200]	train-aucpr:0.92025	validation-aucpr:0.68043

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1396.35it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1289.06it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1447.50it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1409.61it/s]
Bootstrapping pr_auc:  54%|█████▎    | 536/1000 [00:00<00:00, 1324.40it/s]

[100]	train-aucpr:0.91512	validation-aucpr:0.37108
[300]	train-aucpr:0.92155	validation-aucpr:0.68043
[0]	train-aucpr:0.59373	validation-aucpr:0.04033
[100]	train-aucpr:0.91454	validation-aucpr:0.55923
[200]	train-aucpr:0.91729	validation-aucpr:0.38048
[400]	train-aucpr:0.92583	validation-aucpr:0.70130
[200]	train-aucpr:0.91809	validation-aucpr:0.54208
[500]	train-aucpr:0.92779	validation-aucpr:0.70130
[300]	train-aucpr:0.91740	validation-aucpr:0.37753
[300]	train-aucpr:0.92239	validation-aucpr:0.50100
[356]	train-aucpr:0.91889	validation-aucpr:0.37173
[600]	train-aucpr:0.93024	validation-aucpr:0.69636
[348]	train-aucpr:0.92344	validation-aucpr:0.50017
[0]	train-aucpr:0.52823	validation-aucpr:0.03461
[700]	train-aucpr:0.93101	validation-aucpr:0.70108
[741]	train-aucpr:0.93075	validation-aucpr:0.70164
[100]	train-aucpr:0.89252	validation-aucpr:0.34251

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1334.58it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1180.35it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1415.82it/s]
Bootstrapping pr_auc:  16%|█▌        | 155/1000 [00:00<00:00, 1549.90it/s]

[200]	train-aucpr:0.89724	validation-aucpr:0.35217
[0]	train-aucpr:0.55591	validation-aucpr:0.03155
[0]	train-aucpr:0.57430	validation-aucpr:0.02667
[300]	train-aucpr:0.90005	validation-aucpr:0.38527
[100]	train-aucpr:0.94983	validation-aucpr:0.19095
[100]	train-aucpr:0.92085	validation-aucpr:0.36255
[200]	train-aucpr:0.95279	validation-aucpr:0.17822
[400]	train-aucpr:0.90545	validation-aucpr:0.37609
[200]	train-aucpr:0.92384	validation-aucpr:0.37437
[300]	train-aucpr:0.95345	validation-aucpr:0.17746
[0]	train-aucpr:0.54650	validation-aucpr:0.03183
[500]	train-aucpr:0.90689	validation-aucpr:0.33309
[503]	train-aucpr:0.90693	validation-aucpr:0.33309
[353]	train-aucpr:0.95554	validation-aucpr:0.16793
[100]	train-aucpr:0.90860	validation-aucpr:0.46881
[300]	train-aucpr:0.92319	validation-aucpr:0.37566
[200]	train-aucpr:0.91072	validation-aucpr:0.47576

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1354.02it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1496.89it/s]
Bootstrapping pr_auc:  46%|████▌     | 459/1000 [00:00<00:00, 1282.49it/s]

[400]	train-aucpr:0.92709	validation-aucpr:0.36872
[401]	train-aucpr:0.92713	validation-aucpr:0.36872
[300]	train-aucpr:0.91078	validation-aucpr:0.47146
[0]	train-aucpr:0.55065	validation-aucpr:0.03644
[343]	train-aucpr:0.91072	validation-aucpr:0.47277
[100]	train-aucpr:0.95785	validation-aucpr:0.29549
[0]	train-aucpr:0.57260	validation-aucpr:0.03198
[200]	train-aucpr:0.96117	validation-aucpr:0.30377
[100]	train-aucpr:0.91982	validation-aucpr:0.37591
[0]	train-aucpr:0.58415	validation-aucpr:0.03021
[300]	train-aucpr:0.96084	validation-aucpr:0.30490
[0]	train-aucpr:0.50911	validation-aucpr:0.04052
[345]	train-aucpr:0.96124	validation-aucpr:0.30098
[100]	train-aucpr:0.93137	validation-aucpr:0.33131
[200]	train-aucpr:0.92116	validation-aucpr:0.41005

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1225.31it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1169.64it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1337.23it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1368.21it/s]
Bootstrapping pr_auc:  28%|██▊       | 278/1000 [00:00<00:00, 1341.96it/s]

[100]	train-aucpr:0.90226	validation-aucpr:0.43138
[200]	train-aucpr:0.93584	validation-aucpr:0.34242
[300]	train-aucpr:0.93589	validation-aucpr:0.34186
[200]	train-aucpr:0.91231	validation-aucpr:0.41296
[300]	train-aucpr:0.92325	validation-aucpr:0.45237
[400]	train-aucpr:0.93958	validation-aucpr:0.34693
[300]	train-aucpr:0.91601	validation-aucpr:0.38436
[307]	train-aucpr:0.91581	validation-aucpr:0.38336
[400]	train-aucpr:0.92574	validation-aucpr:0.47240
[500]	train-aucpr:0.93977	validation-aucpr:0.46517
[600]	train-aucpr:0.94449	validation-aucpr:0.46728
[500]	train-aucpr:0.92593	validation-aucpr:0.46942
[700]	train-aucpr:0.94490	validation-aucpr:0.46679
[589]	train-aucpr:0.92659	validation-aucpr:0.46938

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1359.68it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1365.95it/s]
Bootstrapping pr_auc:  58%|█████▊    | 580/1000 [00:00<00:00, 1304.67it/s]

[778]	train-aucpr:0.94507	validation-aucpr:0.46747

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1226.84it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1367.41it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1273.83it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1354.80it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1405.52it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1429.90it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1577.24it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1522.15it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1525.53it/s]

bound,Metrics,estimate,lower,upper,models
0,AUPRC_value,43.3939,21.7415,65.9645,XGBoost (VL diag + 1 & SMOTE)
1,AUROC_value,93.2148,85.7114,98.2488,XGBoost (VL diag + 1 & SMOTE)
2,Accuracy,87.4743,82.6208,91.5408,XGBoost (VL diag + 1 & SMOTE)
3,Accuracy_train,86.5997,82.3196,90.7360,XGBoost (VL diag + 1 & SMOTE)
4,NPV,99.3785,98.4374,100.0000,XGBoost (VL diag + 1 & SMOTE)
5,Precision,17.5414,12.7716,24.3015,XGBoost (VL diag + 1 & SMOTE)
6,Sensitivity,82.3000,54.7500,100.0000,XGBoost (VL diag + 1 & SMOTE)
7,Specificity,87.6355,82.5389,91.6044,XGBoost (VL diag + 1 & SMOTE)

## Fitting data list with VL at diagnosis & VL at 2-days after diagnosis

In [8]:
xgb_add2_list = model_func_xgb_tune(split_list_diag2_valid_smote_final)
xgb_add2_met_summary = sum_metric(xgb_add2_list)
xgb_add2_metrics_summary = xgb_add2_met_summary["metric_summary"]
xgb_add2_summary = met_collate_func(xgb_add2_metrics_summary).assign(
    models = "XGBoost (VL diag + 2 & SMOTE)"
)
xgb_add2_summary

/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:58] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:58] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:58] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:58] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:58] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:58] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:58] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:58] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:58] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:58] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:58] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:58] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:58] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:58] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:58] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:58] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:58] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:58] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:58] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:58] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:58] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:58] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:58] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:58] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()

[0]	train-aucpr:0.52476	validation-aucpr:0.03936
[0]	train-aucpr:0.55870	validation-aucpr:0.04176
[100]	train-aucpr:0.91080	validation-aucpr:0.61483
[100]	train-aucpr:0.93049	validation-aucpr:0.54473
[0]	train-aucpr:0.51440	validation-aucpr:0.03697
[200]	train-aucpr:0.91759	validation-aucpr:0.58689
[0]	train-aucpr:0.54171	validation-aucpr:0.03141
[200]	train-aucpr:0.93273	validation-aucpr:0.54234
[100]	train-aucpr:0.92758	validation-aucpr:0.43148
[100]	train-aucpr:0.94085	validation-aucpr:0.45163
[300]	train-aucpr:0.91896	validation-aucpr:0.58023
[0]	train-aucpr:0.57115	validation-aucpr:0.02235
[273]	train-aucpr:0.93347	validation-aucpr:0.54254
[339]	train-aucpr:0.91992	validation-aucpr:0.57184
[0]	train-aucpr:0.57182	validation-aucpr:0.03021
[200]	train-aucpr:0.93164	validation-aucpr:0.37747
[0]	train-aucpr:0.57580	validation-aucpr:0.03009
[0]	train-aucpr:0.56957	validation-aucpr:0.02647
[200]	train-aucpr:0.94398	validation-aucpr:0.44019
[100]	train-aucpr:0.91982	validation-aucpr:0.35263
[100]	train-aucpr:0.94837	validation-aucpr:0.19670
[256]	train-aucpr:0.94346	validation-aucpr:0.44114
[0]	train-aucpr:0.54305	validation-aucpr:0.04013
[292]	train-aucpr:0.93387	validation-aucpr:0.38058
[0]	train-aucpr:0.56935	validation-aucpr:0.04865
[0]	train-aucpr:0.52290	validation-aucpr:0.03592
[100]	train-aucpr:0.93952	validation-aucpr:0.20909
[100]	train-aucpr:0.92454	validation-aucpr:0.46041
[200]	train-aucpr:0.92206	validation-aucpr:0.31204
[200]	train-aucpr:0.94851	validation-aucpr:0.19454
[100]	train-aucpr:0.91082	validation-aucpr:0.40862
[0]	train-aucpr:0.51998	validation-aucpr:0.03169
[100]	train-aucpr:0.94457	validation-aucpr:0.28936
[100]	train-aucpr:0.96110	validation-aucpr:0.38648
[200]	train-aucpr:0.94221	validation-aucpr:0.22618
[200]	train-aucpr:0.92915	validation-aucpr:0.46751
[300]	train-aucpr:0.92454	validation-aucpr:0.30407
[305]	train-aucpr:0.92436	validation-aucpr:0.30388
[0]	train-aucpr:0.53639	validation-aucpr:0.03127
[300]	train-aucpr:0.95141	validation-aucpr:0.19196
[200]	train-aucpr:0.91468	validation-aucpr:0.36794
[200]	train-aucpr:0.94727	validation-aucpr:0.28875
[200]	train-aucpr:0.96226	validation-aucpr:0.38562
[300]	train-aucpr:0.94309	validation-aucpr:0.23832
[300]	train-aucpr:0.93033	validation-aucpr:0.46216
[100]	train-aucpr:0.93293	validation-aucpr:0.51801
[0]	train-aucpr:0.54920	validation-aucpr:0.02984
[273]	train-aucpr:0.94849	validation-aucpr:0.28330
[349]	train-aucpr:0.95179	validation-aucpr:0.19210
[285]	train-aucpr:0.91697	validation-aucpr:0.35691
[100]	train-aucpr:0.94507	validation-aucpr:0.41226
[300]	train-aucpr:0.96228	validation-aucpr:0.37630
[387]	train-aucpr:0.93124	validation-aucpr:0.46407
[400]	train-aucpr:0.94388	validation-aucpr:0.25493
[200]	train-aucpr:0.94172	validation-aucpr:0.58388
[100]	train-aucpr:0.92672	validation-aucpr:0.39517
[374]	train-aucpr:0.96276	validation-aucpr:0.37572
[200]	train-aucpr:0.94838	validation-aucpr:0.41555
[259]	train-aucpr:0.94239	validation-aucpr:0.57134
[0]	train-aucpr:0.54628	validation-aucpr:0.03734
[500]	train-aucpr:0.94487	validation-aucpr:0.24332
[250]	train-aucpr:0.94712	validation-aucpr:0.42344
[200]	train-aucpr:0.92879	validation-aucpr:0.38897
[100]	train-aucpr:0.95739	validation-aucpr:0.21104
[600]	train-aucpr:0.94652	validation-aucpr:0.30263
[299]	train-aucpr:0.92849	validation-aucpr:0.38791
[700]	train-aucpr:0.94734	validation-aucpr:0.26334
[200]	train-aucpr:0.95905	validation-aucpr:0.21725

/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:58] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:58] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:58] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:58] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
Bootstrapping pr_auc:  16%|█▌        | 155/1000 [00:00<00:00, 1543.86it/s]/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:59] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  self.starting_round = model.num_boosted_rounds()
/home/blaw004/anaconda3/lib/python3.12/site-packages/xgboost/callback.py:385: UserWarning: [13:43:59] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  self.starting_round = model.num_boosted_rounds()
Bootstrapping pr_auc:  31%|███       | 310/1000 [00:00<00:00, 1368.47it/s]

[800]	train-aucpr:0.94720	validation-aucpr:0.26463
[852]	train-aucpr:0.94745	validation-aucpr:0.26357
[300]	train-aucpr:0.95896	validation-aucpr:0.21136
[344]	train-aucpr:0.95875	validation-aucpr:0.21435

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1524.87it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1460.55it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1396.29it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1305.52it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1435.35it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1381.01it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1407.95it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1326.63it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1254.88it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1358.84it/s]

[0]	train-aucpr:0.58121	validation-aucpr:0.03047
[100]	train-aucpr:0.95323	validation-aucpr:0.36084
[0]	train-aucpr:0.57678	validation-aucpr:0.02647
[200]	train-aucpr:0.95292	validation-aucpr:0.37425
[100]	train-aucpr:0.92935	validation-aucpr:0.32142
[300]	train-aucpr:0.95313	validation-aucpr:0.38467
[0]	train-aucpr:0.56698	validation-aucpr:0.02688
[0]	train-aucpr:0.52542	validation-aucpr:0.03141
[100]	train-aucpr:0.94286	validation-aucpr:0.41359[400]	train-aucpr:0.95489	validation-aucpr:0.39787

[100]	train-aucpr:0.94262	validation-aucpr:0.25059
[200]	train-aucpr:0.93261	validation-aucpr:0.32381
[0]	train-aucpr:0.54291	validation-aucpr:0.03477
[500]	train-aucpr:0.95561	validation-aucpr:0.39969
[200]	train-aucpr:0.94378	validation-aucpr:0.42041
[200]	train-aucpr:0.94492	validation-aucpr:0.24468
[300]	train-aucpr:0.93283	validation-aucpr:0.32414
[100]	train-aucpr:0.95487	validation-aucpr:0.28238
[0]	train-aucpr:0.53003	validation-aucpr:0.02540
[340]	train-aucpr:0.93471	validation-aucpr:0.31821

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1237.68it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1430.03it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1170.80it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1227.30it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1321.93it/s]
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]

[258]	train-aucpr:0.94392	validation-aucpr:0.23828
[300]	train-aucpr:0.94371	validation-aucpr:0.41981
[600]	train-aucpr:0.95578	validation-aucpr:0.40016
[200]	train-aucpr:0.95595	validation-aucpr:0.28654
[100]	train-aucpr:0.91505	validation-aucpr:0.46130
[356]	train-aucpr:0.94468	validation-aucpr:0.41960
[230]	train-aucpr:0.95377	validation-aucpr:0.29149
[700]	train-aucpr:0.95585	validation-aucpr:0.40279
[200]	train-aucpr:0.91817	validation-aucpr:0.48872
[800]	train-aucpr:0.95618	validation-aucpr:0.38311
[0]	train-aucpr:0.53873	validation-aucpr:0.03526
[0]	train-aucpr:0.54859	validation-aucpr:0.03198
[300]	train-aucpr:0.92077	validation-aucpr:0.48749
[0]	train-aucpr:0.54972	validation-aucpr:0.02568
[352]	train-aucpr:0.92239	validation-aucpr:0.49743
[100]	train-aucpr:0.93743	validation-aucpr:0.38833
[100]	train-aucpr:0.92769	validation-aucpr:0.53912
[900]	train-aucpr:0.95655	validation-aucpr:0.37739
[100]	train-aucpr:0.91202	validation-aucpr:0.39009
[937]	train-aucpr:0.95670	validation-aucpr:0.37739
[200]	train-aucpr:0.93928	validation-aucpr:0.37329
[200]	train-aucpr:0.93464	validation-aucpr:0.52940
[200]	train-aucpr:0.91402	validation-aucpr:0.38659
[0]	train-aucpr:0.57174	validation-aucpr:0.02365

Bootstrapping pr_auc:   9%|▉         | 90/1000 [00:00<00:01, 898.63it/s]s]

[250]	train-aucpr:0.93404	validation-aucpr:0.53912
[300]	train-aucpr:0.93890	validation-aucpr:0.33623
[307]	train-aucpr:0.93825	validation-aucpr:0.33623
[0]	train-aucpr:0.57798	validation-aucpr:0.02947
[100]	train-aucpr:0.91352	validation-aucpr:0.64075
[300]	train-aucpr:0.91524	validation-aucpr:0.38769
[341]	train-aucpr:0.91633	validation-aucpr:0.38133
[200]	train-aucpr:0.91550	validation-aucpr:0.65322
[100]	train-aucpr:0.91769	validation-aucpr:0.27877
[0]	train-aucpr:0.57338	validation-aucpr:0.02444
[200]	train-aucpr:0.92121	validation-aucpr:0.35558
[100]	train-aucpr:0.94699	validation-aucpr:0.29276
[300]	train-aucpr:0.91490	validation-aucpr:0.63467
[355]	train-aucpr:0.91636	validation-aucpr:0.61450
[0]	train-aucpr:0.52272	validation-aucpr:0.02578
[300]	train-aucpr:0.92191	validation-aucpr:0.35050
[100]	train-aucpr:0.94017	validation-aucpr:0.35410
[383]	train-aucpr:0.92455	validation-aucpr:0.35732
[200]	train-aucpr:0.94924	validation-aucpr:0.40272
[0]	train-aucpr:0.54154	validation-aucpr:0.02607
[200]	train-aucpr:0.94286	validation-aucpr:0.33904

Bootstrapping pr_auc:  74%|███████▍  | 744/1000 [00:00<00:00, 1516.09it/s]

[300]	train-aucpr:0.94946	validation-aucpr:0.40605
[100]	train-aucpr:0.93669	validation-aucpr:0.20468
[300]	train-aucpr:0.94312	validation-aucpr:0.32967
[0]	train-aucpr:0.52366	validation-aucpr:0.02688
[391]	train-aucpr:0.95096	validation-aucpr:0.39989
[200]	train-aucpr:0.93731	validation-aucpr:0.21976
[208]	train-aucpr:0.93722	validation-aucpr:0.21869
[355]	train-aucpr:0.94368	validation-aucpr:0.33725
[100]	train-aucpr:0.94605	validation-aucpr:0.27207
[200]	train-aucpr:0.94792	validation-aucpr:0.27640
[236]	train-aucpr:0.94688	validation-aucpr:0.28138

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1462.99it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1468.87it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1432.79it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1355.34it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1384.90it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1511.80it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1386.90it/s]

[0]	train-aucpr:0.52943	validation-aucpr:0.04093
[0]	train-aucpr:0.55288	validation-aucpr:0.03034
[100]	train-aucpr:0.90093	validation-aucpr:0.63938
[100]	train-aucpr:0.92435	validation-aucpr:0.40684
[200]	train-aucpr:0.90633	validation-aucpr:0.61291
[200]	train-aucpr:0.92607	validation-aucpr:0.42106
[0]	train-aucpr:0.53932	validation-aucpr:0.04134
[300]	train-aucpr:0.90887	validation-aucpr:0.59809
[300]	train-aucpr:0.92651	validation-aucpr:0.42170
[100]	train-aucpr:0.93241	validation-aucpr:0.37901
[354]	train-aucpr:0.91011	validation-aucpr:0.59125
[200]	train-aucpr:0.93524	validation-aucpr:0.37837
[400]	train-aucpr:0.92813	validation-aucpr:0.40656
[0]	train-aucpr:0.59043	validation-aucpr:0.02677
[500]	train-aucpr:0.92799	validation-aucpr:0.40610

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1279.92it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1349.36it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1338.29it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1227.72it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1414.19it/s]
Bootstrapping pr_auc:  97%|█████████▋| 973/1000 [00:00<00:00, 1455.32it/s]

[0]	train-aucpr:0.58291	validation-aucpr:0.03169
[0]	train-aucpr:0.54723	validation-aucpr:0.02647
[576]	train-aucpr:0.92804	validation-aucpr:0.41018
[100]	train-aucpr:0.95038	validation-aucpr:0.57720
[300]	train-aucpr:0.93513	validation-aucpr:0.40141
[100]	train-aucpr:0.94893	validation-aucpr:0.46236
[100]	train-aucpr:0.94688	validation-aucpr:0.19218
[0]	train-aucpr:0.51524	validation-aucpr:0.03370
[200]	train-aucpr:0.95031	validation-aucpr:0.57471
[200]	train-aucpr:0.94850	validation-aucpr:0.19335
[400]	train-aucpr:0.93679	validation-aucpr:0.37422
[200]	train-aucpr:0.94979	validation-aucpr:0.44539[236]	train-aucpr:0.94669	validation-aucpr:0.19044

[464]	train-aucpr:0.93635	validation-aucpr:0.40039
[0]	train-aucpr:0.56558	validation-aucpr:0.03155
[300]	train-aucpr:0.95012	validation-aucpr:0.58280
[100]	train-aucpr:0.95045	validation-aucpr:0.34636
[300]	train-aucpr:0.95035	validation-aucpr:0.44600
[361]	train-aucpr:0.95013	validation-aucpr:0.58767
[100]	train-aucpr:0.92984	validation-aucpr:0.34634
[200]	train-aucpr:0.95280	validation-aucpr:0.35501
[379]	train-aucpr:0.95214	validation-aucpr:0.43163

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1372.30it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1361.59it/s]
Bootstrapping pr_auc:  45%|████▍     | 447/1000 [00:00<00:00, 1446.47it/s]

[200]	train-aucpr:0.93193	validation-aucpr:0.34439
[279]	train-aucpr:0.95327	validation-aucpr:0.35851
[224]	train-aucpr:0.93154	validation-aucpr:0.34759
[0]	train-aucpr:0.56447	validation-aucpr:0.02959
[0]	train-aucpr:0.57372	validation-aucpr:0.02325
[100]	train-aucpr:0.90134	validation-aucpr:0.65749
[0]	train-aucpr:0.52454	validation-aucpr:0.03155
[100]	train-aucpr:0.94825	validation-aucpr:0.39072
[0]	train-aucpr:0.56141	validation-aucpr:0.03009
[200]	train-aucpr:0.90719	validation-aucpr:0.65531
[100]	train-aucpr:0.93587	validation-aucpr:0.29560
[200]	train-aucpr:0.94991	validation-aucpr:0.32312
[100]	train-aucpr:0.91168	validation-aucpr:0.66642
[0]	train-aucpr:0.55093	validation-aucpr:0.02731
[200]	train-aucpr:0.93797	validation-aucpr:0.29867
[300]	train-aucpr:0.90743	validation-aucpr:0.64978
[200]	train-aucpr:0.91695	validation-aucpr:0.65946
[300]	train-aucpr:0.95087	validation-aucpr:0.32835
[307]	train-aucpr:0.95067	validation-aucpr:0.32363
[100]	train-aucpr:0.94009	validation-aucpr:0.33938
[300]	train-aucpr:0.93795	validation-aucpr:0.29905

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1059.66it/s]
Bootstrapping pr_auc:  49%|████▉     | 492/1000 [00:00<00:00, 1304.31it/s]

[378]	train-aucpr:0.90918	validation-aucpr:0.63710
[0]	train-aucpr:0.53050	validation-aucpr:0.03575
[360]	train-aucpr:0.93752	validation-aucpr:0.30092
[300]	train-aucpr:0.91818	validation-aucpr:0.66228
[200]	train-aucpr:0.94280	validation-aucpr:0.34321
[208]	train-aucpr:0.94236	validation-aucpr:0.34124
[382]	train-aucpr:0.92442	validation-aucpr:0.65992
[100]	train-aucpr:0.92563	validation-aucpr:0.28244
[200]	train-aucpr:0.92819	validation-aucpr:0.28526
[210]	train-aucpr:0.92845	validation-aucpr:0.27748
[0]	train-aucpr:0.52690	validation-aucpr:0.02753
[100]	train-aucpr:0.92029	validation-aucpr:0.38583
[200]	train-aucpr:0.92389	validation-aucpr:0.36241

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1265.30it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1365.39it/s]
Bootstrapping pr_auc:  96%|█████████▋| 964/1000 [00:00<00:00, 1490.85it/s]

[300]	train-aucpr:0.92950	validation-aucpr:0.38236
[400]	train-aucpr:0.93612	validation-aucpr:0.42455
[500]	train-aucpr:0.93689	validation-aucpr:0.42948
[562]	train-aucpr:0.93839	validation-aucpr:0.42897
[0]	train-aucpr:0.51070	validation-aucpr:0.04176

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1352.68it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1264.49it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1280.36it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1147.92it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1265.10it/s]
Bootstrapping pr_auc:  26%|██▌       | 261/1000 [00:00<00:00, 1113.33it/s]

[100]	train-aucpr:0.90183	validation-aucpr:0.37688
[0]	train-aucpr:0.52618	validation-aucpr:0.04113
[200]	train-aucpr:0.90684	validation-aucpr:0.36171
[0]	train-aucpr:0.55687	validation-aucpr:0.03202
[299]	train-aucpr:0.90658	validation-aucpr:0.36075
[100]	train-aucpr:0.93198	validation-aucpr:0.35645
[100]	train-aucpr:0.91905	validation-aucpr:0.68504
[200]	train-aucpr:0.93361	validation-aucpr:0.36263
[200]	train-aucpr:0.92111	validation-aucpr:0.66803
[0]	train-aucpr:0.51307	validation-aucpr:0.03385

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1514.77it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1419.57it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1096.27it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1364.33it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1308.91it/s]

[300]	train-aucpr:0.92151	validation-aucpr:0.68788
[300]	train-aucpr:0.93446	validation-aucpr:0.35703
[374]	train-aucpr:0.92332	validation-aucpr:0.71425
[0]	train-aucpr:0.54214	validation-aucpr:0.02742
[345]	train-aucpr:0.93525	validation-aucpr:0.35645
[100]	train-aucpr:0.93512	validation-aucpr:0.17131
[0]	train-aucpr:0.52333	validation-aucpr:0.01720
[200]	train-aucpr:0.93772	validation-aucpr:0.14856
[0]	train-aucpr:0.56197	validation-aucpr:0.03477
[291]	train-aucpr:0.93843	validation-aucpr:0.14796
[100]	train-aucpr:0.92845	validation-aucpr:0.36182
[100]	train-aucpr:0.90856	validation-aucpr:0.23406
[0]	train-aucpr:0.54499	validation-aucpr:0.03242
[100]	train-aucpr:0.92947	validation-aucpr:0.55051
[200]	train-aucpr:0.93141	validation-aucpr:0.39127
[0]	train-aucpr:0.51480	validation-aucpr:0.03446
[200]	train-aucpr:0.91125	validation-aucpr:0.23179
[100]	train-aucpr:0.91946	validation-aucpr:0.55573
[300]	train-aucpr:0.93334	validation-aucpr:0.38878
[200]	train-aucpr:0.93148	validation-aucpr:0.55182

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1196.42it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1253.31it/s]
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]958.92it/s]]

[0]	train-aucpr:0.53709	validation-aucpr:0.02657

[100]	train-aucpr:0.92183	validation-aucpr:0.40152
[400]	train-aucpr:0.93703	validation-aucpr:0.40517
[200]	train-aucpr:0.92242	validation-aucpr:0.55812[0]	train-aucpr:0.59897	validation-aucpr:0.02779

[300]	train-aucpr:0.91118	validation-aucpr:0.23284
[270]	train-aucpr:0.93139	validation-aucpr:0.55286
[100]	train-aucpr:0.92270	validation-aucpr:0.31704
[339]	train-aucpr:0.91017	validation-aucpr:0.23008
[200]	train-aucpr:0.92427	validation-aucpr:0.40470
[500]	train-aucpr:0.93772	validation-aucpr:0.37707
[100]	train-aucpr:0.93801	validation-aucpr:0.19661
[0]	train-aucpr:0.56836	validation-aucpr:0.02657
[300]	train-aucpr:0.92265	validation-aucpr:0.56448
[200]	train-aucpr:0.92531	validation-aucpr:0.31932
[214]	train-aucpr:0.92486	validation-aucpr:0.30543
[200]	train-aucpr:0.93976	validation-aucpr:0.20844
[100]	train-aucpr:0.94265	validation-aucpr:0.12566[400]	train-aucpr:0.92466	validation-aucpr:0.57072

[0]	train-aucpr:0.56487	validation-aucpr:0.03644
[300]	train-aucpr:0.92673	validation-aucpr:0.41529
[600]	train-aucpr:0.93878	validation-aucpr:0.37860
[601]	train-aucpr:0.94109	validation-aucpr:0.37860
[500]	train-aucpr:0.92503	validation-aucpr:0.57090
[300]	train-aucpr:0.94027	validation-aucpr:0.20325
[0]	train-aucpr:0.52663	validation-aucpr:0.04497
[514]	train-aucpr:0.92522	validation-aucpr:0.56903
[200]	train-aucpr:0.94655	validation-aucpr:0.11983
[400]	train-aucpr:0.93032	validation-aucpr:0.42061
[354]	train-aucpr:0.94231	validation-aucpr:0.20483
[100]	train-aucpr:0.95747	validation-aucpr:0.33277
[100]	train-aucpr:0.92266	validation-aucpr:0.34437
[300]	train-aucpr:0.94771	validation-aucpr:0.11609
[500]	train-aucpr:0.93070	validation-aucpr:0.42542
[200]	train-aucpr:0.95879	validation-aucpr:0.33560

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1149.40it/s]
Bootstrapping pr_auc:  22%|██▏       | 222/1000 [00:00<00:00, 1091.60it/s]

[200]	train-aucpr:0.92712	validation-aucpr:0.33642
[350]	train-aucpr:0.94900	validation-aucpr:0.11002
[600]	train-aucpr:0.93162	validation-aucpr:0.42462
[268]	train-aucpr:0.95900	validation-aucpr:0.33794
[300]	train-aucpr:0.93171	validation-aucpr:0.40238
[700]	train-aucpr:0.93213	validation-aucpr:0.57564
[400]	train-aucpr:0.93596	validation-aucpr:0.39964
[800]	train-aucpr:0.93345	validation-aucpr:0.57430
[500]	train-aucpr:0.93782	validation-aucpr:0.39754
[900]	train-aucpr:0.93292	validation-aucpr:0.57747
[565]	train-aucpr:0.93981	validation-aucpr:0.39777
[999]	train-aucpr:0.93399	validation-aucpr:0.58049

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1300.81it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1468.26it/s]
Bootstrapping pr_auc:  72%|███████▏  | 720/1000 [00:00<00:00, 1543.93it/s]

[0]	train-aucpr:0.55743	validation-aucpr:0.03936
[0]	train-aucpr:0.50635	validation-aucpr:0.04093
[100]	train-aucpr:0.91020	validation-aucpr:0.89295
[100]	train-aucpr:0.89707	validation-aucpr:0.44515
[0]	train-aucpr:0.56007	validation-aucpr:0.03009
[200]	train-aucpr:0.91327	validation-aucpr:0.86906
[200]	train-aucpr:0.89935	validation-aucpr:0.47531
[100]	train-aucpr:0.95467	validation-aucpr:0.27132
[300]	train-aucpr:0.91446	validation-aucpr:0.86906
[304]	train-aucpr:0.91457	validation-aucpr:0.86906
[300]	train-aucpr:0.90055	validation-aucpr:0.47624
[200]	train-aucpr:0.95515	validation-aucpr:0.28557
[356]	train-aucpr:0.90243	validation-aucpr:0.48502
[300]	train-aucpr:0.95515	validation-aucpr:0.25902
[0]	train-aucpr:0.58304	validation-aucpr:0.04197[358]	train-aucpr:0.95565	validation-aucpr:0.27111

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1279.33it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1322.57it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1477.97it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1285.52it/s]

[0]	train-aucpr:0.59480	validation-aucpr:0.02374
[100]	train-aucpr:0.95512	validation-aucpr:0.50997
[0]	train-aucpr:0.53938	validation-aucpr:0.03073
[200]	train-aucpr:0.95442	validation-aucpr:0.51551
[100]	train-aucpr:0.93017	validation-aucpr:0.46320
[236]	train-aucpr:0.95307	validation-aucpr:0.52227
[100]	train-aucpr:0.96100	validation-aucpr:0.32123
[0]	train-aucpr:0.57981	validation-aucpr:0.02513
[200]	train-aucpr:0.93205	validation-aucpr:0.34093
[200]	train-aucpr:0.96134	validation-aucpr:0.32034
[230]	train-aucpr:0.95901	validation-aucpr:0.32729
[100]	train-aucpr:0.95866	validation-aucpr:0.18586
[300]	train-aucpr:0.93145	validation-aucpr:0.34244
[303]	train-aucpr:0.93149	validation-aucpr:0.34307
[200]	train-aucpr:0.95927	validation-aucpr:0.17883
[224]	train-aucpr:0.95895	validation-aucpr:0.17596
[0]	train-aucpr:0.57956	validation-aucpr:0.02616

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1249.20it/s]
Bootstrapping pr_auc:  84%|████████▍ | 838/1000 [00:00<00:00, 1248.42it/s]]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1323.07it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1272.90it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1301.79it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1330.26it/s]
Bootstrapping pr_auc:  14%|█▎        | 136/1000 [00:00<00:00, 1357.02it/s]

[100]	train-aucpr:0.94805	validation-aucpr:0.17084
[0]	train-aucpr:0.52676	validation-aucpr:0.02310
[200]	train-aucpr:0.95176	validation-aucpr:0.16406
[100]	train-aucpr:0.93847	validation-aucpr:0.17331
[0]	train-aucpr:0.55642	validation-aucpr:0.03542
[300]	train-aucpr:0.95275	validation-aucpr:0.15862
[309]	train-aucpr:0.95244	validation-aucpr:0.15838
[100]	train-aucpr:0.92250	validation-aucpr:0.50111
[0]	train-aucpr:0.53434	validation-aucpr:0.03662
[200]	train-aucpr:0.94101	validation-aucpr:0.16694
[243]	train-aucpr:0.93914	validation-aucpr:0.17351
[0]	train-aucpr:0.54542	validation-aucpr:0.03918
[100]	train-aucpr:0.92246	validation-aucpr:0.42652
[200]	train-aucpr:0.92530	validation-aucpr:0.52623

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1337.79it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1260.86it/s]
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]1370.29it/s]

[0]	train-aucpr:0.52599	validation-aucpr:0.04033
[100]	train-aucpr:0.93286	validation-aucpr:0.39094
[300]	train-aucpr:0.92595	validation-aucpr:0.51321
[100]	train-aucpr:0.89025	validation-aucpr:0.53601
[200]	train-aucpr:0.92769	validation-aucpr:0.42170
[377]	train-aucpr:0.92753	validation-aucpr:0.53233
[200]	train-aucpr:0.93602	validation-aucpr:0.38141
[235]	train-aucpr:0.92546	validation-aucpr:0.42967
[215]	train-aucpr:0.93571	validation-aucpr:0.38566
[200]	train-aucpr:0.89632	validation-aucpr:0.51686
[300]	train-aucpr:0.89784	validation-aucpr:0.59284
[0]	train-aucpr:0.52378	validation-aucpr:0.03430
[400]	train-aucpr:0.90055	validation-aucpr:0.59328
[100]	train-aucpr:0.92892	validation-aucpr:0.25671
[472]	train-aucpr:0.90074	validation-aucpr:0.59267

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1357.83it/s]
Bootstrapping pr_auc:  26%|██▌       | 259/1000 [00:00<00:00, 1327.52it/s]

[200]	train-aucpr:0.93100	validation-aucpr:0.26452
[300]	train-aucpr:0.93129	validation-aucpr:0.27442
[342]	train-aucpr:0.93163	validation-aucpr:0.27456
[0]	train-aucpr:0.53155	validation-aucpr:0.03609
[100]	train-aucpr:0.96015	validation-aucpr:0.30525
[0]	train-aucpr:0.51733	validation-aucpr:0.03326
[0]	train-aucpr:0.57055	validation-aucpr:0.03326
[200]	train-aucpr:0.96099	validation-aucpr:0.30781
[100]	train-aucpr:0.93394	validation-aucpr:0.26471
[226]	train-aucpr:0.95927	validation-aucpr:0.30608

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1252.34it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1329.63it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1596.72it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1303.42it/s]
Bootstrapping pr_auc:  56%|█████▋    | 563/1000 [00:00<00:00, 1441.87it/s]

[0]	train-aucpr:0.57372	validation-aucpr:0.02971
[200]	train-aucpr:0.93786	validation-aucpr:0.23750
[100]	train-aucpr:0.93779	validation-aucpr:0.35271
[0]	train-aucpr:0.53572	validation-aucpr:0.02408
[247]	train-aucpr:0.93544	validation-aucpr:0.23415
[200]	train-aucpr:0.94264	validation-aucpr:0.35208
[100]	train-aucpr:0.93271	validation-aucpr:0.37382
[100]	train-aucpr:0.92279	validation-aucpr:0.29403
[0]	train-aucpr:0.53202	validation-aucpr:0.02657
[300]	train-aucpr:0.94130	validation-aucpr:0.34439
[200]	train-aucpr:0.92766	validation-aucpr:0.28865
[200]	train-aucpr:0.93472	validation-aucpr:0.38738[100]	train-aucpr:0.92669	validation-aucpr:0.51609

[378]	train-aucpr:0.94348	validation-aucpr:0.35975
[225]	train-aucpr:0.92773	validation-aucpr:0.28916
[200]	train-aucpr:0.93255	validation-aucpr:0.50924
[300]	train-aucpr:0.93435	validation-aucpr:0.38661
[249]	train-aucpr:0.93235	validation-aucpr:0.48647
[0]	train-aucpr:0.50232	validation-aucpr:0.02374
[100]	train-aucpr:0.91731	validation-aucpr:0.31218

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1277.87it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1247.27it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1355.09it/s]
Bootstrapping pr_auc:  70%|██████▉   | 699/1000 [00:00<00:00, 1103.92it/s]

[400]	train-aucpr:0.93667	validation-aucpr:0.46944
[0]	train-aucpr:0.56007	validation-aucpr:0.03697
[200]	train-aucpr:0.92029	validation-aucpr:0.30774
[0]	train-aucpr:0.50203	validation-aucpr:0.03592
[240]	train-aucpr:0.91819	validation-aucpr:0.31882
[500]	train-aucpr:0.93749	validation-aucpr:0.46744
[100]	train-aucpr:0.95380	validation-aucpr:0.26200
[100]	train-aucpr:0.91929	validation-aucpr:0.30841
[600]	train-aucpr:0.93791	validation-aucpr:0.46509
[200]	train-aucpr:0.95469	validation-aucpr:0.26033
[649]	train-aucpr:0.93839	validation-aucpr:0.42248
[200]	train-aucpr:0.91519	validation-aucpr:0.28904
[300]	train-aucpr:0.95528	validation-aucpr:0.25775
[300]	train-aucpr:0.91522	validation-aucpr:0.30943
[352]	train-aucpr:0.95598	validation-aucpr:0.26285
[400]	train-aucpr:0.91675	validation-aucpr:0.27372

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1235.56it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1329.59it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1283.18it/s]
Bootstrapping pr_auc:  56%|█████▌    | 560/1000 [00:00<00:00, 1297.73it/s]

[0]	train-aucpr:0.55389	validation-aucpr:0.04033
[0]	train-aucpr:0.54331	validation-aucpr:0.03326
[500]	train-aucpr:0.92361	validation-aucpr:0.27073
[503]	train-aucpr:0.92357	validation-aucpr:0.27062
[100]	train-aucpr:0.93849	validation-aucpr:0.47830
[100]	train-aucpr:0.93178	validation-aucpr:0.24059
[0]	train-aucpr:0.54805	validation-aucpr:0.02626
[200]	train-aucpr:0.93919	validation-aucpr:0.47498
[236]	train-aucpr:0.93772	validation-aucpr:0.47639
[100]	train-aucpr:0.94071	validation-aucpr:0.15519
[200]	train-aucpr:0.93851	validation-aucpr:0.22809
[0]	train-aucpr:0.53631	validation-aucpr:0.02587
[300]	train-aucpr:0.94028	validation-aucpr:0.22614
[200]	train-aucpr:0.94343	validation-aucpr:0.15448
[307]	train-aucpr:0.94085	validation-aucpr:0.21496
[100]	train-aucpr:0.92331	validation-aucpr:0.17409

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1106.33it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1306.51it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1156.84it/s]
Bootstrapping pr_auc:  80%|███████▉  | 795/1000 [00:00<00:00, 1585.01it/s]

[200]	train-aucpr:0.92512	validation-aucpr:0.17670
[208]	train-aucpr:0.92454	validation-aucpr:0.17801
[300]	train-aucpr:0.94604	validation-aucpr:0.13767
[307]	train-aucpr:0.94533	validation-aucpr:0.13917
[0]	train-aucpr:0.57356	validation-aucpr:0.03141
[100]	train-aucpr:0.92949	validation-aucpr:0.40894
[200]	train-aucpr:0.93181	validation-aucpr:0.40655
[0]	train-aucpr:0.51733	validation-aucpr:0.03400
[300]	train-aucpr:0.93217	validation-aucpr:0.41238
[0]	train-aucpr:0.58713	validation-aucpr:0.03169
[100]	train-aucpr:0.93143	validation-aucpr:0.35661

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1310.27it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1471.85it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1571.38it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1152.23it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1517.71it/s]

[385]	train-aucpr:0.93297	validation-aucpr:0.40140
[0]	train-aucpr:0.54071	validation-aucpr:0.03526
[200]	train-aucpr:0.93648	validation-aucpr:0.40608
[0]	train-aucpr:0.55999	validation-aucpr:0.02947[100]	train-aucpr:0.95603	validation-aucpr:0.09529

[300]	train-aucpr:0.93832	validation-aucpr:0.35380
[200]	train-aucpr:0.95792	validation-aucpr:0.10147
[100]	train-aucpr:0.92532	validation-aucpr:0.70629
[100]	train-aucpr:0.91560	validation-aucpr:0.42495
[300]	train-aucpr:0.95722	validation-aucpr:0.10025
[385]	train-aucpr:0.94034	validation-aucpr:0.36133
[200]	train-aucpr:0.92711	validation-aucpr:0.71038
[200]	train-aucpr:0.91835	validation-aucpr:0.42822
[0]	train-aucpr:0.59373	validation-aucpr:0.04033
[352]	train-aucpr:0.95681	validation-aucpr:0.10433
[300]	train-aucpr:0.92809	validation-aucpr:0.71038
[100]	train-aucpr:0.91960	validation-aucpr:0.57227
[300]	train-aucpr:0.91869	validation-aucpr:0.42918
[354]	train-aucpr:0.91971	validation-aucpr:0.42182
[400]	train-aucpr:0.92950	validation-aucpr:0.70146

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1134.99it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1376.12it/s]
Bootstrapping pr_auc:   0%|          | 0/1000 [00:00<?, ?it/s]1235.89it/s]

[0]	train-aucpr:0.52823	validation-aucpr:0.03461
[500]	train-aucpr:0.93089	validation-aucpr:0.72359
[200]	train-aucpr:0.92581	validation-aucpr:0.55699
[561]	train-aucpr:0.93214	validation-aucpr:0.71923
[300]	train-aucpr:0.92828	validation-aucpr:0.52776
[100]	train-aucpr:0.90567	validation-aucpr:0.36857
[0]	train-aucpr:0.55591	validation-aucpr:0.03155
[344]	train-aucpr:0.92944	validation-aucpr:0.52776
[200]	train-aucpr:0.91135	validation-aucpr:0.42677
[100]	train-aucpr:0.95247	validation-aucpr:0.20828
[200]	train-aucpr:0.95568	validation-aucpr:0.21064
[300]	train-aucpr:0.91173	validation-aucpr:0.43911
[0]	train-aucpr:0.57430	validation-aucpr:0.02667
[0]	train-aucpr:0.54650	validation-aucpr:0.03183
[300]	train-aucpr:0.95713	validation-aucpr:0.20086

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1419.83it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1136.58it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1255.24it/s]
Bootstrapping pr_auc:  27%|██▋       | 272/1000 [00:00<00:00, 1294.65it/s]

[382]	train-aucpr:0.91234	validation-aucpr:0.42367
[353]	train-aucpr:0.95862	validation-aucpr:0.19553
[100]	train-aucpr:0.91262	validation-aucpr:0.48939
[100]	train-aucpr:0.92512	validation-aucpr:0.34688
[200]	train-aucpr:0.91400	validation-aucpr:0.49537
[200]	train-aucpr:0.92514	validation-aucpr:0.35568
[0]	train-aucpr:0.55065	validation-aucpr:0.03644
[300]	train-aucpr:0.91429	validation-aucpr:0.49829
[300]	train-aucpr:0.92524	validation-aucpr:0.34649
[100]	train-aucpr:0.96543	validation-aucpr:0.29321
[374]	train-aucpr:0.91436	validation-aucpr:0.50008
[353]	train-aucpr:0.92676	validation-aucpr:0.34382
[200]	train-aucpr:0.96712	validation-aucpr:0.30010
[0]	train-aucpr:0.57260	validation-aucpr:0.03198
[300]	train-aucpr:0.96698	validation-aucpr:0.30171

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1270.52it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1256.97it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1227.34it/s]
Bootstrapping pr_auc:  50%|█████     | 501/1000 [00:00<00:00, 1316.85it/s]

[100]	train-aucpr:0.92832	validation-aucpr:0.46412
[400]	train-aucpr:0.96977	validation-aucpr:0.29674
[0]	train-aucpr:0.58415	validation-aucpr:0.03021
[0]	train-aucpr:0.50911	validation-aucpr:0.04052
[200]	train-aucpr:0.92894	validation-aucpr:0.54588
[500]	train-aucpr:0.96986	validation-aucpr:0.30120
[100]	train-aucpr:0.93832	validation-aucpr:0.33377
[514]	train-aucpr:0.96988	validation-aucpr:0.29942
[100]	train-aucpr:0.90668	validation-aucpr:0.44238
[300]	train-aucpr:0.92950	validation-aucpr:0.53730
[200]	train-aucpr:0.94096	validation-aucpr:0.34066
[200]	train-aucpr:0.91507	validation-aucpr:0.41096
[400]	train-aucpr:0.93150	validation-aucpr:0.55009
[300]	train-aucpr:0.94039	validation-aucpr:0.33992
[300]	train-aucpr:0.91835	validation-aucpr:0.39027
[304]	train-aucpr:0.91821	validation-aucpr:0.38648
[317]	train-aucpr:0.94038	validation-aucpr:0.34114
[500]	train-aucpr:0.93187	validation-aucpr:0.54216

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1375.34it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1294.85it/s]
Bootstrapping pr_auc:  94%|█████████▍| 940/1000 [00:00<00:00, 1254.98it/s]

[594]	train-aucpr:0.93206	validation-aucpr:0.54560

Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1173.31it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1252.16it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1260.40it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1284.52it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1362.50it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1314.43it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1505.51it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1437.93it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1422.51it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1530.14it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1477.62it/s]
Bootstrapping pr_auc: 100%|██████████| 1000/1000 [00:00<00:00, 1456.31it/s]

bound,Metrics,estimate,lower,upper,models
0,AUPRC_value,44.7082,22.3797,63.8181,XGBoost (VL diag + 2 & SMOTE)
1,AUROC_value,93.6593,87.3107,98.2103,XGBoost (VL diag + 2 & SMOTE)
2,Accuracy,88.6979,84.5921,92.1450,XGBoost (VL diag + 2 & SMOTE)
3,Accuracy_train,87.2825,83.2269,91.4901,XGBoost (VL diag + 2 & SMOTE)
4,NPV,99.3846,98.3271,100.0000,XGBoost (VL diag + 2 & SMOTE)
5,Precision,19.1441,13.5135,25.7627,XGBoost (VL diag + 2 & SMOTE)
6,Sensitivity,82.2000,50.0000,100.0000,XGBoost (VL diag + 2 & SMOTE)
7,Specificity,88.9003,84.4237,92.8349,XGBoost (VL diag + 2 & SMOTE)

# Save model trained

In [9]:
path = os.getcwd()

state = {
    "xgb_fil_list": xgb_fil_list,
    "xgb_vlsymp_sim_list": xgb_vlsymp_sim_list,
    "xgb_vldiag_list": xgb_vldiag_list,
    "xgb_add1_list": xgb_add1_list,
    "xgb_add2_list": xgb_add2_list
}

save_file = os.path.join(path, "xgb_trained.pkl")

with open(save_file, "wb") as f:
    dill.dump(state, f)

#print(f"Saved to: {save_file}")

In [10]:
path = os.getcwd()

state = {
    "xgb_fil_summary": xgb_fil_summary,
    "xgb_vlsymp_sim_summary": xgb_vlsymp_sim_summary,
    "xgb_vldiag_summary": xgb_vldiag_summary,
    "xgb_add1_summary": xgb_add1_summary,
    "xgb_add2_summary": xgb_add2_summary
}

save_file = os.path.join(path, "xgb_metric_summary.pkl")

with open(save_file, "wb") as f:
    dill.dump(state, f)

#print(f"Saved to: {save_file}")